### ISSUE TITLE
[ENHANCEMENT] Redo interactions

### ISSUE THREAD

**Issue by JnKTechstuff** [xXJamieXx/paradox-bugs#10]
**Your Discord Name**
[Enter your Discord name]

**Describe the annoyance**
Interactions on radial menu should be in the 3rd eye not in the F1 menu which allows mistakes.

**Requested behavior**
Better options in the radial menu and most in 3rd eye

**Comment by xXJamieXx** [comment]
Done in https://github.com/xXJamieXx/Paradox-3.0/commit/589f78077080e84a47f06a9679f2e055b1fd9d16
