### ISSUE TITLE
[BUG] doubling time and fine incorrectly in MDT

### ISSUE THREAD

**Issue by PadawanPepsi** [xXJamieXx/paradox-bugs#103]
**Your Discord Name**
PadawanPepsi#6898

**Describe the bug**
I have a arrest report #3605. It has three people attached the report. I gave each of them one singal charge.  That charge reccomended time and fine is 115 months and $1150. However when i gave each person their charge individually it stacked the time and fine for all three. So instead of the time being 115 and fine being $1150. The reccomended time is 345 months and $3450.

**To Reproduce**
[Steps to reproduce the bug]
1. Create an arrest report
2. Add multiple people to it
3. give each one a charge.

**Expected behavior**
Each person should only have a recommendation for their individual charges not everyone's in the report

**Screenshots**
https://i.imgur.com/liRZwsS.png

**Comment by xXJamieXx** [comment]
To clarify, its displaying the recommended fines/times as the combined value of the charges applied to ALL characters added to the arrest report. I've confirmed this to be the case but unsure of fix at this time.

**Comment by xXJamieXx** [comment]
Fixed.
