### ISSUE TITLE
[BUG] Transferring items when inventory is full

### ISSUE THREAD

**Issue by SterlingMoss** [xXJamieXx/paradox-bugs#104]
SterlingMoss#1596

I went to grab my gold coins out of my stash to sell them, they were in 2 stacks of 5 and 1 stack of 1 for 11 total coins. When I tried to put them in my pockets, I'm guessing that it was too much weight for my pockets; so instead of putting the coins back in my stash that I couldn't hold, a stack of 5 just outright disappeared. I'm guessing this might happen with other items too.

**To Reproduce**
[Steps to reproduce the bug]
1. Try to transfer gold coins from stash to pockets
2. 
3. 

**Expected behavior**
I would expect to have any gold coins I can't fit in my pockets go back in the stash box instead of disappearing.

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment]
There seems to be an issue where it will tell you that you're inventory is full but not block the transfer, this is causing those items to get deleted when over the max weight limit.

**Comment by JnKTechstuff** [comment]
fixed https://github.com/xXJamieXx/Paradox-3.0/pull/81
