### ISSUE TITLE
[BUG] Invisible item taking up space in glovebox

### ISSUE THREAD

**Issue by SterlingMoss** [xXJamieXx/paradox-bugs#105]
SterlingMoss#1596

There is an item taking up space in my glovebox that cannot be seen or removed. I'm not sure what the item is or why its there, so I'm not sure how to reproduce the bug.
![2022-01-12](https://user-images.githubusercontent.com/97280265/149118303-9a997359-4781-4cc7-b89a-1a7ffe12e530.png)

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment]
A fix was made to that vehicles glovebox, @SterlingMoss please confirm if it is fixed.

**Comment by SterlingMoss** [comment]
It is not fixed unfortunately:(

**Comment by SterlingMoss** [comment]
Okay I think I just did👍🏼 Thanks!
