### ISSUE TITLE
[BUG] 20L jerry can doesn't work

### ISSUE THREAD

**Issue by SterlingMoss** [xXJamieXx/paradox-bugs#107]
SterlingMoss#2596

I bought a 20L jerry can in the early days of the city, and wanted to use it since the gas pumps aren't currently functional. The $400 20L jerry can doesn't do anything, but the regular jerry can does.

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
I would expect a $400 jerry can to hold more than a regular jerry can, and would expect it to be able to fuel a car.

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by JnKTechstuff** [comment]
This item will be removed
