### ISSUE TITLE
Public Safety suddenly get full salary off duty

### ISSUE THREAD

**Issue by Sly-Panda** [xXJamieXx/paradox-bugs#109]
SlyPanda#8576

Public safety members whilst off duty are getting paid their full wage today instead of getting the basic salary when off duty.

**To Reproduce**

1.  Take a public safety job
2.  Go on then off duty
3.  Wait for the pay tick

**Expected behavior**
Get the regular unemployment salary when off duty

**Comment by StealthyRiot** [comment]
I can confirm this is happening to me too.

**Comment by JnKTechstuff** [comment]
Fixed: https://github.com/xXJamieXx/Paradox-3.0/commit/794fb770dcfca88f5c4f01dc7a1d30f4dd7f6ac5
