### ISSUE TITLE
[BUG] MDT Report Tab is still not able to be scrolled through

### ISSUE THREAD

**Issue by Petrovic247** [xXJamieXx/paradox-bugs#111]
**Your Discord Name**
PretenderPatrol#5993

**Describe the bug**
MDT Report tab still not showing all reports. It seems like the most recent report is at the bottom and the top is older ones. You still cannot scroll through all reports. Must search to find 3509 for example.

**To Reproduce**
[Steps to reproduce the bug]
1. Asked other officers to see if they could scroll through all reports. They were unable too.
2. 
3. 

**Expected behavior**
All reports are able to be scrolled through like Arrest reports.

**Screenshots**
https://i.imgur.com/HUhfQ2P.png
https://i.imgur.com/bi1lIbV.png

**Additional context**
[Add any other context about the problem here]

**Comment by JnKTechstuff** [comment]
The fact you can not see more than 20 reports is NOT a bug. Its for data saving. The reports are not missing either, I think you are mistaking reports vs arrests and I suggest consulting your COC. 

The ordering issue is fixed here: https://github.com/xXJamieXx/Paradox-3.0/pull/82
