### ISSUE TITLE
[BUG] StormRams no longer work

### ISSUE THREAD

**Issue by monk3ythund3r** [xXJamieXx/paradox-bugs#114]
**Your Discord Name**
Monk3yThund3r

**Describe the bug**
When we responded to a Residential Alarm we attempted to enter the house but our StormRams were not working.
**To Reproduce**
[Steps to reproduce the bug]
1. Approach the house
2. Put the StormRam in one of your top pockets
3. Flex that muscle

**Expected behavior**
Using the StormRam gave us entry into the house

**Screenshots**
https://i.imgur.com/t15Ec9l.jpeg
https://i.imgur.com/kKWlAjF.png

**Additional context**
[Add any other context about the problem here]

**Comment by JnKTechstuff** [comment]
Operator error
