### ISSUE TITLE
[BUG] Vehicle Option Menu

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#115]
**Your Discord Name**
OwlCherry#6969

**Describe the bug**
Having an issue where when im within my PD vehicle, i could be attempting a 10-11 or a 10-80 when suddenly the vehicle option menu opens up out of no where causing me to crash.

ive attempted to reproduce this as ive heard people say its somehow tied to the scroll wheel on the mouse, to no avail. its not any sort of accidental pressing of the [.] key as my left hand is on wasd and my right is on the mouse. Was unable to locate any other bindings in keybinds that could be causing the issue

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by JnKTechstuff** [comment]
Fixed: https://github.com/xXJamieXx/Paradox-3.0/commit/dd119b0218293e496ece7e5195aeb96289449f67
