### ISSUE TITLE
[BUG] Danny Face/Hair

### ISSUE THREAD

**Issue by SterlingMoss** [xXJamieXx/paradox-bugs#117]
SterlingMoss#1596

I went to change my outfit in the apartments and it changed my face and my hair to bright green again. Can't color eyebrows or facial hair any color but bright green.

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment]
Fixed in business update.
