### ISSUE TITLE
[BUG] Gun durability extremely low

### ISSUE THREAD

**Issue by SterlingMoss** [xXJamieXx/paradox-bugs#118]
SterlingMoss#1596

When shooting a gun, the durability goes down extremely fast. I wasn't able to get through more than a magazine or two before my gun broke. I've been hearing of a bunch of people having this issue, especially when shooting at cars. It seems like the more damage you do, the more durability is taken away. Given the price of guns I would expect to go through many magazines before having to replace my pistol.

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment]
Fixed.
