### ISSUE TITLE
MDT Profile Searching

### ISSUE THREAD

**Issue by prdxFairBZ** [xXJamieXx/paradox-bugs#119]
**Your Discord Name**
Bru
**Describe the bug**
Searching common names are impossible to find.

**To Reproduce**
[Steps to reproduce the bug]
1. Search Jimmy Johnson
2. 
3. 

**Expected behavior**
Jimmy Johnson should return when searched, unfortunately you cannot find him because there are too many jimmys and too many johnsons, You also cannot search his full name as you can only search by first and last name. You also cannot search by citizen ID number or Fingerprint.

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment]
Name searching needs work so names can be searched easier however in the meantime I'm adding search by Citizen ID. Will be available next restart.

**Comment by OwlCherry** [comment]
Just had a ticket that a Smith Will was also unable to be located within MDT

**Comment by OwlCherry** [comment]
In relation to this, i managed to get video showing Citizen ID num, and name searches failing to locate civilian. video is here

https://streamable.com/jpeyfk

**Comment by xXJamieXx** [comment]
Irrelevant since MDT update.
