### ISSUE TITLE
[ENHANCEMENT] Jerry cans are Gas stations.

### ISSUE THREAD

**Issue by stbadreturns** [xXJamieXx/paradox-bugs#120]
**Your Discord Name**
Stbadreturns#9043

**Describe the annoyance**
jerry cans act like gas pumps and charge us as such and never need refilled/ 

**To Reproduce**
[Steps to reproduce the annoyance]
1.  pull out jerry can
2.  refuel vehicle
3.  see that it cost money.

**Requested behavior**
it act like a jerry can where we use it and need to refuel./maybe make a third eye option for tow. 

**Screenshots**
![20220114141044_1](https://user-images.githubusercontent.com/47409242/149571633-58cab52e-b3fd-4dbb-822e-d815cbfa43d9.jpg)

**Additional context**
[Add any other context about the enhancement here]

**Comment by JnKTechstuff** [comment]
Simple wording change needed. Also needs ammo set properly on jerry can or remove it

**Comment by xXJamieXx** [comment]
Fixed next restart.

**Comment by TeddyNM** [comment]
Since the change, you can't buy jerry cans at the gas pump nor refill them the third eye doesn't work on them at all you can only refuel your car. Not sure if this is a bug or you've changed locations for this

**Comment by xXJamieXx** [comment]
Seems to be working now
