### ISSUE TITLE
[BUG] BENNY'S menu above MRPD

### ISSUE THREAD

**Issue by 211Walker** [xXJamieXx/paradox-bugs#121]
**Your Discord Name**
tonytone883

**Describe the bug**
There appears to be a BENNY'S menu above MRPD. As seen in the picture below.  
Once over MRPD I hit my "LEFT BUMPER" on my Xbox control and I spawn next to the front door of MRPD with a BENNY'S menu.   

https://i.imgur.com/vtmgveO.jpeg
https://i.imgur.com/F10f0ll.jpeg
https://www.twitch.tv/videos/1263010964
https://www.twitch.tv/videos/1263010967

**Comment by JnKTechstuff** [comment]
Fixed: https://github.com/xXJamieXx/Paradox-3.0/commit/1f3fdb6dbd7e7d0d3b4d5493ae793ac7eac4f4d8
