### ISSUE TITLE
[BUG] Cant search anyone on mdt

### ISSUE THREAD

**Issue by PadawanPepsi** [xXJamieXx/paradox-bugs#123]
**Your Discord Name**
PadawanPepsi#6898

**Describe the bug**
when you search a single name the refresh ring just spins

**To Reproduce**
[Steps to reproduce the bug]
1. try to search someone on mdt
2. 
3. 

**Screenshots**
![image](https://user-images.githubusercontent.com/96961442/149605569-abb64930-abbf-4644-b128-49bf4c0bb851.png)

**Comment by JnKTechstuff** [comment]
Fixed in: https://github.com/xXJamieXx/Paradox-3.0/commit/eaededa040ea82e41d6232325c7c56c1aebb86f8
