### ISSUE TITLE
[BUG] Uniforms still changing hair color and face of thee person

### ISSUE THREAD

**Issue by Timmy636** [xXJamieXx/paradox-bugs#124]
**Your Discord Name**
Timmy#8418

**Describe the bug**
I don't know why but whenever I change my clothes two times when I get into the server it changes my hair and color of my face and shape of my face like jesus 

**To Reproduce**
[Steps to reproduce the bug]
1. Log into the server 
2. Go to a any place to change your clothes with your existing saved clothes
3. Press more than 3 clothes 

**Expected behavior**
Change clothes to without it changing your hair, face or color of your 

**Screenshots**
https://medal.tv/games/gta-v/clips/7QlvG9VinvGPc/d1337qtGDuNu?invite=cr-MSxEeHEsMzY5ODkzNDgs

**Additional context**
[Add any other context about the problem here]

**Comment by JnKTechstuff** [comment]
Hair and such are intended to be saved with each outfit
