### ISSUE TITLE
Keybind for Cinematic

### ISSUE THREAD

**Issue by prdxFairBZ** [xXJamieXx/paradox-bugs#125]
**Your Discord Name**
Bru

**Describe the annoyance**
Cinematic is worthless without a keybind to do it on the fly in roleplay.

**To Reproduce**
[Steps to reproduce the annoyance]
Leave it as is.

**Requested behavior**
1. Press a Button
2. HUD Enter Cinematic
3. Press again to exit Cinematic

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by JnKTechstuff** [comment]
Fix in: https://github.com/xXJamieXx/Paradox-3.0/commit/a0bdafb8243e14772925270bd8a8e15d9daac310

Adds `/cinematicmode` to be used in `/binds`
