### ISSUE TITLE
[BUG] Pillbox killing you after getting checked out

### ISSUE THREAD

**Issue by McEwann** [xXJamieXx/paradox-bugs#126]
**Your Discord Name**
McEwan#9999

**Describe the bug**
Intermittent issue. after being checked out and appearing in the lobby, dropping dead and having to be moved to check back in

**To Reproduce**
Intermittent happened about 3 times to me yesterday, EMT saw it happen and said it's been happening to other people.

**Expected behavior**
Not die after being checked out of Pillbox

**Screenshots**
Screen capture is disabled as it messes my FiveM up

**Additional context**
N/A

**Comment by xXJamieXx** [comment]
Can't reproduce.
