### ISSUE TITLE
[BUG] Using Slushies

### ISSUE THREAD

**Issue by BrotherDayZ** [xXJamieXx/paradox-bugs#127]
**Your Discord Name**
BDZ#0001

**Describe the bug**
When consuming a slushy, instead of only consuming 1 it consumes 2

**Comment by JnKTechstuff** [comment]
Fixed by @xXJamieXx: https://github.com/xXJamieXx/Paradox-3.0/commit/4665360fcd05e74b122f7ba57e166f7d1a94e323
