### ISSUE TITLE
[BUG] Limited clothing options and menu doesn't close when discarding changes

### ISSUE THREAD

**Issue by SuperGamerTron** [xXJamieXx/paradox-bugs#128]
**Your Discord Name**
SuperGamerTron#2394

**Describe the bug**
When changing clothes, I am only able to change about half of the clothing types and can only select a few variations. When discarding changes, the clothing menu doesn't close and an error is outputted to the console.

**To Reproduce**
1. Open clothing store
2. Change clothes
3. Discard changes

**Expected behavior**
Select many clothing variations, and menu closes when discarding changes.

**Screenshots**
![console error](https://user-images.githubusercontent.com/45374546/149640026-b120d76b-3fa0-4929-bc36-f920c4300093.png)

**Additional context**
The first time I joined the server I had the default character, and the second time I joined it was randomized. It's been stuck like this ever since.

https://user-images.githubusercontent.com/45374546/149640000-96817dd8-586f-4e81-bb57-ad0b8f569ac8.mp4

https://user-images.githubusercontent.com/45374546/149640003-68f3b564-c055-431a-a58f-129734d75467.mp4

**Comment by xXJamieXx** [comment]
@SuperGamerTron It seems your character bugged out when you first created it. You're best bet is to delete the character and start over because you're not gonna be able to do much with that character.
