### ISSUE TITLE
[BUG] Camera app bug 

### ISSUE THREAD

**Issue by supawiz6991** [xXJamieXx/paradox-bugs#129]
**Your Discord Name**
Supawiz6991

**Describe the bug**
When trying to use the camera app on the phone, when you left click to take a picture while in the camera app, it leaves the camera app and goes into a loop where your characters arm moves in a circular motion and the camera moves back and forth between first and third person. The loop can be ended by clicking on the camera app again and the right clicking once its up.

**To Reproduce**
[Steps to reproduce the bug]
1. Bring up the phone
2. Click the camera app 
3. Left click once the camera app is open and the bug should occur. 
4. To recover from the bug, click the  camera app again and then right click.

**Expected behavior**
I expected the camera app to take a picture.

**Screenshots**
A screen shot isn't able to show this issue but I did capture some video of the bug which is available at here -> https://youtu.be/LB8Z20c4dQo

**Additional context**
My fivem is stock. No mods and no graphics packs.

**Comment by supawiz6991** [comment]
I assume the updated flags mean that this app should he avoided, correct?

**Comment by JnKTechstuff** [comment]
The whole phone will be eventually be redone. We are awaiting framework support of NPWD phone which is an amazing community project.
