### ISSUE TITLE
[BUG] Vehicle Color

### ISSUE THREAD

**Issue by kingtortle** [xXJamieXx/paradox-bugs#130]
**Your Discord Name**
Tortle#0499

**Describe the bug**
Bennies still not letting me change my car color even after the new mod shop and color fix.

**To Reproduce**
1. My vehicle is the deviant
2. take it to bennies and try to change color
3. 

**Expected behavior**
color to change

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment]
Compiling into #137 as it has more detail.
