### ISSUE TITLE
[BUG] Stress grows too fast

### ISSUE THREAD

**Issue by xQuezii** [xXJamieXx/paradox-bugs#134]
**Your Discord Name**
[Enter your discord name]
xQuezii#0899
**Describe the bug**
[A clear and concise description of what the bug is]
Stress is rising way too fast in my opinion, I have had a few others tell me the same since I flew in today
**To Reproduce**
[Steps to reproduce the bug]
1. Drive short distance with seatbelt on
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]
I should have been able to drive back and forth with a seatbelt on for at least a few trips without having to relieve stress.
**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by OwlCherry** [comment]
it also takes far too long to destress. i have only destressed approx 10% in an hour

**Comment by Brewheem** [comment]
when riding a motorcycle you cant go very far due to no seatbelt being available and stress rising quickly, hoping the seatbelt could maybe be removed from the motorcycle.
