### ISSUE TITLE
Cant move anything in apartment stash.

### ISSUE THREAD

**Issue by richard19999** [xXJamieXx/paradox-bugs#136]
Zeal_Undy#5506

**Describe the bug**
So before when the stash in your apartment was 2000 weight and i had 1800 in there. Now the stash is 1000 and i cant move anything in or out. Ive tried relogging multiple times and walking in out of apartment 

**To Reproduce**
[Steps to reproduce the bug]
1. Go into stash
2. Cant move any items out 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]
Be able to move items back in forth.
**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]
https://medal.tv/games/requested/clips/838P55rPO3Me6/d1337BieumZG?invite=cr-MSxDU1MsNDYwOTI4OTQs

**Comment by xXJamieXx** [comment]
Cannot reproduce.
