### ISSUE TITLE
[BUG] Color Changing Options at Bennys not working

### ISSUE THREAD

**Issue by Person-AL767** [xXJamieXx/paradox-bugs#137]
**Your Discord Name**
Person__AL#7454

**Describe the bug**
I am unable to see the changes to car color when cycling through all colors on a car I just purchased- this was not happening on any of my other cars and still doesn't happen if I take my old ones to Benny's only my new one (_Karin Previon_).  However- when I went to test the metal colors (gold, chrome), you could see that the chrome/gold overlay is actually _kinda_ working with the car color, like it's trying to show up, but the current color is somewhat locked on there. But any other primary color (matte, regular, etc) doesn't show up at all.

I did swap the colors of the vehicle when purchasing at the store (sedans store) and selected the orange- but i had intentions to change at bennys after the set up. Wonder if pre-selecting the color in the vehicle shop is overriding any color selection at Bennys?

**To Reproduce**
[Steps to reproduce the bug]
1. buy a car, select a random color (both a primary and a secondary) with the store before leaving (I selected a burnt orange)
2. put car in garage, take out (per standard Paradox recommendation to put car in garage right after buying)
3. take to bennys, attempt to change primary color- should not be able to change
4. try to use the chrome/gold overlay- you'll see what im talking about how it shows up like it's doing something, but the orange still overrides it.

**Expected behavior**
being able to select a car color/livery at the store, but also being able to update no problem at the Bennys after

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
I have 3 other cars with this character- all cars been able to be updated/tweaked with colors. I bought this car (previon) today (1/17/22) and the color changing is not working now. I feel like it has to be something to do with pre-selecting a color at the store, vs just buying the car w/o selecting a color, but i could be wrong.

**Comment by Strandis** [comment]
Also doesn't work on the sultan classic.

**Comment by Tobjaks** [comment]
Also does not work on the Exemplar.

**Comment by Th1Con** [comment]
Also doesn't work on Bison

**Comment by xXJamieXx** [comment]
This was fixed. https://github.com/xXJamieXx/Paradox-3.0/commit/2bce7617df8d3bcfb843c4e0789a1104ce8e56e8
