### ISSUE TITLE
Can't get into my stash

### ISSUE THREAD

**Issue by Megs02** [xXJamieXx/paradox-bugs#140]
**Your Discord Name**
megs02#1739

**Describe the bug**
Whenever I go into my stash in my apartments and put something in or take something out it kicks me out of my stash and then when I try to go back in it shows there is nothing in my stash. Also sometimes if I take stuff out of my stash and check my pockets after the items aren't in my pockets so I go back to my stash and try to grab them again but it shows nothing in my stash.

**To Reproduce**
[Steps to reproduce the bug]
1.  Open up stash
2.  Put something in or take something out and get kicked out
3.  Try and open up stash again and it shows nothing in my stash 

**Expected behavior**
Being able to move stuff in and out of my stash without getting kicked out and not being able to get back in

**Screenshots**
![Screenshot (88)](https://user-images.githubusercontent.com/97911356/149824083-7a860c56-5636-4804-a1d9-9fb4b2299f48.png)

**Additional context**

**Comment by xXJamieXx** [comment]
Can't reproduce.
