### ISSUE TITLE
Both Fully upgraded cars are worse then stock

### ISSUE THREAD

**Issue by Chull912** [xXJamieXx/paradox-bugs#141]
**Your Discord Name**
Bjorn#1739

**Describe the bug*
My penumbras acceleration got worse and i can barely reach 100 with full upgrades which is way worse then what it was stock. Also my other car "Annis Remus" sounds like its shifting gears at super low rpms causing my accelation to be even worse then it was stock while its also fully upgraded as well.

**To Reproduce**
[Steps to reproduce the bug]
1. go to bennys
2. buy best performance upgrades for both penumbra and remus 

**Expected behavior**
The fully upgraded penumbra will feel slower then it did stock. The remus sounds like its shifting gears at way too low of rpms. My upgrades were fine and made my cars faster all day up until yesterdays evening tsunami on the 16th of January.

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
Also the Penumbra ff is currently slower then the normal penumbra which should not be the case considering the FF is twice as much money and its the formula edition of the two.

**Comment by JnKTechstuff** [comment]
GTA bug not us
