### ISSUE TITLE
[BUG] Eating is stressful

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#144]
**Your Discord Name**
OwlCherry#6969

**Describe the bug**
i eat sandwhich i gain 1/2 stess

**To Reproduce**
[Steps to reproduce the bug]
1. grab sammy.
2. eat sammy
3.  feel stressed

**Expected behavior**
i find eating very soothing. i would not expect to get stressed highly after eating

**Screenshots**
https://streamable.com/amgl9g

**Additional context**

**Comment by xXJamieXx** [comment]
Cannot reproduce.
