### ISSUE TITLE
[BUG] Gun powder on clothing when NOT shooting

### ISSUE THREAD

**Issue by PadawanPepsi** [xXJamieXx/paradox-bugs#148]
**Your Discord Name**
PadawanPepsi#6898

**Describe the bug**
Unsure if this is an actual bug but i find sometimes ill pull out a gun IN A CAR ill get gunpower on clothing even when not shooting. 

**To Reproduce**
[Steps to reproduce the bug]
1.  Sit in a car pull out a pistol and point it
2. always happened in a PD car. never tested in a civ car
3. 

https://user-images.githubusercontent.com/96961442/150053497-4b840b5a-b6f7-4517-ad94-226e93cbcc1d.mp4

**Comment by jibbersh** [comment]
Does not happen with civilian cars + guns.

**Comment by Sly-Panda** [comment]
Cannot reproduce.
