### ISSUE TITLE
[BUG] Repeated fake explosions

### ISSUE THREAD

**Issue by supawiz6991** [xXJamieXx/paradox-bugs#149]
**Your Discord Name**
supawiz6991#5529

**Describe the bug**
Explosion effects keep triggering even though there isn't actually explosions. I drove from postal code 17 to postal code 501 to get to the jewelry guy and the explosions followed.
A buddy of mine also had this happening at the same time. Another person in general-chat said they had encountered that as well and closing and reopening the game fixed it.

**To Reproduce**
[Steps to reproduce the bug]
1. Unknown how to get it to start.
2. Close the game and restart to get it to stop
3. 

**Expected behavior**
Not get random repeating explosion effects for no reason.

**Screenshots**
Here is a youtube clip of what I was seeing -> https://youtu.be/Mjj2ITxTjqA

**Additional context**
Stock client

**Comment by JnKTechstuff** [comment]
This was stress effects, which are now a blur instead of shake
