### ISSUE TITLE
[BUG] Garbage bin not working at postal 363

### ISSUE THREAD

**Issue by Strandis** [xXJamieXx/paradox-bugs#15]
**Your Discord Name**
Axel

**Describe the bug**
There is no way to interact with the bins at postal 363 and therefore can't collect any trash. 

**To Reproduce**
Bug was reported, not sure if there's an easy way to reproduce.

**Expected behavior**
Collect the trash from the bins.

**Screenshots**
![CD14523A-9358-4D8D-8120-75BA3E324063](https://user-images.githubusercontent.com/26605406/147853737-e5960a1f-77ed-4f91-8ff5-9d53dcc41ae0.jpeg)
![F111CDA3-C77C-4AD6-8711-421BA455D55E](https://user-images.githubusercontent.com/26605406/147853740-4232fda0-d05c-4c32-b10d-596e6fc4d22b.jpg)
![87F548E9-9772-4B5C-B544-DEA0C7C3B92A](https://user-images.githubusercontent.com/26605406/147853744-71ba737d-669f-4cd9-ac39-953fb512be2d.jpg)

**Comment by prdxFairBZ** [comment]
I believe this is referencing the actual garbage job, as in the bag entities are not spawning at this location
