### ISSUE TITLE
[BUG] Car locks not working properly

### ISSUE THREAD

**Issue by SterlingMoss** [xXJamieXx/paradox-bugs#156]
SterlingMoss#1596

I'm sure this is well known by the devs, but just in case I'd like to report it since its not showing up on the list. Car locks have been behaving very strangely, not letting you into your own car or any passengers without putting forth a lot of effort. The only way I have been able to get a passenger and myself in a car is to first unlock the car 3 times, let the passenger in, then unlock again so the driver can get in.

**Comment by JnKTechstuff** [comment]
Fixed: https://github.com/xXJamieXx/Paradox-3.0/commit/eaca289c9a837ad1bac3be4ea06b62fb7a2d9db4
