### ISSUE TITLE
[BUG] Car doors unlocking

### ISSUE THREAD

**Issue by baxepw** [xXJamieXx/paradox-bugs#161]
**Your Discord Name**
baxe#0666

**Describe the bug**
[A clear and concise description of what the bug is]
When trying to get into someones car even if it is their car or a local car the driver has to unlock the car like 5 times whilst passenger has to repeatedly try to get into the car.
**To Reproduce**
[Steps to reproduce the bug]
1. Someone drive car
2. Try to get passenger into car
3. Passenger struggles to get in

**Expected behavior**
[A clear and concise description of what you expected to happen]
You unlock the doors and people can enter the car
**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment]
This has been fixed.
