### ISSUE TITLE
[ENHANCEMENT] Lockpicks moving way too fast to use

### ISSUE THREAD

**Issue by SterlingMoss** [xXJamieXx/paradox-bugs#163]
SterlingMoss#1596

The new lockpick system has the lockpick speed going way too fast. Its too difficult to pick a car at its current rate.

**To Reproduce**
[Steps to reproduce the annoyance]
1. 
2. 
3. 

**Requested behavior**
[A clear and concise description of what you want to happen]

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
It varies in difficulty so its not always the same. Some things are harder than others.
