### ISSUE TITLE
[BUG] Hunting Durability Bugs 

### ISSUE THREAD

**Issue by OmegaGrape** [xXJamieXx/paradox-bugs#164]
**Your Discord Name**
OMEGA#0821

**Describe the bug**
When hunting if you try to place bait before the cooldown is up it will still use the bait up a little. Same goes for the hunting knife. I had an error when trying to skin a boar I basically used up the entire durability of the knife and kept getting an error every time i used it the durability when down whether I was actually skinning them or not 

**To Reproduce**
[Steps to reproduce the bug]

[Bait BUG]
1. Place bait 
2. Place a second one before the cooldown is up
3. check the durability

[Hunting Knife BUG]
1. Use the hunting knife (not to skin an animal)
2. check the durability 

**Expected behavior**
[A clear and concise description of what you expected to happen]
I would expect the hunting Knife and bait to only lose durability if actually used to skin an animal or place bait.

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]
If the usage durability is too hard or not worth the time to fix possible add a timer to the bait with a notification on when it can be placed again.

**Comment by xXJamieXx** [comment]
Fixed in business update.
