### ISSUE TITLE
[BUG] House robbery alarm goes off randomly

### ISSUE THREAD

**Issue by Nsmith2424** [xXJamieXx/paradox-bugs#165]
**Your Discord Name**
Pumpernikl#8493 

**Describe the bug**
Randomly the alarm when you are robbing houses will go off and contact police. There have been 2 instances now where that has happened to me.

**To Reproduce**
[Steps to reproduce the bug]
1. Get a house job (Normally the ones in paleto give me the issues)
2. Start robbing the house
3. Step outside and see cops (when you havent triggered the alarm)

**Expected behavior**
I would like to know that when i am breaking into a house that the alarm wont go off if i dont fill up the bar. 

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by JnKTechstuff** [comment]
Not a bit g
