### ISSUE TITLE
[BUG] Trunk scuffed

### ISSUE THREAD

**Issue by D0CTA** [xXJamieXx/paradox-bugs#168]
**Your Discord Name**
Chris Cutter 😈
(DOC#7777)

**Describe the bug**
when trying to access your trunk inventory you go into the animation + the trunk or tail gate opens and inventory does not show 
**To Reproduce**
[Steps to reproduce the bug]
1. Make sure vehicle is unlocked 
2. Press [tab] button to access trunk inventory at rear of vehicle

**Expected behavior**
access my trunk inventory 

**Screenshots**
![no trunk inv](https://user-images.githubusercontent.com/98142167/150510235-9517a7b2-b2a5-446f-9189-b44669b90a49.jpg)

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment]
Can't reproduce.
