### ISSUE TITLE
[BUG] Local cars unlocked

### ISSUE THREAD

**Issue by Tobjaks** [xXJamieXx/paradox-bugs#169]
**Your Discord Name**
tobjak#4191

**Describe the bug**
You don't need lockpick's or anything else to break into local cars. All you have to do is hit "F" and it breaks their window and lets you in.

**To Reproduce**
[Steps to reproduce the bug]
1. Walk up to a car, owned by a local
2. Hit F
3. Smash windows and drive away.

**Expected behavior**
Locked

**Comment by xXJamieXx** [comment]
Fixed https://github.com/xXJamieXx/Paradox-3.0/commit/fb8ea37985f776b51d2af397cbc8be3468bbd763
