### ISSUE TITLE
[BUG] HUD not updating health values properly

### ISSUE THREAD

**Issue by dave1880** [xXJamieXx/paradox-bugs#17]
**Your Discord Name**
dave1#1884

**Describe the bug**
Bleeding causing instant down 

**To Reproduce**
[Steps to reproduce the bug]
1. Fall off a very small roof
2. Wait 
3. 

**Expected behavior**
"You are bleeding a little bit" Caused me to go instantly down from 3/4 or so health after around a minute and a half even after using multiple gauze rolls

**Screenshots**
https://youtu.be/uBaaqPggNs4

**Comment by prdxFairBZ** [comment]
I was able to slightly reproduce this.
I believe the HUD may not be showing health loss when they are "bleeding a little" so eventually you drop from what your health was at when you obtained the status to 0.
