### ISSUE TITLE
[ENHANCEMENT] Hunting Issues

### ISSUE THREAD

**Issue by SterlingMoss** [xXJamieXx/paradox-bugs#170]
SterlingMoss#1596

So there may be some bugs involved in this post, but I decided it would probably be best to consolidate these issues into one post since they all have to do with hunting. 
Firstly, hunting isn't profitable, you end up taking a large deficit most of the time. The hunting knife durability is very low and the knife itself is too expensive. Also you may try to use your hunting knife and/or bait, and even if it doesn't use it, it will take a hit on its durability. You end up losing money hunting more often than not.
Secondly, the drop rate of high quality carcasses seems to be a bit too low. In my last run, I killed 15 animals, and received ten 1 star quality carcasses and 5 2 stars. I received zero 3 or 4 star carcasses. This resulted in a total lost of about $600. This may be somewhat circumstantial, but it seems to be the theme amongst hunters to have to hunt for hours to get a few of the carcasses you need and end up losing more money than you can potentially make in the process.

**Requested behavior**
Hunting knife durability increased, or decreased price. Higher drop rate of high quality carcasses. Lastly, hunting knife and bait should not take a hit on durability if not used.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
Fixed.
