### ISSUE TITLE
[ENHANCEMENT] Stress raises very quickly

### ISSUE THREAD

**Issue by SterlingMoss** [xXJamieXx/paradox-bugs#172]
SterlingMoss#1596

Stress raises so quickly that you need to have many on you if you're making runs up and down the city. Typically I'll need a slushy per trip from the city to paleto, and 1 for the way back, etc. 

**To Reproduce**
[Steps to reproduce the annoyance]
1. 
2. 
3. 

**Requested behavior**
[A clear and concise description of what you want to happen]

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
Fixed.
