### ISSUE TITLE
[BUG] Danny hair/face after tsunami

### ISSUE THREAD

**Issue by SterlingMoss** [xXJamieXx/paradox-bugs#173]
SterlingMoss#1596

Getting danny hair and face after tsunami and sometimes headpop. Tried to add a picture but its over 10mb

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment]
Duplicate of #117
