### ISSUE TITLE
[BUG] Gallery in MDT

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#174]
**Your Discord Name**
OwlCherry#6969

**Describe the bug**
Unable to upload images to Case Report in MDT

**To Reproduce**
[Steps to reproduce the bug]
1. go to case file. click plus sign in gallery
2. paste hyperlink
3. press enter, nothing saves and no image added

**Expected behavior**
it should add images like it does in evidence however it does not

**Screenshots**

**Additional context**
[Add any other context about the problem here]

**Comment by JnKTechstuff** [comment]
I'd it just the CID reports?

**Comment by OwlCherry** [comment]
From what I've discovered so far. I can test it for regular reports if you'd like

**Comment by JnKTechstuff** [comment]
I know arrests work and you're making sure the link ends in a `.png` or `.jpg`?

**Comment by OwlCherry** [comment]
Yes the arrest ones are fine. I've only noticed in cid so far

**Comment by JnKTechstuff** [comment]
MDT is deferred
