### ISSUE TITLE
[BUG] Max stress causing vehicle to completely stop

### ISSUE THREAD

**Issue by richard19999** [xXJamieXx/paradox-bugs#176]
**Your Discord Name**
[Enter your Discord name]
Zeal_Undy#5506
**Describe the bug**
[A clear and concise description of what the bug is]
Stress makes your screen goes black and makes the vehicle your driving come to a complete stop/ to much stress while driving 
**To Reproduce**
[Steps to reproduce the bug]
1. Drive fast
2. Get maxed out stress and keep driving fast for 10 more minutes
3. Screen will black out and vehicle will go from 100 mph to 0 in less than 0.1 of a second.

**Expected behavior**
[A clear and concise description of what you expected to happen]
I don't really know maxed out stress should effect a person. I just dont think it should end a scene that has been going on for 20-30 mins.
**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]
https://medal.tv/games/requested/clips/8ySQXN4SjG-Ul/d1337QzBm9tk?invite=cr-MSxDZ3MsNDYwOTI4OTQs

**Comment by richard19999** [comment]
Im not upest one bit. I dont know why you would assume that. I just didn't think stress should stop my vehicle in its tracks.

**Comment by JnKTechstuff** [comment]
The wording is weird. Anyway, we will look into the stopping of the vehicle part.
