### ISSUE TITLE
[BUG] Some glasses Missing

### ISSUE THREAD

**Issue by Hembry** [xXJamieXx/paradox-bugs#18]
**Your Discord Name**
_Hembry_#9901

**Describe the bug**
glasses are missing at the clothing store, some are there, but a large chunk is missing 

**To Reproduce**
[Steps to reproduce the bug]
1. Go to clothing store
2. Go to accessories 
3. Start going up in the sunglasses box, and you'll see a large chunk are missing

**Expected behavior**
Expected to find more glasses

**Screenshots**
N/A

**Comment by JnKTechstuff** [comment]
@xXJamieXx This one is all you

**Comment by xXJamieXx** [comment]
Resolved next server restart.
