### ISSUE TITLE
[BUG] Bank Transactions don't work

### ISSUE THREAD

**Issue by Doofensmirtzed** [xXJamieXx/paradox-bugs#181]
**Your Discord Name**
[DrPork#7560]

**Describe the bug**
[Whenever somebody tries to send me money over the bank app on the phone including a staff member i do not receive the money and the person loses there money Aswell. This has happened twice I don't remember who sent me money the first time but my friend(Steam is: BOrBON) sent me 1500 to the bank number 76614 and I didn't get anything, I have now received my 1500 but i would like my bank account to be able to work, All transactions BOrBON($1500), Jibberish($5,$10,$6,$5)]

**To Reproduce**
1. Enter my bank number into the app and send any amount of money or
2. Use my contact on the bank app and it also does not give me the money
3. 

**Expected behavior**
[I would get the money that was sent to me]

**Screenshots**

**Logs**
[Uploading CitizenFX_log_2022-01-23T203005.log…]

**Comment by xXJamieXx** [comment]
So we were using numbers that could have been linked to other players so I've changed it to a different system which should ensure unique account numbers and make sure the money goes to the right person.
