### ISSUE TITLE
mini map and pause map fuzzy

### ISSUE THREAD

**Issue by codyraygaming** [xXJamieXx/paradox-bugs#182]
my mini map and pause menu map are super fuzzy almost to the point where i cant see anything. postals are extremely hard to read.

**Comment by codyraygaming** [comment]
![A0075090-0A96-4A01-8C01-2C4BB05E88EB](https://user-images.githubusercontent.com/84162306/150833056-a9b2742b-e429-404c-a9fc-6a3aa87e3cae.jpg)

**Comment by codyraygaming** [comment]
![IMG_8468](https://user-images.githubusercontent.com/84162306/150833232-4119d5df-c89a-4b07-922b-766e819a6b26.jpg)

**Comment by Person-AL767** [comment]
This also happened to me this morning as well- so at least a sample of 2 confirmed fuzzy maps.

**Comment by codyraygaming** [comment]
![IMG_8472](https://user-images.githubusercontent.com/84162306/150834664-509624ac-3a5b-466f-800c-19483abefe7e.jpg)
![IMG_8469](https://user-images.githubusercontent.com/84162306/150834672-515155b8-05b1-4c3a-8ab2-b95ebc74bc8e.jpg)

**Comment by codyraygaming** [comment]
@Person-AL767 my game crashed and it fixed the map lol
