### ISSUE TITLE
[ENHANCEMENT] Whatsapp/Phone

### ISSUE THREAD

**Issue by Tobjaks** [xXJamieXx/paradox-bugs#183]
**Your Discord Name**
tobjak#4191

**Describe the annoyance**

**I know there's a new phone in the works, since I don't know when this is happening I was thinking to put this here anyways.**

1. Messages don't sort after most recent. It works when you're in-game. When you relog it goes back to unsorted/sorted after something else. (names maybe)

2. The phone notifications goes back and forth with twitter, calls and messages. There is no sound/signal when you get a text, which makes you sometimes miss incoming texts.

3. I am having issues scrolling all the way down in my messages, It wont let me click the last one without tabbing out to the home screen. 

![phonetext](https://user-images.githubusercontent.com/97873782/151002149-f3fa0789-f4cf-4643-8d35-a3c73ad18645.png)

**Requested behavior**
1. To always be sorted after most recent
2. Notification & **signal** when receiving a text.
3. More space for scrolling on the phone.

**Comment by Tobjaks** [comment]
+ Text's thats been sent to you while being offline are automatically set as "read" and doesn't give you a notification when you log in. 

This together with the sorting issues could put your most recent message at the bottom of your message list.

**Comment by JnKTechstuff** [comment]
Waiting for new phone
