### ISSUE TITLE
[BUG] Can't take shoes off

### ISSUE THREAD

**Issue by SpiceF0x** [xXJamieXx/paradox-bugs#184]
**Your Discord Name**
spicedf0x#2127

**Describe the bug**
When I use the command /s0 to take my shoes off, a different pair of shoes are put on. It's the same pair of shoes (currently 45) no matter which shoes I currently have on. /s1 does not put back on the shoes assigned to the outfit

**To Reproduce**
1. Have an outfit saved with the shoes of your choice
2. Try to take them off with /s0
3. Fail, and put on a different pair of ugly teal boots
4. Try to take these off by /s0 and you can't, or put your outfit shoes on with /s1 and you can't

**Expected behavior**
Take my shoes off and have bare feet when I do /s0 so I can see my toes.

**Screenshots**
These are the ugly shoes:
![The culprits](https://user-images.githubusercontent.com/96963965/151072460-6c17c016-6c43-4877-93d1-00e5b682908a.jpg)

Here's a nice video
https://streamable.com/g5lnvi

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
This was fixed. https://github.com/xXJamieXx/Paradox-3.0/commit/d097890dff33545f98e701dd17b9620cf5fd95bd
