### ISSUE TITLE
[BUG] Enter bug title

### ISSUE THREAD

**Issue by SaraLef** [xXJamieXx/paradox-bugs#185]
**Your Discord Name**
[Ssara#7821]

**Describe the bug**
[Still gets Dannyface and different haircolor. Makeup is green, eyebrows too.]

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[Expected to wake up like yesterday. Look like a Danny with green brows and blush. Can change face without issue, but not makeup or brows.]

**Screenshots**
(https://i.imgur.com/Gzmrjh7.jpg)

**Comment by xXJamieXx** [comment]
Duplicate of #117
