### ISSUE TITLE
[BUG] DJ booth menu not opening

### ISSUE THREAD

**Issue by Llieno** [xXJamieXx/paradox-bugs#187]
**Your Discord Name**
[Llieno#7518]

**Describe the bug**
[The DJ booth menu will not open when using "Third Eye" on it and right clicking.]

**To Reproduce**
[Steps to reproduce the bug]
1. Walk up to any DJ booth
2. Hold down [ALT] and look DJ booth location
3. Right click when EYE turns purple over DJ booth location

**Expected behavior**
[An option to open the DJ booth menu would open after selecting said, non existent, option after right clicking]

**Screenshots**
[If applicable, add screenshots to help explain your problem]
![image](https://user-images.githubusercontent.com/77819515/151265246-3ea9906b-a060-4f08-8eee-ed809b70f218.png)

**Logs**
[Add your FiveM logs]
[CitizenFX_log_2022-01-26T233158.log](https://github.com/xXJamieXx/paradox-bugs/files/7946378/CitizenFX_log_2022-01-26T233158.log)

**Comment by xXJamieXx** [comment]
There isn't a DJ booth there right now. Maybe in the future.

**Comment by Llieno** [comment]
@xXJamieXx I've also tried the one at the VU and it looked exactly the same.
