### ISSUE TITLE
Robberies 

### ISSUE THREAD

**Issue by Dragon115g** [xXJamieXx/paradox-bugs#189]
**Your Discord Name**
[Enter your Discord name] Dragon115g#0814

**Describe the bug**
[A clear and concise description of what the bug is] robberies(crashing)

**To Reproduce**
[Steps to reproduce the bug]
1. Get job
2. Drive to job depending on where its at (crashing because of 65000 Building pool)
3. getting in the house and crashing unexpectantly when entering 

**Expected behavior**
[A clear and concise description of what you expected to happen] get the job go to it without crashing or entering the house and crashing without knowing why  

**Screenshots**
[If applicable, add screenshots to help explain your problem]
never screenshotted them 

**Logs**
[Add your FiveM logs] don't know how 

it happened 3 times i turned off pc the first  time it happened then second time turned down setting then 3rd time reset and continued to happen

**Comment by JnKTechstuff** [comment]
Not valid
