### ISSUE TITLE
Amnunation has no guns

### ISSUE THREAD

**Issue by ithegreatgatsby** [xXJamieXx/paradox-bugs#19]
**Chris**
[Chris]

**Describe the bug**
[gun store has no guns. Nothing in f8 I do have a gun license and it validates.]

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment]
Fixed. https://github.com/xXJamieXx/Paradox-3.0/commit/a38469d5927e816c1f8c640dab4a68551f4c9ebc
