### ISSUE TITLE
[ENHANCEMENT] NOTEPADSSSSSSS

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#191]
**Your Discord Name**
OwlCherry#6969

**Describe the annoyance**
NOTEPAD BRING IT BACK PRETTY PLEASE. This is something GREAT for CID and those ill be interacting with. i have several items i think that would improve CID and the things im able to do (we can tlk bout later not publically)

**To Reproduce**
[Steps to reproduce the annoyance]
1. /notepad
2. no notepad
3. us = big sadddddddddddd

**Requested behavior**
notepad and drops as we had in 2.0

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by doppelshire** [comment]
/notepad opens notepad

If you make it an item that can be taken, I simply won't use it out of spite.

**Comment by doppelshire** [comment]
https://github.com/Dhruvpamnani/qb-notepad

https://github.com/NonexistentRP/qb-notepad
