### ISSUE TITLE
[BUG] $1000 impound fee

### ISSUE THREAD

**Issue by ArtyShwift** [xXJamieXx/paradox-bugs#193]
**Your Discord Name**
itsShaman#2451

**Describe the bug**
Impound Fee for $1000 for vehicle. However, vehicle does not have any strikes.

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
No charge to pull out vehicle from impound.

**Screenshots**

![IMG_1225](https://user-images.githubusercontent.com/97571985/151687026-d63fe4ab-f7e8-4ba5-bb46-a9302f53c071.jpg)

**Logs**
[Add your FiveM logs]

**Comment by jibbersh** [comment]
Happened to alanaelizabeth.lopez(lanaa94#5719) with a Canis Seminole, car was automatically impounded when placed in garage(did not notice until trying to remove the car at a later time so no logs provided for this), car cost $1000 at impound. Image below is the only error they noticed when pulling vehicle from impound.
![image](https://user-images.githubusercontent.com/96938099/152283618-b3f4f014-96c5-4736-af1d-52e71cf1a397.png)

**Comment by xXJamieXx** [comment]
This was fixed.
