### ISSUE TITLE
[BUG] buying new clothes at clothing store removes tattoos (can get back by selecting any outfit at apartment)

### ISSUE THREAD

**Issue by Person-AL767** [xXJamieXx/paradox-bugs#194]
**Your Discord Name**
Person__AL
**Describe the bug**
Every time you go to clothing store to buy clothes, the tattoos get removed from body and are not on character after leaving. You can get them back on by going to apartment and selecting an outfit, so this is low priority, but wanted to call out.

**To Reproduce**
[Steps to reproduce the bug]
1. Purchase any tattoos from tattoo parlor
2.  go to clothing store, initiate transaction
3. watch the tattoo fairies remove tattoos from skin.
4. (optional) go to apartment, change outfits to get tattoos back

**Expected behavior**
tattoos remaining at all times

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Could only reproduce this issue when hitting the "Discard" button in the clothing store so I've gone ahead and fixed that :) Live next restart.
