### ISSUE TITLE
[BUG] DJ Booths

### ISSUE THREAD

**Issue by BrotherDayZ** [xXJamieXx/paradox-bugs#196]
**Your Discord Name**
BDZ#0001

**Describe the bug**
Tried getting the DJ booths to work at the VU but there is nothing there to prompt for the menu to work. Basically there is nothing there anymore 

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Fixed whenever this gets merged. https://github.com/xXJamieXx/Paradox-3.0/commit/6de109e645ed3216e446f1c13e02f76d5902cbd6

**Comment by xXJamieXx** [comment]
This was fixed.
