### ISSUE TITLE
[BUG] Kanjo Impound Cost Raised?

### ISSUE THREAD

**Issue by dombpw** [xXJamieXx/paradox-bugs#197]
**Your Discord Name**
brulism#4567

**Describe the bug**
[A clear and concise description of what the bug is]
Yesterday I was awake in city for majority of the day. I had to take my Kanjo out of the impound atleast once or twice and never was it $1000. Now today I woke up for the first time, seen my car was impounded for whatever reason and upon arrival it is now telling me it is $1000 to return the vehicle.

**To Reproduce**
[Steps to reproduce the bug]
1. Buy Kanjo 
2. Impound Kanjo
3. Check release price

**Expected behavior**
[A clear and concise description of what you expected to happen]
Have a fixed release price unless other factors apply to raise the cost.

**Screenshots**
[If applicable, add screenshots to help explain your problem]
![image](https://user-images.githubusercontent.com/97014302/151721412-000e0897-9aec-4473-a43f-24dfe014840d.png)

**Logs**
[Add your FiveM logs]
Nothing in F8.

**Comment by dombpw** [comment]
This has yet to happen again.

**Comment by CorFinn** [comment]
Can confirm that issue doesn't seem to be a thing anymore. $0 for my Kanjo from the impound.

**Comment by dombpw** [comment]
Happened once again.

**Comment by xXJamieXx** [comment]
This was fixed.
