### ISSUE TITLE
[BUG] Chain No longer layering ontop of clothing

### ISSUE THREAD

**Issue by dombpw** [xXJamieXx/paradox-bugs#198]
**Your Discord Name**
brulism#4567

**Describe the bug**
Every since the clothing update a few days ago. The chain I have been wearing for months now no longer sits on top of any clothing. Before the chain had obvious issues with some clothing articles, but we were obviously able to work around that. Now it seems I am the only individual out of us all that is having this issue. I am unsure if it is an issue with my chest or what. Inside of cars, the chain shows more but still clips into my stomach a bit, this happens as well if I walk shirtless. The chain does not show through either jackets or undershirts.

**To Reproduce**
[Steps to reproduce the bug]
1. Be small
2. Lose muscle in chest
3. 

**Expected behavior**
Be able to wear my chain once again.

**Screenshots**
[If applicable, add screenshots to help explain your problem]
![image](https://user-images.githubusercontent.com/97014302/151721778-b6edcfc2-0962-4e5c-ab20-7ee4ef2d7fef.png)

![image](https://user-images.githubusercontent.com/97014302/151721792-e4cfd9de-ee61-42a6-8e8f-0cee46121ae0.png)

![image](https://user-images.githubusercontent.com/97014302/151721802-a97c83ec-cdfc-4de5-aafe-fc36297b7f8d.png)

![image](https://user-images.githubusercontent.com/97014302/151721845-41f5f2d5-cb64-4ca0-a1f5-03a7ab99e72a.png)

![image](https://user-images.githubusercontent.com/97014302/151721862-1472dae9-07f9-4a3a-9565-4f4f631b81d3.png)

**Logs**
[Add your FiveM logs]

**Comment by dombpw** [comment]
This is still an annoying issue I experience and am unsure if there is a solution.

**Comment by JnKTechstuff** [comment]
Do you ever change your arms?

**Comment by dombpw** [comment]
Yes, I have done everything within the city to try and resolve this issue.

**Comment by dombpw** [comment]
I got it figured out
