### ISSUE TITLE
[BUG] MDT Shift Info

### ISSUE THREAD

**Issue by 211Walker** [xXJamieXx/paradox-bugs#2]
tonytone883

**Describe the bug**
On the MDT as PD I am unable to delete or remove unwanted messages in the Shift Information 

![FiveM_b2372_GTAProcess_IzmPzPg8GG](https://user-images.githubusercontent.com/96933759/147844725-a3f18f52-826a-4f6b-8fb4-6038ab4bad08.png)

**Comment by JnKTechstuff** [comment]
Removed every restart now
