### ISSUE TITLE
[BUG] "put in vehicle" throwing people in the front passenger seat

### ISSUE THREAD

**Issue by LittletonSniper** [xXJamieXx/paradox-bugs#20]
LittletonSniper

**Describe the bug**
When you use "put in vehicle" via the radial menu it throws them in the front seat of the vehicle. For civs this may not be a big issue, but for cops it can be. As yes, your not able to get out of a car while in cuffs anymore, it's very weird to head to station with the suspect in the passenger seat. As well, if your riding duo, it forces your partner to have to sit in the back seat

**To Reproduce**
[Steps to reproduce the bug]
1. Recode it to put them in seat 3 or 4
2. 
3. 

**Expected behavior**
The script putting them in the back seat(s)

**Screenshots**
N/A

**Additional context**
:)

**Comment by JnKTechstuff** [comment]
This is an enhancement request but its already being done.
