### ISSUE TITLE
[BUG] Engine On + Refueling = BOOM

### ISSUE THREAD

**Issue by BrotherDayZ** [xXJamieXx/paradox-bugs#201]
**Your Discord Name**
BDZ#0001

**Describe the bug**
Pretty sure this bug is something that you guys are already aware of but I didnt see a bug report on it so I thought Id put one to see the status on fixing it.

**To Reproduce**
[Steps to reproduce the bug]
1. engine on
2. refuel
3. car goes boom

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
(https://i.imgur.com/bQlHSjI.png)

**Logs**
[Add your FiveM logs]

**Comment by JnKTechstuff** [comment]
Not a bug
