### ISSUE TITLE
[ENHANCEMENT] Blueprint drop rates seem very low

### ISSUE THREAD

**Issue by SterlingMoss** [xXJamieXx/paradox-bugs#202]
SterlingMoss#1596

The blueprint drop rates seem to be very low. Many of us will grind for hours, days, etc., not for money, but purely for blueprints and receive absolutely nothing. Personally, I was somehow able to pull a blueprint from mining on my first try a little over a week ago, but I've seen nothing since. I know a fair bit of people that haven't even seen one blueprint after days and days of basically nothing but grinding. It makes us wonder what's going on with them or if they're even working at all. We don't want to have to grind all the time, but at this rate if we want any blueprints, we're expecting a huge grind just to get even the most basic BP's.

**Requested behavior**
Increased BP drop rate, or something equivalent

**Comment by xXJamieXx** [comment]
It's just how probability works, the chances for it to drop when it is supposed to is equal for someone who did it 3 times a week as it is for someone doing it 30 times a day.

**Comment by SterlingMoss** [comment]
Okay, thanks for clearing that up! I appreciate it
