### ISSUE TITLE
when i try to see text on my phone i cant see any text

### ISSUE THREAD

**Issue by Dez505** [xXJamieXx/paradox-bugs#203]
**Your Discord Name**
[SuperD 505]

**Describe the bug**
[i can't see text on my phone and it says I have text here's a clip for it: https://medal.tv/games/gta-v/clips/9Q8olIY-B3bmG/d1337ic6dHAU?invite=cr-MSxqd20sMzQ3OTM3MTAs]

**To Reproduce**
[Steps to reproduce the bug]
1. get a text 
2. open the whatsapp app 
3. see no text

**Comment by JnKTechstuff** [comment]
Someone used an emoji, relogging will fix.
