### ISSUE TITLE
[BUG] Whitelist Removal being overwritten by Job Assignment at Town Hall

### ISSUE THREAD

**Issue by Person-AL767** [xXJamieXx/paradox-bugs#208]
**Your Discord Name**
Person__AL

**Describe the bug**
We've had to remove a few tow operators, and realize that even though the whitelist removal has been processed, the Town Hall Job being selected as "Tow" overrides the whitelist removal, allowing previously removed characters to still clock in and engage as a normal tow operator. Right now we are trying to tell people to go to townhall to switch to civilian, but for those we don't get through to, there's no telling what will happen.

**To Reproduce**
[Steps to reproduce the bug]
1. Have whitelist for a job, have the job selected at town hall
2.  remove whitelist via THE WHITELISTER (admin removal....)
3.  attempt to still go and engage with the whitelisted job and still be able to perform all functions

**Expected behavior**
We would expect the whitelist to override the person's selected role at town hall, so that the whitelist removal done via Discord is the only step in ensuring the fired/quitting individual does not have access to the whitelist roles.

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by Person-AL767** [comment]
Note- unclear if this is also w/ LEO / EMS

**Comment by xXJamieXx** [comment]
Only applies to tow. Other whitelisted jobs have the ability to fire employees therefore removing their job. The ideal solution is to give tow the boss menu to allow them to do this but that will come with time.

**Comment by xXJamieXx** [comment]
With the business update comes a boss menu for tow upper management. This will allow them to fire and manage the rankings of employees. This should resolve this issue. I'll close this but feel free to open a new bug report if it still happens after the update is released.
