### ISSUE TITLE
[BUG] Pocket 5 working as Pocket 6

### ISSUE THREAD

**Issue by PadawanPepsi** [xXJamieXx/paradox-bugs#21]
**Your Discord Name**
PadawanPepsi#6898

**Describe the bug**
5th pocket is working as if its the item slot 

**To Reproduce**
[Steps to reproduce the bug]
1. place any item in bottom right slot and then go out of pockets and press 5 that item in the bottom right will be used.
2. 
3. 

**Expected behavior**
normally that bottom right slot item is used when i press 6

**Screenshots**
https://i.imgur.com/tk31PBO.png

**Comment by JnKTechstuff** [comment]
Fixed https://github.com/xXJamieXx/Paradox-3.0/commit/bb6133c9b70919dead53d0b0dfabb0ef7459b6a6
