### ISSUE TITLE
[BUG] Seat Belts Don't Work

### ISSUE THREAD

**Issue by kingtortle** [xXJamieXx/paradox-bugs#210]
**Your Discord Name**
[Tortle#0499]

**Describe the bug**
The seat belts are always failing and will launch one or all people out of the car randomly. Very minor bumps to other vehicles will throw you out. I really hope this is not intended because it makes criminal activity almost impossible.
**To Reproduce**
[Steps to reproduce the bug]
1. Get in a vehicle 
2. Put on seatbelt and drive
3. Get launched randomly with crashes minor or otherwise

**Expected behavior**
[A clear and concise description of what you expected to happen]
To not get launched when your seatbelt is on

**Comment by xXJamieXx** [comment]
Can't reproduce this issue.
