### ISSUE TITLE
[BUG] Unable To Receive Weapons License

### ISSUE THREAD

**Issue by Nofsy** [xXJamieXx/paradox-bugs#211]
**Your Discord Name**
Nofsy#4764

**Describe the bug**
Officers are unable to give me a weapons license. I've tried with two different officers on separate days.

**Expected behavior**
This issue to be investigated and/or resolved so I'm able to receive a weapons license.

**Logs**
[CitizenFX_log_2022-02-06T210127.log](https://github.com/xXJamieXx/paradox-bugs/files/8011507/CitizenFX_log_2022-02-06T210127.log)

**Comment by xXJamieXx** [comment]
Believe this is no longer an issue.
