### ISSUE TITLE
[BUG] Phantom cars at garage sites

### ISSUE THREAD

**Issue by xecutionrStylz** [xXJamieXx/paradox-bugs#213]
**Your Discord Name**
xecutionrStylz#8035

**Describe the bug**
Ever since the change to garages happened, sometimes(up to maybe 50%) when people "put away" their car it will become invisible and will still have all collision effects causing people to damage their cars while trying to park. People can also climb on top of the vehicles and makes for an overall scuffed feel around garage sites. There seems to be a couple variations of this bug; sometimes when people put their car away it will disappear for them but not for others and those people can even lockpick the "stored" vehicle and make it reappear for that person when they enter the vehicle. The other variation i have come across is that some cars disappear entirely but the have all their collision making it where its like an invisible vehicle is sitting there. you can stand on them, hit them with cars and they even move as if they were hit with the car. When i county the vehicle, it is still counted as stored for the person and they can pull it back out without problem no matter which version is occurring. There is another phantom car event i had happen 1 time that i was able to get within one of the clips i have in which i was called to a scene to unlock a car for someone, i was unable to see the vehicle and for me there wasnt collision or anything to imply the car was even there including no third eye interaction. we were able to get the owner to be able to unlock the car finally and when the person entered the vehicle it was then made real on my side as well.

**To Reproduce**
1. Park car at garage site
2. "put away" car
3. have car either disappear but stay with full collision or have it disappear for you but not others

**Expected behavior**
When you put your car away it is fully removed from the city until pulled back out again

**Screenshots**

**Logs**
[Add your FiveM logs]

**Comment by xecutionrStylz** [comment]
[https://vimeo.com/675684227](url)

**Comment by xecutionrStylz** [comment]
[https://youtu.be/Cv02GFetRu0](url)

**Comment by Sly-Panda** [comment]
Does not appear to be happening anymore, not able to reproduce.
