### ISSUE TITLE
[BUG] Bikini Tow repairs don't effect Benny's repair costs

### ISSUE THREAD

**Issue by xecutionrStylz** [xXJamieXx/paradox-bugs#214]
**Your Discord Name**
xecutionrStylz#8035

**Describe the bug**
Whenever I repair a vehicle using the Tow Job command and the customer proceeds to go for body repairs from bennys, their cost is the same as if i had not done any repairs. I feel this may be negatively effecting peoples desire to call tow and instead abuse the impound system thats free to get a now drivable vehicle. I also went in city and tested this for myself and saw $0 change in cost from orange barely driving motor to green motor driving like new. I am 100% unsure if this is the same for repair kits but i am under the assumption that it is likely the same for those as well.

**To Reproduce**
1. Damage vehicle to point it no longer runs(or barely does), go to bennys and view cost of repair($194)
2. Use the tow job repair function
3. go to benny's and see it still costs $194

**Expected behavior**
If Bikini Tow repairs a vehicle, Benny's repair cost should be lower than before they performed the repair due to the engine no longer needing to be repaired. 

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
The Benny's repair cost is only affected by body damage and not engine damage, therefore regardless of whether a member of tow has repaired the engine or not, the price will be the same.
