### ISSUE TITLE
[BUG] Invisible cars for everyone not owning/driving vehicle

### ISSUE THREAD

**Issue by xecutionrStylz** [xXJamieXx/paradox-bugs#215]
**Your Discord Name**
xecutionrStylz#8035

**Describe the bug**
I have seen multiple people "falling through the ground" while travelling around the city and recently i have found out that these are people driving vehicles nobody else can see or interact with. The owner of the vehicle can see the vehicle and when the get into driver seat they begin to fall through the ground and it looks like "wizard" stuff is going on to everyone around. I have had 2 people test this and when they take a nap, the vehicle is gone for them, it goes to impound if i remember correctly. No further details have been able to be found by me due to the rarity of the bug. 

**To Reproduce**
1.talk to someone and watch them do animation like their getting in their car but no car is there 
2.watch the person repeatedly fall into the ground and back up while sitting position
3. have them get out and see no car or change in their appearance
4. have them nap and vehicle is no longer there for them either and is put in impound(or garage maybe)

**Expected behavior**
cars are able to be seen by all people or not by the owner if the vehicle is not intended to be there.

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by xecutionrStylz** [comment]
[https://youtu.be/K4qzPjdGVnU](url)

**Comment by JnKTechstuff** [comment]
Cross-networking issue that should be resolved
