### ISSUE TITLE
[BUG] 911 call coming in with different language 

### ISSUE THREAD

**Issue by monk3ythund3r** [xXJamieXx/paradox-bugs#216]
**Your Discord Name**
monk3ythund3r#5594

**Describe the bug**
I got a 911 call for a shots fired but when it gave me the location it gave the location in a completely different language

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
Having the 911 call location come in in English

**Screenshots**
(https://i.imgur.com/sCTYhQV.png)

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment]
This is a localization thing from the callers pc language settings.
