### ISSUE TITLE
[ENHANCEMENT] City Services

### ISSUE THREAD

**Issue by Tobjaks** [xXJamieXx/paradox-bugs#217]
**Your Discord Name**
tobjak#4191

**Describe the annoyance**
When there's no police on-duty and I clock on as EMS. It'll show on city services that both Ambulance and Police are available.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Make sure no police are on duty
2. Clock on as EMS
3. Check City Services

**Requested behavior**
Police should still be unavailable

**Screenshots**
https://imgur.com/ZdSOLXr)

**Comment by xXJamieXx** [comment]
Fixed in business update.
