### ISSUE TITLE
[ENHANCEMENT] Alta cars come out sideways

### ISSUE THREAD

**Issue by xecutionrStylz** [xXJamieXx/paradox-bugs#218]
**Your Discord Name**
xecutionrStylz#8035

**Describe the annoyance**
Ever since the Alta St. Apartments Garage has been moved to the middle area, the cars have come out sideways in relation to the direction of the parking spots. This in company with the phantom cars that plague the city make it difficult to get your car out especially without damage. It seems to me that the direction of vehicles was kept the same as the parking spots along the side wall and didnt get rotated to correspond with the new parking spots.

**To Reproduce**
1. go to the alta street garage
2. pull out car
3. see it come out sideways and possibly collide with a phantom car due to coming in on two or more parking spots.

**Requested behavior**
When pulling cars from that garage they would come out parallel to the parking spots not perpendicular

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
No longer applicable since Alta was moved.
