### ISSUE TITLE
[BUG] Bandage hurts

### ISSUE THREAD

**Issue by PadawanPepsi** [xXJamieXx/paradox-bugs#22]
**Your Discord Name**
PadawanPepsi#6898

**Describe the bug**
Bandaged hurting and ifaks do nothing possibly.

**To Reproduce**
[Steps to reproduce the bug]
1. i was hurt and used a bandage and lost health
2. 
3. 

**Expected behavior**
Loseing health when injuired 

**Additional context**
After using the bandage and got more damage i used an ifak and nothing happened

**Comment by xXJamieXx** [comment]
We believe this could be related to an issue with the HUD not updating when bleeding, this could explain the sudden change when using a bandage. See #17.

**Comment by JnKTechstuff** [comment]
This was in fact some weird issue with max health. I believe it has been resolved.
