### ISSUE TITLE
3rd eye not working at Sandy PD to get Cruiser out of garage

### ISSUE THREAD

**Issue by BigG5904** [xXJamieXx/paradox-bugs#220]
Your Discord Name
205-M. Foreman

Describe the bug
Can't get a police cruiser out of Sandy PD using 3rd eye. 3rd eye turns purple when looking at the garage attendant but the menu to for Open Motor pool, Store Vehicle, etc. does not open up.

[Steps to reproduce the bug]
1. Go into Sandy PD garage and try to remove a police cruiser.
2.
3.

Expected behavior
When looking at the garage attendant at Sandy PD using 3rd eye, you should be able to get the popup menu to get out a police cruiser, store vehicle, etc.

Screenshots
https://i.imgur.com/MJ7G30a.jpeg

**Comment by Deadles** [comment]
To add on this bug report that is related to the recent update with Public Safety.

The Clock in/out book at MRPD shows the option to go on or off duty but does not do anything when the action is performed.

LSPD can take the job from Sandy or Davis but they can't clock off,  Works fine for BCSO.  Not sure about the other departments for PD.

EMS is unable to clock in period,  EMS is getting the "you are not authorized!" 

That is all the reports I have came across so far.

**Comment by Person-AL767** [comment]
"not authorized" happening for all of tow as well

**Comment by BigG5904** [comment]
Third eye is also not working at the fuel pumps to fuel cars either and also can't use the jerry can't fuel up police cruiser. I can fuel up the jerry can, but I can't fuel the police cruiser up straight from the pump.

https://i.imgur.com/M0t3vJh.jpeg
https://i.imgur.com/M0t3vJh.jpeg
