### ISSUE TITLE
(BUG) Unable to Check Out Ambulances

### ISSUE THREAD

**Issue by Nicklmfao** [xXJamieXx/paradox-bugs#222]
Your Discord Name
Nicklol#2510

Describe the bug
Whenever myself or others clocks in for EMS, we get all of our ambulances from the man in the corner of the garage. Earlier as well as last night, I would try to grab a ambulance like normal, no changes and attempted to use my third eye to check out the vehicle. Whenever I go to do so, the third eye menu does not pop up what so ever, just the cursor. This happened to a fellow EMT as well and we had no fix to try and get it to work. We tried other third eye-able things and it worked on those.(Snack machines, water dispensors, etc.)

To Reproduce
[Steps to reproduce the bug]

1. Clock in for EMS
2. Go downstairs to the garage
3. Use your third eye on Charles to check out a ambulance
4. The menu does not show at all, regardless of normal attempted fixes.

Expected behavior
I expected to check out the car with no issues, if the third eye menu would load up I would be able to check out my ambulance and go throughout my shift with little to no issues.

Screenshots
https://i.imgur.com/S5TixK0.jpeg

Logs
https://i.imgur.com/9k7woms.jpeg

**Comment by Strandis** [comment]
Does work to pull out the ambulance when job is set to Assistant Chief at Pillbox, Sandy and Paleto.

**Comment by xXJamieXx** [comment]
This was fixed.
