### ISSUE TITLE
[BUG] Third eye not working, fix didn't work

### ISSUE THREAD

**Issue by SterlingMoss** [xXJamieXx/paradox-bugs#223]
SterlingMoss#1596

The server was reset to fix the third eye, but its broken for most of us now. It was working fine for me before, but it seems like its broken for more people than it was before the fix. Just wanted to report it in case staff thinks the fix worked

**Comment by BigG5904** [comment]
I'm still having issues with my Third eye as well. I'm still not able to put fuel into my vehicles at the pump or with a jerry can

**Comment by Person-AL767** [comment]
Was able to use third eye on Butch (tow operator) but not on Chester (civilian).

**Comment by CorFinn** [comment]
It's the same from my end. This character has no whitelisted jobs (in case that is part of it). Vehicle is a Brioso. A different citizen was able to fill my car, however he had to search around the car for a spot that allowed him to refuel. He eventually found a spot to fuel, near the right rear taillight. ( I was unable to fuel from the same location he did) After he entered the driver's seat and exited, car was refueled.

**Comment by CorFinn** [comment]
Also, it seems distance plays a factor somehow. While close to my vehicle, no third eye. While at the edge of its range, I get the vehicle menu (but not the fuel menu)

https://i.imgur.com/2jNlbeP.jpeg
https://i.imgur.com/ZZTsRqR.jpeg

**Comment by xXJamieXx** [comment]
This was fixed.
