### ISSUE TITLE
[BUG] Enter bug title

### ISSUE THREAD

**Issue by BigG5904** [xXJamieXx/paradox-bugs#227]
Your Discord Name
205-M. Foreman

Describe the bug
Can't put fuel into cruiser at all. Fuel menu will not come up.
[Steps to reproduce the bug]

Go into Sandy PD garage and try to remove a police cruiser.
Expected behavior
Should be able to use third eye to put fuel in vehicle. Jerry can and fuel pumps dont' work

Screenshots
https://i.imgur.com/MJ7G30a.jpeg
https://clips.twitch.tv/NeighborlySmellyCakeBudStar-WhI70uZ-AnulcKiJ[](https://github.com/BigG5904)

**Comment by xXJamieXx** [comment]
This was fixed.
