### ISSUE TITLE
[BUG] Twitter Pic doesn't disappear

### ISSUE THREAD

**Issue by SpiceF0x** [xXJamieXx/paradox-bugs#23]
**Your Discord Name**
spicedf0x#2127

**Describe the bug**
If you click on a picture on Twitter it pops up on your screen and you have to relog to get rid of it.

**To Reproduce**
1. Open phone and navigate to Twitter
2. Find a tweet with a pic attached
3. Click on the pic to enlarge

**Expected behavior**
Pic to disappear when you click off?

**Screenshots**
![20220102015135_1](https://user-images.githubusercontent.com/96963965/147864028-ed3326c6-06e6-400d-adfe-939ec287f5ca.jpg)

**Additional context**
F8 showing error - shown in screenshot

**Comment by xXJamieXx** [comment]
Only happens if someone adds a picture with `http` at the start of the link instead of `https`.
