### ISSUE TITLE
Reliable network event size overflow

### ISSUE THREAD

**Issue by northernb0y** [xXJamieXx/paradox-bugs#230]
**Your Discord Name**
[Enter your Discord name]
Northern | C Dawwg
**Describe the bug**
[A clear and concise description of what the bug is]
I keep crashing with this: Reliable network event size overflow: a1d21cd1-8c1d-4a25-b1a1-f72c2f027605
**To Reproduce**
[Steps to reproduce the bug]
1. Fly in to city
2. Do anything
3. Crash

**Screenshots**
[If applicable, add screenshots to help explain your problem]
![Desktop Screenshot 2022 02 19 - 17 00 31 03](https://user-images.githubusercontent.com/97005803/154824322-1225b8a0-b426-43e7-92ab-c31f1aca5b7f.png)
![Desktop Screenshot 2022 02 19 - 17 40 41 61](https://user-images.githubusercontent.com/97005803/154824326-c883c338-6af0-4593-bcf9-b1d3c2ddf79f.png)
https://drive.google.com/file/d/1OTrpAkYVcLl0D3aN1dxxjzWDjDMf_rQV/view?usp=sharing 
**Logs**
[Add your FiveM logs]

**Comment by northernb0y** [comment]
Let me know if I can help in anyway.

**Comment by xXJamieXx** [comment]
Tackled the events that seem to be spamming in your video so hopefully should fix this issue. If it continues please open a new report with a new video. Thanks.
