### ISSUE TITLE
[BUG] PD Door locks

### ISSUE THREAD

**Issue by JaxCreed** [xXJamieXx/paradox-bugs#232]
**Your Discord Name**
[Spicy#5426]

**Describe the bug**
[Characters that are not apart of PD can unlock doors at police stations, I have Richard Harder and on Jax Creed i am able to unlock the doors/cells ]

**To Reproduce**
[Steps to reproduce the bug]
1. be on a character that is not a cop
2. Hit E
3. Door will unlock

**Expected behavior**
[Not to be able to unlock doors on other characters, its possible it could be abused ]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Fixed in business update.
