### ISSUE TITLE
[BUG] Bike impounded at random

### ISSUE THREAD

**Issue by VincentVangoatt** [xXJamieXx/paradox-bugs#233]
**Your Discord Name**
Vangoat#9993

**Describe the bug**
For the last few days, my bikes randomly get impounded, I believe related to distance. If I do a trash run, or even visit the off road dealership, I will come back to nothing, the bike is impounded. Scorcher and BMX both have this issue. I only noticed this so far with the offroad dealer, but have only visited that and the low end in recent times. I have not had this issue with my car, a Winky. I got a good distance away and it remained last night.

**To Reproduce**
[Steps to reproduce the bug]
1. Get Scorcher/BMX
2. Do a few stops of the Garbage job/enter the offroad dealership and come back to where you left your bike
3. Bike gone, and in the impound.

**Expected behavior**
[A clear and concise description of what you expected to happen]
For my bikes to not be impounded by simply traveling a great distance as I imagine is what is happening. My car stays no matter how far away I go, as long as I don't fly out. Bikes used to work like that, as I would do trash runs that lasted for quite some time and came back to my bike waiting for me.
**Screenshots**
[If applicable, add screenshots to help explain your problem]
N/A
**Logs**
[Add your FiveM logs]
I can get them if really needed but I am unsure if it was even logged.

**Comment by VincentVangoatt** [comment]
It seems to be cleared up now, I did a long trash run and checked a dealership, bike remained both times.

**Comment by xXJamieXx** [comment]
This is just standard GTA cleanup. Vehicles will get deleted in this fashion usually if nobody is nearby.
