### ISSUE TITLE
[BUG] Third-eye EMS

### ISSUE THREAD

**Issue by Tobjaks** [xXJamieXx/paradox-bugs#234]
**Your Discord Name**
tobjak#4191

**Describe the bug**
Yesterday we had someone at the hospital unable to use their third-eye on things. Today I have one more in the team that can't use their EMS abilities. (Print screen is from that person) I also was unable to third-eye my ambulance earlier. 

I am not sure on how to reproduce this. It seems to be working fine for people and then all of a sudden it stops and the interaction menu does not show up. 

**Screenshots** **Logs**
![IMG_5215](https://user-images.githubusercontent.com/97873782/154995991-84221757-db8a-43c7-aaee-5f4f190f25f2.jpg)

**Comment by xXJamieXx** [comment]
This was fixed.
