### ISSUE TITLE
[BUG] EMS third eye

### ISSUE THREAD

**Issue by SaraLef** [xXJamieXx/paradox-bugs#236]
**Your Discord Name**
[Ssara#7821]

**Describe the bug**
[I can't use EMS-interactions when I'm on duty, at all. Everything else works fine with the third eye.]

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[Excpected to be able to be on duty and help people without bigger issues.]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by Person-AL767** [comment]
I was able to have all my EMS actions last night, but I could NOT put downed individuals in the back of an ambulance- didn't have the option to. I did have the option to pull from the seat menu, but there was no option to put players in the vehicle.

Also, every time I was flexing my third eye while escorting, it was dropping the escorted player, not sure if that has to do with the issue.

**Comment by JnKTechstuff** [comment]
Please do not skip parts of the Bug Report because you do not want to. As a subsequent of the skipping of the provided template we are missing all key information needed to actually fix this issue.

**Comment by SaraLef** [comment]
Sorry for skipping but English is not my first language so I don't understand exactly what to do.
I know 2 colleagues of mine had the same issue with not being able to use ems interactions, but after clocking in and out a couple of times it worked for them again. I'll see what happens when I go on duty today as well.

Hämta Outlook för Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by xXJamieXx** [comment]
This was fixed.
