### ISSUE TITLE
[BUG] Female BurgerShot Jersey

### ISSUE THREAD

**Issue by MikanGabi** [xXJamieXx/paradox-bugs#237]
**Your Discord Name**
MikanGabi#1865

**Describe the bug**
None of the arms work together with the Female Burgershot Jersey, there is always a part that is invisable or skin is showing through.

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
![3e7b9d2754deb71ea7cc9e8923720c1e](https://user-images.githubusercontent.com/100172357/155041952-f7c213b3-72ca-43ec-9e6b-e82317727e31.jpg)
![10ee07981d417f0573b6d4153e8f57e8](https://user-images.githubusercontent.com/100172357/155041959-d291106e-cfef-40f5-8f04-dd49fb1def3f.jpg)

**Logs**
[Add your FiveM logs]

**Comment by JnKTechstuff** [comment]
This is a R* bug not us unfortunately, could also just be your neck type. Either way its not possible to fix on our end.
