### ISSUE TITLE
[BUG] State Police Third Eye

### ISSUE THREAD

**Issue by JaxCreed** [xXJamieXx/paradox-bugs#238]
**Your Discord Name**
[Spicy#5426]

**Describe the bug**
[So im apart of the state police and yesterday i was not able to look at anyone with my third eye. nothing would show up just the eye would go purple and thats it. Now today i have signed off duty refreshed perms and gone back on duty, Today i can use my third eye but its only normal basic functions like Escort and put in vehicle, but no police actions. Apparently some departments have their perms that work and others dont. /Job states im on duty and police]

**To Reproduce**
[Steps to reproduce the bug]
1. try to use third eye
2. Has normal functions 
3. But no police menu

**Expected behavior**
[to be able to arrest crims man]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[No failed scripts ]

**Comment by xXJamieXx** [comment]
This was fixed.
