### ISSUE TITLE
[ENHANCEMENT] Limit /911e calls with a 5 minute cooldown

### ISSUE THREAD

**Issue by Person-AL767** [xXJamieXx/paradox-bugs#239]
**Your Discord Name**
Person__AL

**Describe the annoyance**
When people are downed, there have been times where people have become impatient with EMS (~some instances, not even 10 min), and decide "maybe if I put in 15-20 calls at once, they will help me". Then all the sudden they will do /911e; /911e; /911e; /911e; /911e; /911e; /911e;  over and over and over again, effectively breaking all EMS's dispatching system by not being able to see all the calls (or it slows it down tremendously, especially on low performance PCs). This is breaking other people's scenes/story archs by not allowing us to be able to get to others EMS calls.

This, on top of people shitting on EMS lately, has been quite deflating and causes EMS to not even want to sign on.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Delayed calls past 5+ min
2. Wait for someone to do /911e; /911e; /911e; /911e; /911e; /911e; /911e; /911e; /911e; 
3. Notice that dispatching is now very hard to read, engage, etc.

**Requested behavior**
/911e has a 5 min cool down, effectively only allowing players put in calls every 5 min (plus the initial "HOLD E" EMS call). This limits spamming for EMS, while still giving the player opportunity to re-call EMS if needed/delayed (without destroying our dispatching system)

**Screenshots**
I will get another screenshot/video of when it happens, it's ridiculous. Last time it happened, we reported it to Staff, but it's hard sometimes to get that info.

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
Added in business update.
