### ISSUE TITLE
MDT Known convictions not showing on player profile

### ISSUE THREAD

**Issue by PadawanPepsi** [xXJamieXx/paradox-bugs#24]
**Your Discord Name**
PadawanPepsi#6898

**Describe the bug**
All known Convictions not showing on players profile 

**To Reproduce**
[Steps to reproduce the bug]
1. Unkown
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]
For some reason all of someones charges are not showing on their profile. Not sure if this is everyone or just a few

https://i.imgur.com/p5XMGqU.png

https://i.imgur.com/V3BKykp.png

**Additional context**
[Add any other context about the problem here]

**Comment by JnKTechstuff** [comment]
Closing, if still occurs make a new one
