### ISSUE TITLE
when doing a EMS training my trainee cant get there Job

### ISSUE THREAD

**Issue by Dez505** [xXJamieXx/paradox-bugs#240]
**Your Discord Name**
[SuperD 505#1060]

**Describe the bug**
[when doing an EMS training my trainee cant get their Job to do FTOs or in city part of the training]

**To Reproduce**
[Steps to reproduce the bug]
1. get the EMT role in public safety discord
2. try clocking in at pillbox
3. says "unauthorized for this job"

**Expected behavior**
[cant clock on duty for a new whitelisted job]

**Comment by xXJamieXx** [comment]
Cannot reproduce.
