### ISSUE TITLE
[BUG] PMMS - Video links flicker continuously on TVs

### ISSUE THREAD

**Issue by CorFinn** [xXJamieXx/paradox-bugs#241]
**Your Discord Name**
GrandNagus#9705
**Describe the bug**
When attempting to play a video on a TV with PMMS, the audio plays correctly, but any video will flicker and display approximately 1-2 frames then a black screen, repeatedly.

**To Reproduce**
[Steps to reproduce the bug]
1. Be near a PMMS enabled asset.
2. open PMMS
3. Set source asset to TV, paste YouTube link in address bar, and hit PLAY.

**Expected behavior**
The video, while not expecting 4k 60fps, should play a little smoother, and without blackout flickering.

**Screenshots**
None necessary. This is easily repeatable.

**Logs**
No F8 Errors I saw.

**Comment by frojei** [comment]
https://user-images.githubusercontent.com/96413401/155899399-47c40f33-393e-42de-870d-1c57c9b94851.mp4

**Comment by Sly-Panda** [comment]
Fixed in business update.
