### ISSUE TITLE
[BUG] Enter bug title

### ISSUE THREAD

**Issue by iHardzyy** [xXJamieXx/paradox-bugs#242]
**Your Discord Name**
iHardzyy#8079
Im unable to use the cop things in third eye like cuffing searching ect clocking in and out didnt work and flying in doesnt either

**To Reproduce**
[Steps to reproduce the bug]

1.  sign in 
2.  clock in
3. third eye someone

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
This was fixed.
