### ISSUE TITLE
[BUG] Payment system is down.

### ISSUE THREAD

**Issue by KindredShadow** [xXJamieXx/paradox-bugs#244]
**Your Discord Name**
Kindred_Shadow#2948

**Describe the bug**
We aren't receiving a paycheck while on duty and off duty as EMS. When I went on duty last night around 8-8:30 pm est I had around $9700 and when I went off duty around midnight I still had the same amount. This isn't just an issue that I have been having. I have reports from sherbert#3139 and Ssara#7821 that were also on duty with me that they didn't receive a paycheck. I am hearing that all of public safety hasn't been able to receive a paycheck.

**To Reproduce**
[Steps to reproduce the bug]
I tried to see if flying in and out as well as clocking in and out would fix it and nothing changed.

**Expected behavior**
Payment every 20 mins.

**Screenshots**
I don't have any screenshots.

**Logs**
I don't have any logs.

**Comment by Person-AL767** [comment]
For the sake of sharing information, Tow whitelisting has not been effected by this paycheck bug.

**Comment by Sly-Panda** [comment]
Fixed
