### ISSUE TITLE
[BUG] Guns randomly degrading

### ISSUE THREAD

**Issue by SterlingMoss** [xXJamieXx/paradox-bugs#245]
SterlingMoss#1596

I'm really surprised nobody has reported this yet, but everyone's weapons are randomly degrading in their pockets/stash. I have around 5-6 sig sauers and a glock, and when i flew out last night they were all nearly broken. They have never been used. This is a big issue going on right now, if you have guns stashed away you could be out thousands of dollars.

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]
![2022-02-22 (32)](https://user-images.githubusercontent.com/97280265/155427991-874ee967-9360-4521-a0ec-05b0e012e1ae.png)

**Comment by JnKTechstuff** [comment]
Not a big, guns rust

**Comment by SterlingMoss** [comment]
over the course of a day? I literally had guns full health and by the time i flew in today they were destroyed

**Comment by JnKTechstuff** [comment]
Yes guns rust

**Comment by SterlingMoss** [comment]
damn :( no more guns I guess
