### ISSUE TITLE
[BUG] No PD Third Eye Menu

### ISSUE THREAD

**Issue by SaintSeven31** [xXJamieXx/paradox-bugs#246]
**Your Discord Name**
[Seven#3131]

**Describe the bug**
[I'm an LSPD officer and while on duty am unable to use the police menu under my third eye.  I see all the normal options, just no police menu. I tried flying in and out, clocking in and out, and attempted to refresh perms.  Nothing worked and I went off duty.]

**To Reproduce**
[Steps to reproduce the bug]
1. Go on duty as LSPD at MRPD
2. Use third eye
3. Don't see police options

**Expected behavior**
[I expect to be able to see, open up, and use my third eye police menu]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[N/A]

**Comment by xXJamieXx** [comment]
This was fixed.
