### ISSUE TITLE
[BUG] Locals have forgotten how to lock their cars

### ISSUE THREAD

**Issue by xecutionrStylz** [xXJamieXx/paradox-bugs#247]
**Your Discord Name**
xecutionrStylz#8035

**Describe the bug**
Local cars no longer have locked door and you can take any car you want anytime you want.

**To Reproduce**
1. Walk up to car and press "F"
2. Smash window and open car to get in
3. Start car and drive away with a sick new ride

**Expected behavior**
Local cars have locked door and require a lockpick to enter them

**Screenshots**

![20220223204246_1](https://user-images.githubusercontent.com/97769962/155447583-7959f3e7-81e8-43ca-ab55-a5bd4ba6428b.jpg)

**Logs**
![20220223204300_1](https://user-images.githubusercontent.com/97769962/155447557-714a28d5-8350-4818-bfd3-867ca806c72d.jpg)

**Comment by xXJamieXx** [comment]
Fixed in business update.
