### ISSUE TITLE
[BUG] Holsters broken

### ISSUE THREAD

**Issue by pulsevr34** [xXJamieXx/paradox-bugs#248]
**Your Discord Name**
Pulse+#5769

**Describe the bug**
PD holsters now don't work. When on duty PD, I pull my baton, tazer, and gun out of my back waistband instead of my holster, and adds an extra couple of seconds to the pullout animation.

**To Reproduce**
[Steps to reproduce the bug]
1. Get PD gun
2. Pull it out
3. Profit

**Expected behavior**
I should be able to pull my gun out of my holster quickly instead of pulling it out of my waistband.

**Screenshots**
https://i.imgur.com/UdIe5tf.jpeg
**Logs**
[[Add your FiveM logs]](https://i.imgur.com/ddqPS3u.png)

**Comment by Drunkle716** [comment]
Can confirm. Been an issue for at least 2 days

**Comment by xXJamieXx** [comment]
Fixed in business update.
