### ISSUE TITLE
3rd EYE locks curser 

### ISSUE THREAD

**Issue by Babbach** [xXJamieXx/paradox-bugs#252]
Babbach#8922
[Enter your Discord name]

**Describe the bug**
When I hold L ALT to use 3rd eye the cursor does not move. As soon as the menu appears my cursor locks on the purple eye and cannot be moved to select an option from the menu.

**To Reproduce**
[Steps to reproduce the bug]
1. Hold L ALT
2. Attempt to move cursor
3. be disappointed 

**Expected behavior**
I expected to be able to move my cursor and choose options from the 3rd eye interaction menu. 

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
@Babbach Please try the following and let me know if it works:

> Go into game settings and then keyboard and mouse and then change the mouse input method to raw

**Comment by Babbach** [comment]
Thank you so much!!!!
