### ISSUE TITLE
can hear maze bank arena at pill box

### ISSUE THREAD

**Issue by Dez505** [xXJamieXx/paradox-bugs#253]
**Your Discord Name**
SuperD 505#1060

**Describe the bug**
when you go the stadium, you can hear the stadium noises - crowd and horn going off for quite some time even when "miles" away from the stadium. After being at the stadium we could hear the cheering all the way to pillbox and then it stops randomly when you get far enough.

**To Reproduce**
[Steps to reproduce the bug]
1. go to maze bank arena
2. drive away 
3. hear the sounds miles away

video: https://www.twitch.tv/videos/1409487686?t=04h50m04s Sound can be heard from around 4:50:00 to about 5:40:00

**Comment by xXJamieXx** [comment]
Fixed
