### ISSUE TITLE
[ENHANCEMENT] Undressing issues

### ISSUE THREAD

**Issue by pulsevr34** [xXJamieXx/paradox-bugs#254]
**Your Discord Name**
Pulse+#5769

**Describe the annoyance**
1. When taking off a shirt and putting it back on, your arms clip through the shirt.
2. When you take off your pants, instead of showing underwear, it shows a pair of white dress pants, for males at least.

**To Reproduce**
[Steps to reproduce the annoyance]
1. /p0 to take off pants, shows white pants (preferably the black boxers with red hearts from 2.0)

1. /j0 to take off shirt
3. /j1 to put back on shirt, arms clip through

**Requested behavior**
When taking off your pants, it should show underwear instead of pants, and when putting a shirt back on, my arms shouldn't clip through.

**Screenshots**

https://user-images.githubusercontent.com/97071437/156027785-32fdc6a7-a3e3-4700-be0c-e9470238bccc.mp4

**Additional context**
[Add any other context about the enhancement here]

**Comment by Sly-Panda** [comment]
Fixed in the business update
