### ISSUE TITLE
[BUG] Vests dont carry over on restart or relog

### ISSUE THREAD

**Issue by pulsevr34** [xXJamieXx/paradox-bugs#255]
**Your Discord Name**
Pulse+#5769

**Describe the bug**
When you put on a vest, it doesn't save once you fly out or after tsunami, so it's essentially pointless to be spending hundreds of dollars on a new vest every time you relog or the server restarts. This also happens when you headpop,  your armor goes away.

**To Reproduce**
[Steps to reproduce the bug]
1. Put on vest
2. relog, server restart, get downed, etc.
3. No more vest, money wasted.

**Expected behavior**
My vest should work after relogging, for the insane price we have to pay each time for a new one, they should at least last after a  relog or restart. The perfect way to go about this is to have them last until they break.

**Screenshots**
No screenshots needed

**Logs**
No errors

**Comment by xXJamieXx** [comment]
Fixed in business update.
