### ISSUE TITLE
I sstill cannot Retrieve my boat after fix.

### ISSUE THREAD

**Issue by Iwear0000FF** [xXJamieXx/paradox-bugs#256]
Your Discord Name
Play3r0000FF#9352

Describe the bug
[I bought a dingy to dive with a friend and let him drive. when we stopped at the docks in paleto he for some unkown reason decided to put my boat in his garage. it then vanished. I then found it down at the middle lsmc dock but cant take it out of the garage at all. I have tried flying out and it doesnt help.]

To Reproduce
[Steps to reproduce the bug]

Buy a new boat.
Have some one else dock your new boat you've never docked
try to take it out of middle lsmc garage
Expected behavior
[I expected it would be able to be clicked on in the depot and it would spawn.]

I still cannot retrieve my Boat. but now it does say my boat isnt in that boat house. ive checked all others and this is the only one it even shows up in tho.

https://user-images.githubusercontent.com/100473322/156275298-a3ba264b-8485-453c-b207-3163554df87d.mp4

![FiveM_b2545_GTAProcess_ICis353z3w](https://user-images.githubusercontent.com/100473322/156275482-105cdd91-9ab4-4a3e-a059-f37a5d9d3e0c.jpg)

**Comment by xXJamieXx** [comment]
Fixed in business update.
