### ISSUE TITLE
[BUG] Police/EMS Actions still broken

### ISSUE THREAD

**Issue by pulsevr34** [xXJamieXx/paradox-bugs#258]
**Your Discord Name**
Pulse+#5769

**Describe the bug**
My third eye is still broken sometimes when I fly in, sometimes police actions will be broken, and sometimes the third eye just wont show anything, including civ actions. I looked at the f8 menu and it didnt give me any errors, just police actions seem to be disappearing occasionally, the only fix is to clock off, fly out, clear your cache, and fly back in, then clock in again. This problem is happening to all of PD and some EMS, not just me.

**To Reproduce**
[Steps to reproduce the bug]
1. Fly in
2. Clock on duty
3. Third eye broken

**Expected behavior**
My third eye should be able to show up and let me cuff, fine jail, etc.

**Screenshots**
https://i.imgur.com/mC5hOhY.jpeg
Happens while on duty LEO, should show "police actions" at the top

**Logs**
No error logs shown

**Comment by xXJamieXx** [comment]
This was fixed.
