### ISSUE TITLE
[BUG] Not able to bring car out from parking Alta Street apartments

### ISSUE THREAD

**Issue by s0ur3n** [xXJamieXx/paradox-bugs#26]
souren #4664

I had just bought a car from the low end shop and parked it at the Alta Street Apartments and wasn't able to get it back out, even after taking a nap, tried in multiple different parking spots. 

[Steps to reproduce the bug]
1. Buy Brioso from low end shop
2. Drive to Alta apartments 
3. Park car
4. Go up to apartment
5. Leave apartment
6. try to take car out of garage 

Expected car to leave garage and appear in parking spot

https://user-images.githubusercontent.com/96967755/147866759-a75b6a86-2325-45ec-902a-b529c89d8c18.mp4

**Comment by xXJamieXx** [comment]
@s0ur3n Please send a screenshot of your F8 with any potential errors after attempting to retrieve the vehicle

**Comment by s0ur3n** [comment]
Hi Jamie i was on Paradox for many hours today dont know if it was resolved
but have not had that issue since. The other issue i was having was to do
with impound, to do with not being placed in your car when requesting it to
be removed fron impound and i submitted a bug report for that too. If the
parking garage bug happens again i'll send over the screenshot of the F8.

Thanks

**Comment by xXJamieXx** [comment]
Ok no problem. I'm going to close this issue and you can open a new one if the issue happens again. Thanks.
