### ISSUE TITLE
[BUG] Duplicate Blueprints

### ISSUE THREAD

**Issue by BBstud44** [xXJamieXx/paradox-bugs#261]
**BBstud27**
[Enter your Discord name]

**While smelting to get blueprints the last 3 blueprints ive gotten have been toolkits and you can only use 1 so the extras are just sitting there collecting dust**
[A clear and concise description of what the bug is]

**To Reproduce**
[Steps to reproduce the bug]
1. Smelt everything you have
2. get a blueprint
3. Be sad because you got the same blueprint again :(

**I expected to get a different blueprint each time**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by JnKTechstuff** [comment]
Not a bug
