### ISSUE TITLE
[BUG] Clocking in and out is required for some whitelisted jobs before doors become unlockable/lockable

### ISSUE THREAD

**Issue by Person-AL767** [xXJamieXx/paradox-bugs#264]
**Your Discord Name**
Person__AL
**Describe the bug**
Some Tow operators tonight were unable to open doors to get into shop. When I opened doors to let them in,  then they flicked their job duty off/on, they were then able unlock doors- both off and on duty thereafter.

Same happened for my EMS character at pillbox- not as bad but I had to hop over counter to sign off/on before i was able to unlock/lock doors around the hospital.

Will likely prevent some operators from going on duty if no one around. Unclear about LEO impact. EMS should have a workaround.

**To Reproduce**
[Steps to reproduce the bug]
1. Sign into whitelisted character
2. attempt to unlock typical whitelisted doors for the role
3. If it doesn't work, find a way to clock on/off.
4. Go back and unlock doors to confirm it works.

**Expected behavior**
Being able to unlock/lock typical doors associated w/ the roles.

**Comment by Tobjaks** [comment]
This happened to me aswell today. After I went back on duty, and then signed off it worked like normal.

**Comment by Sly-Panda** [comment]
This may just be from the recent update needing the jobs to be clocked on again for the first time.

**Comment by xXJamieXx** [comment]
Simply just caused by a change to the system and having to clock on once since the update in order to save your job.
