### ISSUE TITLE
[BUG] You can clip through wall at 3025

### ISSUE THREAD

**Issue by Vsolon** [xXJamieXx/paradox-bugs#266]
**Your Discord Name**
Vsolon#1699

**Describe the bug**
You can clip through the wall at postal 3025 to the right of the atm 

**To Reproduce**
[Steps to reproduce the bug]
Go to 3025 and walk into the wall to the right of the atm on the side of the building. 

**Expected behavior**
You will walk right through 

**Screenshots**
![image](https://user-images.githubusercontent.com/13530791/157073674-cd103e95-f9eb-4a2a-86a6-b34d2b2029a5.png)
![image](https://user-images.githubusercontent.com/13530791/157073599-4d90c57c-c206-4ec3-94a4-a159d81d145b.png)

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Fixed next restart.
