### ISSUE TITLE
Farming Money glitch

### ISSUE THREAD

**Issue by ItsFoux** [xXJamieXx/paradox-bugs#267]
**Your Discord Name**
Foux#1236

**Describe the bug**
after the most recent tsunami, i am able to harvest a plant and then it reappears and i can do it all over again

**To Reproduce**
[Steps to reproduce the bug]
1. harvest plant
2. wait for it to pop back up
3. harvest again, profit

**Expected behavior**
have plant dissapear

**Screenshots**

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Should be fixed.
