### ISSUE TITLE
[BUG] Dinghy missing from boathouse

### ISSUE THREAD

**Issue by TurboDummi** [xXJamieXx/paradox-bugs#269]
**Your Discord Name**
[cybercucked 2077 / turbo dummi]

**Describe the bug**
[prior to the business update dinghy was stored in the dock that was near the boat shop, since I noticed the dock was removed with the business update I checked all other docks just to see that my boat wasn't at any of them]

**To Reproduce**
[Steps to reproduce the bug]
1. Parked boat in docks prior to business update
2. Dock was removed forcing me to check all other docks for boat
3. Boat isn't in any of the docks

**Expected behavior**
[I expected my boat to just have been moved to another dockyard]

**Screenshots**
[None]

**Logs**
[None]

**Comment by xXJamieXx** [comment]
Your dinghy should now be where your other one is.
