### ISSUE TITLE
[ENHANCEMENT] Garages at work sites

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#270]
Now with the new system of recieving paychecks from the bank, I do believe that we do have an argument for Garages at work sites. I would suggest that EMS, LEO, BIKINI TOW [ your welcome daryl), and Player Owned Operations get unmarked garages for empleyee parking. this way CIVILIANS cant use these spots as thier personal parking area without consent. This will make things easier so employees dont have their personal vehicles impounded during work which in my opinon promotes "sleeping at the workplace" and allow them to go and collect their check off duty.

**Comment by OwlCherry** [comment]
updated to include bikini tow

**Comment by xXJamieXx** [comment]
Next restart.
