### ISSUE TITLE
[BUG] Not receiving time based payments

### ISSUE THREAD

**Issue by VincentVangoatt** [xXJamieXx/paradox-bugs#272]
**Your Discord Name**
Vangoat#9993

**Describe the bug**
Having been in city about an hour and some, I have received no "Payment of X deposited" and the bank does not have any money for me.

**To Reproduce**
[Steps to reproduce the bug]
1. Hop on until a usual payment time
2. It never arrives.
3. 

**Expected behavior**
The payments to take place and deposit into the bank to be picked up.

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Intermittent issues with paychecks.

**Comment by xXJamieXx** [comment]
We believe we may have resolved this issue. Please open a new issue if there is still a problem.
