### ISSUE TITLE
[BUG] Farming - Plants start at 70% Health instead of 100%

### ISSUE THREAD

**Issue by CorFinn** [xXJamieXx/paradox-bugs#273]
**Your Discord Name**
GrandNags#9705
**Describe the bug**
When planting crops, the initial health is set to 70%. With no way to increase the health of your plants, that means, at best, you can expect 3 vegetables per plant, with perfect plant care. Realistically, 2.
**To Reproduce**
[Steps to reproduce the bug]
1. Plant a potato.
2. Check its health. It's 70%
3. Is unhealthy potato.

**Expected behavior**
As a farmer, I'd expect either to be able to affect my plant health positively, or start my plant health at 100% and work to maintain it.

**Screenshots**
None necessary
**Logs**
No Errors in F8

**Comment by JnKTechstuff** [comment]
It's possible to increase the health of plants
