### ISSUE TITLE
[BUG] Enter bug title

### ISSUE THREAD

**Issue by rainonparadox** [xXJamieXx/paradox-bugs#274]
** itsR#8165**
[Enter your Discord name]

**Describe the bug**
[A clear and concise description of what the bug is] when doing /playtime it doesn’t show a pop up of my playtime i’ve got told by other people that it’s happening to them 

**To Reproduce**
[Steps to reproduce the bug]
1. show a pop up of how many hours i’ve played
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen] a pop up on the top right of how many hours i have in the city 

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Should be fixed with latest update.
