### ISSUE TITLE
[BUG] unable to third eye sit

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#278]
**Your Discord Name**
OwlCherry#6969

**Describe the bug**
When attempting to third eye my chair, I am unable to take a seat. i tried relaunching but that did not work.

**To Reproduce**
[Steps to reproduce the bug]
1. approach desk at davis
2. use third eye to sit
3. i do not sit.

**Expected behavior**
i would usually expact to sit in the chair as per usual

**Screenshots**
https://i.imgur.com/TJLeE9E.png
https://streamable.com/dtrqen

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment]
Should be fixed in the next update.
