### ISSUE TITLE
Store location

### ISSUE THREAD

**Issue by iHardzyy** [xXJamieXx/paradox-bugs#279]
**Your Discord Name**
iHardzyy#8079

**Describe the bug**
So best way to say it without spoiling anything is when getting a store to rob the location given wasnt a store it was just a random building in paleto.
**To Reproduce**
i dont think you guys want me to say how to do this lol

**Expected behavior**
I shouldve been taken to a store not a building

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment]
Should be fixed with the next update.
