### ISSUE TITLE
[BUG] Cant see anyone after character switch

### ISSUE THREAD

**Issue by JaxCreed** [xXJamieXx/paradox-bugs#28]
**Your Discord Name**
[Spicy#5426]

**Describe the bug**
[Whenever i switch from my one character over to the other i cannot see anyone. being PD i can see peoples blips but not them ]

**To Reproduce**
[Steps to reproduce the bug]
1. Should just be switching over characters messes it up
2. results in a f8 quit to solve
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by JnKTechstuff** [comment]
Fixed https://github.com/xXJamieXx/Paradox-3.0/commit/5152275b31050008ea395be765d7f400b5315c27
