### ISSUE TITLE
Phone not tracking vehicles

### ISSUE THREAD

**Issue by ItsFoux** [xXJamieXx/paradox-bugs#280]
**Your Discord Name**
Foux#1236

**Describe the bug**
when i go to the mmi app to track my vehicles, no notification is popping up in the top right. i asked my taxi driver to try as well and they had the same issue.

**To Reproduce**
[Steps to reproduce the bug]
1. open mmi app
2. hit track
3. nothing

**Expected behavior**
when the aliens take my car i should be able to track it

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by JnKTechstuff** [comment]
Fixed
