### ISSUE TITLE
Business bank account withdrawals

### ISSUE THREAD

**Issue by k4rumk100** [xXJamieXx/paradox-bugs#282]
**Your Discord Name**
[Enter your Discord name]
K4#4819
**Describe the bug**
[A clear and concise description of what the bug is]
When I try to withdraw money from my business account it only lets me withdraw how ever much I have in my personal account.
**To Reproduce**
[Steps to reproduce the bug]
1. Go to a bank and select your business account
2. For example if you have 61K in your business account, but 22K in your personal account, you can't withdraw 24K from your business account
3. It will say you don't have enough money in the account if you try to withdraw

**Expected behavior**
[A clear and concise description of what you expected to happen]To withdraw 24K from my business account but it didn't work.
**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Fixed.
