### ISSUE TITLE
[BUG] Phones Reverted back to calling Tow operators directly, vs showing "available" / "unavailable"

### ISSUE THREAD

**Issue by Person-AL767** [xXJamieXx/paradox-bugs#283]
**Your Discord Name**
Person__AL#7454

**Describe the bug**
Looks like upon a recent update, for the past week or 2, the phones now have an option to call tow operators directly, vs just showing "available" or "unavailable" like EMS/LEO. While citizens have been picking up /311 to call us, this could diminish that behavior, making our awesome dispatching system not relevant since customers might not place a 311 now.

**To Reproduce**
[Steps to reproduce the bug]
1. Have a tow operator on duty
2. Look at phone, city services
3. see direct phone contact for tow operators on duty

**Expected behavior**
Saying "Available" or "Unavailable" in the Bikini Tow slot.

**Screenshots**
![image](https://user-images.githubusercontent.com/97871369/158030748-7cdef14a-bef3-4fbb-9711-4323cb85d2fa.png)

**Additional Recommendation?**
- would it be plausible to put "Bikini Tow (311)" on the phone when changing back, so it hints to the player that in order to get B-Tow, they need to do [t<311>]?

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Fixed.
