### ISSUE TITLE
[BUG] Enter bug title

### ISSUE THREAD

**Issue by o7JStreet** [xXJamieXx/paradox-bugs#284]
**Your Discord Name**
BayHarbourButcher#6820

**Describe the bug**
Attempted to go into the Impound Lot and grab my vehicle but the whole area seemed to be unanchored which resulted in myself falling through the map and remaining in a consistant loop.

**Expected behavior**
Able to go into the impound lot and grab the vehicle without falling through the map.

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
Nothing showed on the logs.

**Comment by JnKTechstuff** [comment]
First: 0 useful information given
Second: Should be fixed on relog
