### ISSUE TITLE
[BUG] Second time I've lost all my truck mods

### ISSUE THREAD

**Issue by TurboDummi** [xXJamieXx/paradox-bugs#285]
**Your Discord Name**
[Cybercucked 2077 /turbodummi]

**Describe the bug**
[Car modifications disappeared with new changes to LS customs]

**To Reproduce**
[Steps to reproduce the bug]
1. fly in to city
2. take truck out of garage and see that all my modifications are missing
3. assume it has something to do with the new changes to LS customs

**Expected behavior**
[I expected my contender to have all its modifications that I payed for]

**Screenshots**
Proof that I purchased car mods: 
![Screenshot (83)](https://user-images.githubusercontent.com/99993392/158036398-ad79bc07-d029-472e-8b40-d601f99dfc61.png)
 ] 
![Screenshot (85)](https://user-images.githubusercontent.com/99993392/158036405-f50c6cc1-a576-40d9-804e-6ff8f3f9c638.png)

![Screenshot (88)](https://user-images.githubusercontent.com/99993392/158036411-f4d11384-4a20-4ab9-ac60-68d70a7b6301.png)
![Screenshot (89)](https://user-images.githubusercontent.com/99993392/158036427-55dd236e-aa12-4833-abb4-4432e3da733e.png)

What my truck looks like now after update: 
![Screenshot (110)](https://user-images.githubusercontent.com/99993392/158036434-343b9743-60a8-4ff1-bde7-011557c690bb.png)

**Logs**
None

**Comment by JnKTechstuff** [comment]
Expected behavior, should work now after repurchase
