### ISSUE TITLE
[BUG] Enter bug title

### ISSUE THREAD

**Issue by Darahz** [xXJamieXx/paradox-bugs#286]
**Your Discord Name**
[Enter your Discord name]
Darahz#0001

**Describe the bug**
[A clear and concise description of what the bug is]
"Bennys" at Bikini Tow HQ does not seem to be showing up anymore

**To Reproduce**
[Steps to reproduce the bug]
1.  bring car to HQ
2.  Drive up on the Bennys repair shot place
3. Nothing

**Expected behavior**
[A clear and concise description of what you expected to happen]
Get to fix vehicles 

**Screenshots**
[If applicable, add screenshots to help explain your problem]
![image](https://user-images.githubusercontent.com/35222814/158037206-9d2941cd-a422-4aa0-aee7-098fc11398aa.png)
**Logs**
[Add your FiveM logs]

**Comment by JnKTechstuff** [comment]
@Sly-Panda Can you just re-add a shop here? I forgot to add theirs as its custom.

**Comment by Sly-Panda** [comment]
@xXJamieXx Sorted this, should be one in there now.
