### ISSUE TITLE
[BUG] Unable to drag inventory items

### ISSUE THREAD

**Issue by Ramsey20** [xXJamieXx/paradox-bugs#287]
**Your Discord Name**
[Ramsey]

**Describe the annoyance**
[Unable to drag inventory items.  I get the following script error "script:lj-inventory:nui Uncaught TypeError: $(...).draggable is not a function (@lj-inventory/htlm/js/app.js:674)"]

**To Reproduce**
[Steps to reproduce the annoyance]
1. I just open my inventory and try to drag
2. 
3. 

**Requested behavior**
[I would like to be able to drag items and stack them]

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by JnKTechstuff** [comment]
No further information. Closing
