### ISSUE TITLE
[BUG] Stuck On PTT 

### ISSUE THREAD

**Issue by wallace296** [xXJamieXx/paradox-bugs#288]
**Your Discord Name**
[Enter your Discord name]
Wall-Eze#5863
**Describe the bug**
[A clear and concise description of what the bug is]
Push to talk stuck on and or voice activity when flying in 
**To Reproduce**
[Steps to reproduce the bug]
1. fly in look at bottom left and it is stuck on yellow ring mouth moves when speaking and people hear me 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]
push to talk to work as normal 
**Screenshots**
[If applicable, add screenshots to help explain your problem]
https://streamable.com/kf21j6
**Logs**
[Add your FiveM logs]
https://drive.google.com/file/d/16HNrYTKVjcBm9UAAUWmLCiH8vWembMQ0/view?usp=sharing

**Comment by JnKTechstuff** [comment]
Try clearing cache and see if tat helps. Something goes wonky with FiveM. Its not just our server though.
