### ISSUE TITLE
[BUG] Weapon Fixing Bench Not Returning Weapon

### ISSUE THREAD

**Issue by Drunkle716** [xXJamieXx/paradox-bugs#289]
**Your Discord Name**
Drunkle716#7571

**Describe the bug**
After going to the weapon repair bench, waiting the allotted time, and receiving the email that the repair is done, I am unable to retrieve my gun

**To Reproduce**
[Steps to reproduce the bug]
1.  Place gun at weapon repair bench
2.  Waited allotted time and receive email it has been repaired.
3.  Receive prompt that you do not have a weapon in your hand and are unable to retrieve the weapon you put down.

**Expected behavior**
Should be able to pick up your gun after receiving the email

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]
[CitizenFX_log_2022-03-13T182516.log](https://github.com/xXJamieXx/paradox-bugs/files/8240613/CitizenFX_log_2022-03-13T182516.log)
[CitizenFX_log_2022-03-13T181747.log](https://github.com/xXJamieXx/paradox-bugs/files/8240614/CitizenFX_log_2022-03-13T181747.log)
[CitizenFX_log_2022-03-13T181433.log](https://github.com/xXJamieXx/paradox-bugs/files/8240615/CitizenFX_log_2022-03-13T181433.log)

**Comment by Sly-Panda** [comment]
Did you stay in the area when you placed the gun in there or did you leave and return after you got the email?

**Comment by Drunkle716** [comment]
Left and returned after getting the email

Sent from Yahoo Mail on Android 
 
  On Sun, Mar 13, 2022 at 5:18 PM, ***@***.***> wrote:   


Did you stay in the area when you placed the gun in there or did you leave and return after you got the email?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xXJamieXx** [comment]
How long did you wait after going to collect it. If you leave it too long it gets taken to the void.

**Comment by Drunkle716** [comment]
Not long after I received the email. Couldn't say exactly.

Sent from Yahoo Mail on Android 
 
  On Tue, Mar 15, 2022 at 5:29 PM, ***@***.***> wrote:   


How long did you wait after going to collect it. If you leave it too long it gets taken to the void.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Sly-Panda** [comment]
Should be fixed next update.
