### ISSUE TITLE
Smelted 4 gold ore into a gold bar, did not receive a gold bar

### ISSUE THREAD

**Issue by SupremeAnu** [xXJamieXx/paradox-bugs#29]
About 35 minutes ago, I tried smelting 4 ore into a bar and did not receive a bar. The message indicated I was successful, took 4 ore from my pockets, and left me with 1. I tried taking a nap, but the issue persisted. When I tried to interact with the smelter, I received a message that I did not have enough materials.

**Comment by JnKTechstuff** [comment]
Please follow the format of our bug report system to adequately help your situation
