### ISSUE TITLE
[BUG] Multiple cars in impound 

### ISSUE THREAD

**Issue by duke4344** [xXJamieXx/paradox-bugs#290]
**Your Discord Name** 
[Enter your Discord name] Duke

**Describe the bug**
[A clear and concise description of what the bug is]
my car spawns multiple times in impound
**To Reproduce**
[Steps to reproduce the bug]
1. go to impound
2. take my car out of impound
3. cars continue to respawn
4. 

**Expected behavior**
[A clear and concise description of what you expected to happen]
it is suppose to let me take my car out once, but now it is mulitple
**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment]
Fixed with the new garage system.
