### ISSUE TITLE
[BUG] Tow Garage Invisible Car Issue

### ISSUE THREAD

**Issue by VincentVangoatt** [xXJamieXx/paradox-bugs#291]
**Your Discord Name**
Vangoat#9993
**Describe the bug**
When placing a vehicle into the new Tow Garage, it left behind an invisible copy of my Asbo. A fellow tow worker said he could still see it, but it was invisible for me, though it didn't seem to have collision. As it requires me to be on duty to even use the garage, it was an easy impound fix, but still worth mentioning I think. After impounding the phantom, I can then get my car out fine.

**To Reproduce**
[Steps to reproduce the bug]
1. Clock on as Tow and go out back
2. Deposit vehicle into the new garage
3. It goes in fine, but leaves something you can see with your third eye. 

**Expected behavior**
The car going in, but with no ghosts, I ain't afraid of them but they can get in the way and possibly cause some issues for the tow crew.

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Fixed
