### ISSUE TITLE
[BUG] Tow operators cannot get vehicles

### ISSUE THREAD

**Issue by VincentVangoatt** [xXJamieXx/paradox-bugs#292]
**Your Discord Name**
Vangoat#9993

**Describe the bug**
Me and another tow operator cannot get the NPC to give us the menu to get out our vehicles. We are clocked in, have punched to make sure it wasn't a random local but the needed NPC, which it is, and the option is no longer on the computer, leaving Tow unable to work.

**To Reproduce**
[Steps to reproduce the bug]
1. Clock in and head around the side, look for the man with the clipboard
2. Hold your third eye key, hover over him
3. The eye remains white, with no options whatsoever.

**Expected behavior**
The vehicle menu popping up upon a right click.

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Sandy works. City fixed next restart.
