### ISSUE TITLE
[BUG] Unable to purchase personal vehicle from MRPD motorpool.

### ISSUE THREAD

**Issue by Petrovic247** [xXJamieXx/paradox-bugs#293]
**Your Discord Name**
PretenderPatrol#5993

**Describe the bug**
I am unable to purchase a personal vehicle from the MRPD motorpool. I have $50000 in my bank account so money is not the issue.

**To Reproduce**
[Steps to reproduce the bug]
1. Flew out and flew back in. Still would not allow me.
2. Went off duty and clocked back on duty. Still would not allow me to purchase.
3. 

**Expected behavior**
Click on purchase vehicle and vehicle is purchased.

**Screenshots**
https://streamable.com/00caaq
https://i.imgur.com/msgt88l.jpeg 

**Logs**
[Add your FiveM logs]
[CitizenFX_log_2022-03-14T044742.log](https://github.com/xXJamieXx/paradox-bugs/files/8241852/CitizenFX_log_2022-03-14T044742.log)
[CitizenFX_log_2022-03-14T045546.log](https://github.com/xXJamieXx/paradox-bugs/files/8241853/CitizenFX_log_2022-03-14T045546.log)

**Comment by Petrovic247** [comment]
I also tried taking out 40k in cash but same result.

**Comment by xXJamieXx** [comment]
Fixed next restart.
