### ISSUE TITLE
[BUG] New shared motorpool vehicles changes not being saved, I have no keys, and it's cycling through liveries.

### ISSUE THREAD

**Issue by Petrovic247** [xXJamieXx/paradox-bugs#295]
**Your Discord Name**
PretenderPatrol#5993

**Describe the bug**
New shared motorpool CVPI's Livery/Benny's changes were not saved. I went to pull it out and check if they saved after I changed the livery/extra. Instead I pulled out a BSCO CVPI. Then a State CVPI. I also have no keys to the vehicle.

**To Reproduce**
[Steps to reproduce the bug]
1. Store and take out vehicle. Switches every time.
2. Get out and try to lock. Get no keys error.
3. 

**Expected behavior**
When I go to benny's and apply changes to new cruisers, they should stick so that other Officer do not need to change it every shift. Any Officer that takes out this vehicle should have keys.

**Screenshots**
https://streamable.com/ye4zf0
https://streamable.com/pt4090
**Logs**
[Add your FiveM logs]
[CitizenFX_log_2022-03-14T051724.log](https://github.com/xXJamieXx/paradox-bugs/files/8242004/CitizenFX_log_2022-03-14T051724.log)

**Comment by xXJamieXx** [comment]
Fixed next restart.
