### ISSUE TITLE
ERP emotes

### ISSUE THREAD

**Issue by OgLucy6342** [xXJamieXx/paradox-bugs#296]
**Your Discord Name**
[Enter your Discord name]

**Describe the annoyance**
[A clear and concise description of what the the annoying mechanic that should be resolved is]

**To Reproduce**
[Steps to reproduce the annoyance]
1. Um no clue 
2. 
3. 

**Requested behavior**
[A clear and concise description of what you want to happen]

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]
https://media.discordapp.net/attachments/941576906665512971/953191873105756200/20220315_021659.jpg

**Additional context**
[Add any other context about the enhancement here]

**Comment by Sly-Panda** [comment]
huh?

**Comment by JnKTechstuff** [comment]
SHE CAN'T ERP SLY THATS THE ISSUE

**Comment by OgLucy6342** [comment]
The emotes brokeded

**Comment by jibbersh** [comment]
> The emotes brokeded

How is it broken? and/or have you tried using it in a car?

**Comment by OgLucy6342** [comment]
When you use the emote the two people are supposed to do an animation, but
only one does, while the other just stands there. I have not tried the ones
in the car.
