### ISSUE TITLE
[BUG] F1 wheel menu Repairs at Bennys are free right now

### ISSUE THREAD

**Issue by Person-AL767** [xXJamieXx/paradox-bugs#297]
**Your Discord Name**
Person__AL#7454

**Describe the bug**
Now when using the F1 interaction menu to repair cars, it is either free, or the indication that we paid to get the car fixed is now broken. This seems to have started since the Benny's Shop menu changed.  This will lead to less calls on Tow, and people abusing the car repair over and over.

**To Reproduce**
[Steps to reproduce the bug]
1. use personal vehicle, "break it" a bit by crashing
2. Go to any Bennys
3. Leverage F1 menu -- Repair
4. Fixed car with no charge (or.... fixed car, charged, but no notification, though I am almost positive it's free)

**Expected behavior**
Needing to pay for fixes at the repair shop

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Fixed next restart.
