### ISSUE TITLE
[BUG] Flatbed Truck at Tow HQ not spawning. 

### ISSUE THREAD

**Issue by jplink420** [xXJamieXx/paradox-bugs#300]
**Your Discord Name**
j_plink#1691
**Describe the bug**
Flatbed Truck at Tow garage not able to be pulled out by anybody. When any on-duty tow driver uses their 3rd eye to pull out the base flatbed truck, it does not spawn. But all other vehicles seem to be working properly and as expected. 

**To Reproduce**
[Steps to reproduce the bug]
1. Go to Tow HQ and clock on duty as normal.
2. Use 3rd eye on vehicle Ped and attempt to pull out Flatbed Truck
3. Fail to spawn in Flatbed Truck

**Expected behavior**
The truck to spawn and for my character to teleport inside the Flatbed truck. 

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
Nothing in Logs

**Comment by xXJamieXx** [comment]
Already fixed.
