### ISSUE TITLE
[BUG] Blueprint Bug

### ISSUE THREAD

**Issue by drl0934** [xXJamieXx/paradox-bugs#301]
**Your Discord Name**
l Pcakes l / Logan Crowe

**Describe the bug**
Prompt that I got a blueprint but not getting the Blueprint in my pocket. Happened 3 times

**To Reproduce**
[Steps to reproduce the bug]
1. Prompt Shows "You found a weird blueprint on the floor"
2. Nothing added to pockets
3. 

**Expected behavior**
Prompt Comes up and I receive the blueprint

**Screenshots**
I have video of it happening but video is to large to attach to report

**Logs**
[Add your FiveM logs]

**Comment by drl0934** [comment]
Video is attached sorry wasnt sure how to attach due to size

https://streamable.com/pycahd

**Comment by SterlingMoss** [comment]
Same thing happened to me after a few hours of garbage, huge bummer. https://medal.tv/games/gta-v/clips/eElGQl0RaVk92/d13373CHOLgD?invite=cr-MSxzQlcsNTU0OTMwMjgs

**Comment by xXJamieXx** [comment]
If you already have the blueprint in question it wont give you another. Can you confirm if this is the case?

**Comment by xXJamieXx** [comment]
If you already have the blueprint in question it wont give you another. Can you confirm if this is the case? This includes those you have used and saved to your account.

**Comment by drl0934** [comment]
I dont have that blueprint yet

**Comment by drl0934** [comment]
I never got that one yet

**Comment by xXJamieXx** [comment]
Ok can you try it again when possible and when the message shows that you found it, can you send a screenshot of your F8 menu please.

**Comment by drl0934** [comment]
sounds good might be a bit but when i do it will update in here

**Comment by SterlingMoss** [comment]
I also dont have that blueprint and its scuffed for me, same thing is happening
I can provide footage of the same thing happening to me if needed.

**Comment by xXJamieXx** [comment]
> I also dont have that blueprint and its scuffed for me, same thing is happening I can provide footage of the same thing happening to me if needed.

Just need to see if theres an error in the F8 menu thats all.

**Comment by xXJamieXx** [comment]
Due to lack of response I will be closing this bug report. We cannot resolve issues if we do not have sufficient information so until someone opens a report for this issue with sufficient logs it will be ignored.

**Comment by SterlingMoss** [comment]
I would have to go do garbage for hours and hours just to likely not get the blueprint and check the logs for you. I haven't been credited the blueprint even though I have footage of it scuffing for me, so its hard to get myself to do garbage at the moment.
