### ISSUE TITLE
Everyone has access to all impound types

### ISSUE THREAD

**Issue by iHardzyy** [xXJamieXx/paradox-bugs#302]
**Your Discord Name**
iHardzyy#8079
**Describe the bug**
Everyone has access to all impounds types
**To Reproduce**
[Steps to reproduce the bug]
1. Third eye a car
2. click the impound menu
3.  bing botta boom

**Expected behavior**
IDK was told to make it

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by JnKTechstuff** [comment]
Yeah but can you click the Police one? 👍🏻
