### ISSUE TITLE
[BUG] Car tracking

### ISSUE THREAD

**Issue by baxepw** [xXJamieXx/paradox-bugs#303]
**Your Discord Name**
baxe#0666

**Describe the bug**
[A clear and concise description of what the bug is]
When using mors mutual app to track car it does not track.
**To Reproduce**
[Steps to reproduce the bug]
1. Open mors mutual app on phone
2. Click track
3. No information shows up

**Expected behavior**
[A clear and concise description of what you expected to happen]
When you click track information on cars whereabouts should show.
**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Fixed next restart.
