### ISSUE TITLE
[BUG] Repair car overpriced

### ISSUE THREAD

**Issue by JohnDoew** [xXJamieXx/paradox-bugs#304]
J.hollow
Charges 8k for car repair
**To Reproduce**
[Steps to reproduce the bug]
1. uhh i repaired my car 2 times before at bennys went to paltio to repair there and got charged 8k
2. 
3. 

**Expected behavior**
to be charged 13-87 dollars like i was before and have my money returned.

**Screenshots**
![wow](https://user-images.githubusercontent.com/101779336/158723128-bc09e940-f07f-473f-8619-cf3bb4093dd1.jpg)

**Logs**
![logs](https://user-images.githubusercontent.com/101779336/158723440-2e0b91dd-80c4-4878-a2b7-80b1b8b7a645.jpg)

**Comment by xXJamieXx** [comment]
Fixed.
