### ISSUE TITLE
[BUG] Can not get past spawning location screen

### ISSUE THREAD

**Issue by kelvin152** [xXJamieXx/paradox-bugs#305]
**Your Discord Name**
[K3LVIN152#5855]

**Describe the bug**
[ I cant go past the pick a spawn point screen the list doesn't show and it is because i tried buying a motel room at Postel code 528 i believe i did put a ticket in but i didn't see it here so I'm making this one. I've been told give it 3 days its been about 6 days maybe more. i did make a clone just so i can still hang out with in game fellow RPrs and i was told by one of the staff that that was ok but i don't want to continue doing that because all if my progress in on my main character. her name is cookie apple]

**To Reproduce**
[Steps to reproduce the bug]
1. go to motel and purchase the room for $14 in the green box that pops up
2. relog and it should happen
3. 

**Expected behavior**
[My main character to fixed]

**Screenshots**
[
![    ]
![218_20220312165834_1](https://user-images.githubusercontent.com/24907005/158749477-cdd0e9e0-ddaa-4651-b3f4-e1bd8950c9fd.png)

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment]
This should have been fixed with a recent update.  If your character is still stuck and unable to login then please contact staff to get your character unglitched.
