### ISSUE TITLE
[BUG] PD Door locks

### ISSUE THREAD

**Issue by pulsevr34** [xXJamieXx/paradox-bugs#307]
**Your Discord Name**
Pulse+#5769

**Describe the bug**
When locking a garage door, or the lowering barriers in front of MRPD, while your car is either under the door, or on top of the lowered pillars, you will go catapulting hundreds of feet into the air, and eventually land somewhere completely random

**To Reproduce**

1. unlock MRPD garage door
2. go through
3. lock door while under it
4. bada bang bada boom

**Expected behavior**
I should be able to lock the PD garage doors when going through them, and be able to go through them without careening a million feet into the unknown

**Screenshots**

**Logs**
[Add your FiveM logs]
![FiveM_b2545_GTAProcess_ItUo3A2UiU](https://user-images.githubusercontent.com/97071437/158921278-a23f30a6-58d4-4968-bf43-dca64cac15f5.png)

**Comment by pulsevr34** [comment]
https://user-images.githubusercontent.com/97071437/158923697-ba99cd7a-3216-427d-a5ba-f8b9097c84cd.mp4

This one is alot less... destructive then the one before this, but heres a video example

**Comment by xXJamieXx** [comment]
Maybe don't lock them when you're blocking its path? That sounds like a dangerous prospect to me ;)

**Comment by pulsevr34** [comment]
> Maybe don't lock them when you're blocking its path? That sounds like a dangerous prospect to me ;)

Can you at least fix it? The doors shouldn't be slamming down at intense speeds enough to send our vehicles soaring through the ceiling and landing in the conference room... At the end of that shift there were only 3 cars left cause we had to either normally impound or scuff impound so many cars

**Comment by Sly-Panda** [comment]
> > Maybe don't lock them when you're blocking its path? That sounds like a dangerous prospect to me ;)
> 
> Can you at least fix it? The doors shouldn't be slamming down at intense speeds enough to send our vehicles soaring through the ceiling and landing in the conference room... At the end of that shift there were only 3 cars left cause we had to either normally impound or scuff impound so many cars

May be fixed next restart, let us know.

**Comment by pulsevr34** [comment]
> > > Maybe don't lock them when you're blocking its path? That sounds like a dangerous prospect to me ;)
> > 
> > 
> > Can you at least fix it? The doors shouldn't be slamming down at intense speeds enough to send our vehicles soaring through the ceiling and landing in the conference room... At the end of that shift there were only 3 cars left cause we had to either normally impound or scuff impound so many cars
> 
> May be fixed next restart, let us know.

The MRPD garage door is fixed, works beautifully. The Ballards in front of the motor pool also send you flying still.

**Comment by xXJamieXx** [comment]
Bollards fixed next restart :)
