### ISSUE TITLE
[BUG] Cant enter city with 5120X1440 resolution

### ISSUE THREAD

**Issue by Hitmandoug** [xXJamieXx/paradox-bugs#308]
Your Discord Name
Frosty#4589

Describe the bug
Unable to click the enter city button when using my default resolution of 5120x1440

To Reproduce
[Steps to reproduce the bug]

N/A

Expected behavior
Ability to click enter city on paradox start up screen using 5120x1440 resolution.

Screenshots
![test](https://user-images.githubusercontent.com/28276292/159006035-7cc5ba90-495e-4c59-b25e-381a7d257f62.jpg)

**Comment by JnKTechstuff** [comment]
We don't support your resolution

**Comment by Hitmandoug** [comment]
Thank you for the update JnKTechstuff. I also verified that a lot of the scripts are really slow at that resolution (i.e Pulling out Phone).

**Comment by JnKTechstuff** [comment]
*We will never support your resolution
