### ISSUE TITLE
[ENHANCEMENT]  Cars Getting Stuck In Beach Parking 

### ISSUE THREAD

**Issue by Vsolon** [xXJamieXx/paradox-bugs#309]
**Your Discord Name**
Vsolon#1699

**Describe the annoyance**
When pulling out your vehicle from the 307 Beach Parking your vehicle might vanish into the building. This might not be a big issue for those aware of it but if someone isn't aware of it, their car will get stuck and they'll have to get it out of impound. 

**To Reproduce**
[Steps to reproduce the bug]
1. Go to 307
2. Park your Vehicle 
3. Pull it out

**Requested behavior**
[A clear and concise description of what you want to happen]
The parking spots are moved away from the building so regardless of where you're facing they don't get eaten up by the building. 

**Screenshots**
[If applicable, add screenshots to help explain your problem]
![image](https://user-images.githubusercontent.com/13530791/159022217-078a1d77-1586-4487-8042-7e20927f4408.png)

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment]
Fixed next update.
