### ISSUE TITLE
Consuming/Using multiple items at once 

### ISSUE THREAD

**Issue by Toushime** [xXJamieXx/paradox-bugs#310]
**Your Discord Name**
Lemil#4197

**Describe the bug**
This bug allows you to consume multiple item at once. However, when you drink multiple water or food you will only get the buff from the first item you consumed and the rest will be removed from your inventory without getting the buff. In the case of farming, you can plant multiple when you are in the middle of planting one seed. The plants will then spawn into each other. 

**To Reproduce**
[Steps to reproduce the bug]
Food/Drink version
1. Have food or drink in your hotkey inventory
2. Spam the hotkey with the food/drink 
3. 

Farming version
1. buy multiple seeds and place it on your inventory hotkey
2. plant one seed
3. while in the middle of planting the first seed click or spam the hotkey with the seed to plant more 

**Expected behavior**
While eating or drinking the first item, you should not be able to consume other items. As for farming you should only be able to plant the first seeds. They should be doing the same thing when you are using a bandages 

**Screenshots**
Video of farming:
https://www.youtube.com/watch?v=GtsIt2WE2ds 

**Logs**
https://imgur.com/a/icAOsXp

**Comment by xXJamieXx** [comment]
Fixed next restart.
