### ISSUE TITLE
[BUG] You can go through locked doors when they say they're locked 

### ISSUE THREAD

**Issue by Vsolon** [xXJamieXx/paradox-bugs#311]
**Your Discord Name**
Vsolon#1699

**Describe the bug**
It appears that some doors that should be locked are not locked 

**To Reproduce**
[Steps to reproduce the bug]
1. Go to a place with a lock liked Glazed and Glorious
2.  See the Locked indicator on the left hand sign
3.  Walk into the door and go through it 

**Expected behavior**
You will go through the door despite the locked door indicator still being present 

**Screenshots**
[If applicable, add screenshots to help explain your problem]
![image](https://user-images.githubusercontent.com/13530791/159107569-c04820bb-4fd3-4195-875b-fb5c8d7c09ea.png)
![image](https://user-images.githubusercontent.com/13530791/159107575-50f5304c-3ac5-4f2f-91be-1b896d068d7f.png)

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Fixed.
