### ISSUE TITLE
[ENHANCEMENT] Racing DNF timer.

### ISSUE THREAD

**Issue by dombpw** [xXJamieXx/paradox-bugs#312]
**Your Discord Name**
brulism#4567

**Describe the annoyance**
When you end up creating a race there are a few different variables which cause the race to not officially end. If everything goes as intended, obviously everyone crosses the finish line, the race gets removed from the "Racing Overview" and you are able to run that track again. But what seems to happen more times than not is someone either headpops and cannot officially leave the race. People get taken off the track by either cops or other reasoning and they forget to leave the race and then fly out. While some stop racing after a single race, and never end up leaving the track. 

If someone is to not leave a race, no one else is able to run a race using that exact track again until the next tsunami. Also, the person who originally hosted the race for others to join cannot host ANY races again until next tsunami. 

We feel that after first place crosses the finish line, there should be an approximate three minute timer which starts, and from there anyone who does not cross the finish line within those three minutes gets removed from the race. Allowing other racers to run that track and allowing the host to continue hosting.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Host a race containing any track or number of racers greater than one. 
2. One person finish the race and quit. The other stay in the race and never quit or finish.
3. You see that the track you chose can no longer be ran, and the original host cannot provide any more races.

**Requested behavior**
[A clear and concise description of what you want to happen]
A DNF timer that can be discussed upon.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]
![image](https://user-images.githubusercontent.com/97014302/159148030-f7a4b29f-7c13-4811-a8a7-845fb6531525.png)

![image](https://user-images.githubusercontent.com/97014302/159148542-884ce336-481a-44f2-a08d-97b32ce6ab2a.png)

**Additional context**
[Add any other context about the enhancement here]

**Comment by JnKTechstuff** [comment]
Racing app is not taking any enhancement requests at this time
