### ISSUE TITLE
[ENHANCEMENT] Bikini Tow Garage Fix

### ISSUE THREAD

**Issue by LitrlyD3ad** [xXJamieXx/paradox-bugs#314]
**Your Discord Name**
D3ad#0001

**Describe the annoyance**
The garage is put all the way around back of the building on the outside, a few of the operators have said it can be fairly annoying to walk all the way around and can also lead to skuff when it comes to coming out of the garage, We are requesting that it get moved inside the HQ building towards the back corner.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Clock off for the day
2. Walk all the way around the building to grab your car
3. Realize that you need to be clocked in to take out your car, sigh in defeat
4. Go back around the building and clock back in
5. Walk back around the building and pull out your car
6. Drive your car around and go and clock back in

**Requested behavior**
Be able to remain inside the HQ building and pull out the car.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
Done.
