### ISSUE TITLE
[ENHANCEMENT] Tow callback

### ISSUE THREAD

**Issue by BullRiderMcGhee** [xXJamieXx/paradox-bugs#315]
**Your Discord Name**
[BullRiderMcGhee#3246]

**Describe the annoyance**
[a way to allow tow to call back your customer directly]

**To Reproduce**
[Steps to reproduce the annoyance]
1. 
2. 
3. 

**Requested behavior**
[ to call your customer even if not from the dispatched notification (i know you said that part might not be possible), but even a copy and paste method to the phone maybe? it would be nice so its a quicker response time because you have to pull over and type it all out and then call and wait for the pickup to start driving again, i think some people dont call due to this part, and that leaves the customer wondering if we are even coming to them with the lack of that call. that being said i try to call everyone before im enroute so or even just a way thats a little faster to call that customer back. ]

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by Sly-Panda** [comment]
You can type /replycall CallersIDNumber Message   (e.g /replycall 1 Tow is on the way) and that will send a call to that person. Their id being the number in [ ] on the call.

**Comment by Person-AL767** [comment]
> You can type /replycall CallersIDNumber Message   (e.g /replycall 1 Tow is on the way) and that will send a call to that person. Their id being the number in [ ] on the call.

**does this also work for EMS? Could see that helping in that space too "EMS en route" or something simple that tells the person not to airlift...**

**Comment by Sly-Panda** [comment]
Yes, it works for all jobs that use the dispatch system.
