### ISSUE TITLE
[BUG] Garage Skuff

### ISSUE THREAD

**Issue by LitrlyD3ad** [xXJamieXx/paradox-bugs#316]
**Your Discord Name**
D3ad#0001

**Describe the bug**
As mentioned in the QOL report attached the garage at BTOW is having issues with cars breaking upon spawning, i believe this is due to the location.

**To Reproduce**
[Steps to reproduce the bug]
1. Pull out car
2. car is spawned
3. car perma's

**Expected behavior**
The expected reaction is that the car comes out in the same condition as its put in.

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Fixed.
