### ISSUE TITLE
[ENHANCEMENT] Bank - see cash amount

### ISSUE THREAD

**Issue by SpiceF0x** [xXJamieXx/paradox-bugs#318]
**Your Discord Name**
spicedf0x#2127

**Describe the annoyance**
Can't see cash amount when depositing money

**To Reproduce**
[Steps to reproduce the annoyance]
1. Go to an ATM
2. Open up your banking
3. Try to deposit money
4. Can't see the amount of cash on you without having to exit

**Requested behavior**
I love love love the new bank UI, but something I found useful on the old one was that I could see the amount of cash I had to determine how much I wanted to put in, all on the same screen.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
Added next restart.
