### ISSUE TITLE
Cars being reset to sport engine and stock brakes randomly

### ISSUE THREAD

**Issue by SterlingMoss** [xXJamieXx/paradox-bugs#319]
SterlingMoss#1596

This is happened to me three times, and I'm not sure if this is car specific but at this point I believe this is worthy of a bug report. My Banshee keeps getting the engine reset to sport engine and stock brakes, and for whatever the reason the horn is being reset as well. It does not need to be parked in a garage for this to happen, I reapplied my engine upgrade then parked my car at the VU for work and when I got back in my car it was at sport engine and stock brakes. Unsure how to reproduce the bug without having a fully upgraded Banshee.

![2022-03-21 (12)](https://user-images.githubusercontent.com/97280265/159590487-1186f0aa-5c34-4f94-b135-a44c5e60d3c4.png)
![2022-03-21 (8)](https://user-images.githubusercontent.com/97280265/159590523-893b1f6b-680b-4913-b0b2-2157df30b87e.png)

**Comment by xXJamieXx** [comment]
Please follow the bug report template.
