### ISSUE TITLE
[BUG] EMT cant see there MDT

### ISSUE THREAD

**Issue by killer602** [xXJamieXx/paradox-bugs#32]
Killer602#6618
**Describe the bug**
[A clear and concise description of what the bug is]

**To Reproduce**
[Steps to reproduce the bug]
**To Reproduce**
1. Type /MDT
2. Keep typing MDT until this happens.
3. Keep trying and please fix this so I can get back to saving my patiants.

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
![image](https://user-images.githubusercontent.com/82824880/147884344-828bb9d6-8a8f-4b7c-a855-4144de6d636d.png)
**Additional context**
I all I see when I open up my MDT is a blurry screen, and it wont pull it up now.

**Comment by xXJamieXx** [comment]
@killer602 Can I suggest going into your FiveM settings from the home screen and enabling the feature below. Let us know if this resolves the issue :)
![image](https://user-images.githubusercontent.com/11248045/147885612-3dbdd2f0-f6ae-4cda-8ff6-495af34159e5.png)
