### ISSUE TITLE
Unable to move after throwing garbage bag in trashmaster

### ISSUE THREAD

**Issue by SterlingMoss** [xXJamieXx/paradox-bugs#320]
SterlingMoss#1596

When doing garbage, in addition to the BP bug there's a bug where after trying to throw one of the garbage bags in the trashmaster, you will not be able to move or do anything. Footage attached below

https://medal.tv/games/gta-v/clips/fcUzM6ISdKeFP/d133797wN1zL?invite=cr-MSx1YkQsNTU0OTMwMjgs

**Comment by xXJamieXx** [comment]
Please follow the bug report template.
