### ISSUE TITLE
[ENHANCEMENT] Make impound fees free when car poofs

### ISSUE THREAD

**Issue by SterlingMoss** [xXJamieXx/paradox-bugs#321]
SterlingMoss#1596

You can take a trip around the block with your car parked, turned off and doors locked and your car will poof. Since there aren't any refunds being issued for this, it would be greatly appreciated by the community if situations where you car is left out somewhere and it poofs for that to be free at the impound. If someone steals your car, it gets poofed or even just scuffed and Bikini tow isn't around, depeding on the price of your vehicle youre paying a minimum of $500 and seems like all the way up to $1500 or so. It makes you nervous to leave your car for a second, or to even use your car knowing you might lose your precious money over things that are out of your control.

**Comment by JnKTechstuff** [comment]
Impossible to tell or we would have already
