### ISSUE TITLE
[BUG] Unable to move character after throwing garbage bag into trashmaster

### ISSUE THREAD

**Issue by SterlingMoss** [xXJamieXx/paradox-bugs#324]
SterlingMoss#1596

When doing garbage, in addition to the BP bug there's a bug where after trying to throw one of the garbage bags in the trashmaster, you will not be able to move or do anything

**To Reproduce**
[Steps to reproduce the bug]
1. Do trash runs
2. Throw bags in trashmaster
3. get stuck eventually

**Expected behavior**
expect to throw bags in trashmaster and complete job

**Screenshots**
[[If applicable, add screenshots to help explain your problem]](https://medal.tv/games/gta-v/clips/fcUzM6ISdKeFP/d1337V2bfGOl?invite=cr-MSxobUosNTU0OTMwMjgs)

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Is there any errors in the F8 menu that show at the point you get stuck?

**Comment by SterlingMoss** [comment]
ooh ill check that next time and update you here👍

**Comment by SterlingMoss** [comment]
actually scratch that, looks like theres nothing showing in the f8 menu for that. Had some with farming yesterday showing when i looked just now, but thats it

**Comment by SterlingMoss** [comment]
![2022-03-22 (1)](https://user-images.githubusercontent.com/97280265/159596912-7fafeb04-cd12-4bf0-bff4-b53a72964da4.png)

**Comment by SterlingMoss** [comment]
![2022-03-22 (3)](https://user-images.githubusercontent.com/97280265/159596959-1e3d1945-698b-414d-a202-626c990f70e4.png)

**Comment by xXJamieXx** [comment]
> ![2022-03-22 (3)](https://user-images.githubusercontent.com/97280265/159596959-1e3d1945-698b-414d-a202-626c990f70e4.png)

You would need to check at the time of the issue. It's not gonna error until you run into the issue if at all.

**Comment by SterlingMoss** [comment]
okay ill let you know

**Comment by JnKTechstuff** [comment]
Not relevant error. Error is related to PMMS and this issue is now not related to the first issue. If you have separate issues open separate reports. Unable to reproduce this result, this is being closed.
