### ISSUE TITLE
[BUG] Sound issuse

### ISSUE THREAD

**Issue by Flawlessdx** [xXJamieXx/paradox-bugs#326]
**Your Discord Name**
[Flawlessxd#8302]

**Describe the bug**
[There is some kind of sound bug whenever im in the city and there is only on some places, There is a link from my pov where you can hear the sound and how it changes depending on where ur camera is facing. Atleast i have been having this issue from like a week or two, the other place where atleast i can hear this strange noice is down at Blaze and Glorious ]

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[hopefully have the sound fixed becouse it is kinda loud ]

**Screenshots**
https://streamable.com/dpjyuz

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment]
Is the bug report that you can hear sounds at different levels depending on where your camera is pointing?

**Comment by Flawlessdx** [comment]
Yeah and this only sometimes and thay are at different location almost all the time. talk with a mod about and he said that he has the same audio bug/issue that you can hear in the link i sent

**Comment by jibbersh** [comment]
Have had this happen, nothing in F8 console, no source seems to be causing it. Tried different pmms settings. Seems to be localized(stops after a certain height, stays in a certain area, can be heard with right/left ear depending on where you're facing). It also tapers off, so if you take a step out of the sounds range, it will not just cut out, it'll taper off until it's gone. Stopped randomly once night hit and did not start back up again, could be a sound associated with things loading in?

Had it happen at the bus station by Pillbox and the Fleeca bank at 656 today, only happens in the main city for me.

**Comment by JnKTechstuff** [comment]
More than likely a simple sync issue. But I have no logs 🙃🙃🙃🙃🙃🙃
