### ISSUE TITLE
Farming Script error (no growth F Spawn/Output on harvest)

### ISSUE THREAD

**Issue by ErbieIV** [xXJamieXx/paradox-bugs#327]
**Your Discord Name**
[Erbie#0117]

**Describe the bug**
[Animal growth, health and hunger are no longer updating resulting in not being able to grow said animal even after waiting a while no updates to stats and on the harvest of a scuffed animal its giving a beef with a value of none that is also broken and cant be stacked or considered an actual item not taking space in inventory either ]

**To Reproduce**
[Steps to reproduce the bug] (not entirely sure if this is the cause)
1. constantly spawning animals (spamming like 5 out at once) and then harvesting them instantly seems to be what started the bug
2. 
3. 

**Expected behavior**
[Any animals that are spawned after the bug has occured will no longer have any updates on there personal stats and will give void items which take no space and not are unstackable]  (I have a video of how this isnt working just too big to send) 

**Screenshots**
[![image](https://user-images.githubusercontent.com/102258348/159790638-0c40fe1a-27b2-4592-9c6b-75e17194fa57.png)] [](url)

**Logs**
[Add your FiveM logs]

**Comment by JnKTechstuff** [comment]
So abuse causes things to break... Who would have thought... I will apply a patch to make that abuse not possible.
