### ISSUE TITLE
[BUG] Circle map loads even tho I want square back

### ISSUE THREAD

**Issue by BullRiderMcGhee** [xXJamieXx/paradox-bugs#328]
**Your Discord Name**
BullRiderMcGhee#3246

**Describe the bug**
When you use /hub to change your map to a circle and then close out you forever have a circle map even if you switch it back. I’ve tried clearing cache, reloading in, changing it to a square map toggle and playing for awhile thinking it had to save the settings some how, I’ve reset the hud to default, restart the hud in general, and nothing seems to fix me having a circle map instead of the square, (I believe a friend of mine also never even touched the map just opened /hud and has the same problem as me now without even touching the map settings)

**To Reproduce**
[Steps to reproduce the bug]
1. Use /hud
2. Change map to circle
3. Try to change it back to square even after reloading in etc

**Expected behavior**
When changing the circle map back to a square map I should have a square map again instead of it forcing the circle map after every load in

**Screenshots**
I can take some even a video if needed but it’s not hard to reproduce I don’t believe since I accidentally forced this bug upon my friend for just taking a gander into /hub

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment]
Can you add a video of this happening preferably with F8 open as I've not been able to reproduce this bug.

**Comment by BullRiderMcGhee** [comment]
Yessir I’ll do it when I get home in the morning

**Comment by BullRiderMcGhee** [comment]
ive recorded some videos but i cant send them. so ive just posted them on youtube idk if this helps or not but i think that is the only way i can figure to send these videos to you there is two videos. https://youtu.be/SQKxoenppEg     https://youtu.be/CI2DV1uxRcY anything i can do more to help just let me know. thanks for all yall do!

**Comment by Sly-Panda** [comment]
Yeah the YouTube links were fine.  Can you try and toggle the HUD from circle to square and back a couple of times whilst inside a car to see if it works that way?

**Comment by BullRiderMcGhee** [comment]
I FIXED IT! Thank god! I had to disable mini map and mini map boarders and I have a square again! Thank you for trying your best to help me out I appreciate it
