### ISSUE TITLE
[ENHANCEMENT] full price impound prices for bicycles 

### ISSUE THREAD

**Issue by ErbieIV** [xXJamieXx/paradox-bugs#330]
**Your Discord Name**
Erbie#0117
**Describe the annoyance**
[ I find myself having to leave my bike around an awful lot whether it be leaving it at G&G too play some scene setting music or having to leave it around due to either getting sucked up into a scene or having to leave it unattended while investing staff stuff 250 for the impound is defo better than it being 500 but also at the same time with the amount of times collecting the bike has to happen its steep price to pay ]
[Steps to reproduce the annoyance]
1. lose your bike 
2. want your bike back 
3. feel the pain of paying $250 for the bike 

**Requested behaviour**
bumping down the price of bicycles specifically would be amazing making them free to get from impound would be sweet but I can see why there would be a need for a price maybe something more along the lines of $25-$50 for getting one out would be more reasonable

**Comment by Sly-Panda** [comment]
This was fixed with the new garages.
