### ISSUE TITLE
[BUG] Residential alarms for Downed people

### ISSUE THREAD

**Issue by pulsevr34** [xXJamieXx/paradox-bugs#331]
**Your Discord Name**
Pulse+#5769

**Describe the bug**
When someone goes down and calls EMS, police get a call about a residential alarm, we've had residential alarms everywhere, when I was on a scene of a bank robbery, there was a 10-43 call.

**To Reproduce**
[Steps to reproduce the bug]
1. Go down
2. Hold E to call EMS
3. Bada bing bada boom

**Expected behavior**
It should call EMS instead of making residential alarm calls

**Screenshots**
![FiveM_b2545_GTAProcess_k83GVWrIwH](https://user-images.githubusercontent.com/97071437/160217911-44962745-5c9a-42b3-8247-3123a4faf9b9.jpg)

Logs: Not applicable

**Comment by pulsevr34** [comment]
![FiveM_b2545_GTAProcess_kePWzmcHIy](https://user-images.githubusercontent.com/97071437/160218730-271f5975-ef63-4c2f-ac9f-78b01277a722.png)
 Another one

**Comment by JnKTechstuff** [comment]
Fixed
