### ISSUE TITLE
[BUG] Lock picks and House Robbers Bug

### ISSUE THREAD

**Issue by NFTzane** [xXJamieXx/paradox-bugs#332]
**Your Discord Name**
Zane#0006

**Describe the bug**
The bug I ran into is when you go to rob a house if you use a lock pick that has been used no matter what durability it is at, it will auto matically allow you into the house and not take the Lock pick out of your inventory. 

**To Reproduce**

1. Use a brand new lock pick on a car or anything it can be used for.
2. Make sure the lock pick is a little bit used.
3. Try to use lock pick to see if it takes away the lock pick in your inventory when robbing a house.

**Expected behavior**
I expected it to still take away my lock pick even if it was used a little bit.

**Screenshots**
Dont have any.

**Logs**
NA

**Comment by xXJamieXx** [comment]
Not understanding this bug report. It should just use a part of its durability no?

**Comment by Sly-Panda** [comment]
Have tested this and lockpick durability reduces as it's meant to on use.  Lockpicks are not single use items.
