### ISSUE TITLE
Trucking computer won't work (Third eye not working on this localtion) 

### ISSUE THREAD

**Issue by TeddyNM** [xXJamieXx/paradox-bugs#335]
**Your Discord Name**
[TeddyMercury#4685]

**Describe the bug**
[The trucking depot computer is not working third eye doesn't trigger at all]

**To Reproduce**
[Steps to reproduce the bug]
1. Look at computer 
2. press alt and move third eye all around 
3. 

**Expected behavior**
[Third eye turns purple and trucking menu becomes available]

**Screenshots**
[
![FiveM_b2545_GTAProcess_3k1U8HdrjW](https://user-images.githubusercontent.com/97271676/160220730-906f8897-f114-41bf-96cc-36804cea2bde.gif)

]

**Logs**
[
[CitizenFX_log_2022-03-26T014315.log](https://github.com/xXJamieXx/paradox-bugs/files/8354529/CitizenFX_log_2022-03-26T014315.log)]

**Comment by xXJamieXx** [comment]
Something was pushed a bit early. It'll be fixed next restart.
