### ISSUE TITLE
[ENHANCEMENT] increase alcohol effects

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#336]
**Your Discord Name**
Owlcherry#6969

**Describe the annoyance**
Went to the bar last night and mega enjoyed it. However after spending 600bucks I only had a 30 sec buzz. 

**To Reproduce**
[Steps to reproduce the annoyance]
1. Drink alcohol
2. Get mild buzz
3. Lasts no more than 30 sec regardless of quantity drank.

**Requested behavior**
As a cop and a civ, having booze effect you similar to 2.0 where the more you drink, the longer the effects would increase alot of silly rp.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
The values for this were tweaked. If you still believe this is an issue please open a new issue.
