### ISSUE TITLE
Farming Abuse Bug/Duplication Glitch

### ISSUE THREAD

**Issue by ithegreatgatsby** [xXJamieXx/paradox-bugs#337]
**Your Discord Name**
[Chris]

**Describe the bug**
[Go to milk cows. Third eye cow and select get milk while milking the cow third eye the cow again and hold the menu up till milking is done and then select milking again and you can do a double milking. This works with eggs also]

**To Reproduce**
[Steps to reproduce the bug]
1. https://streamable.com/4utxmv
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
https://streamable.com/4utxmv

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Fixed next restart.
