### ISSUE TITLE
[BUG] Garage door at BikiniTow HQ Being buggy

### ISSUE THREAD

**Issue by Darahz** [xXJamieXx/paradox-bugs#339]
**Your Discord Name**
Darahz#0001

**Describe the bug**
When you go to Lock/Unlock BikiniTow you get no prompt

**To Reproduce**
1. Walk up to garage door at 39
2. No prompt
3. Unable to Lock/unlock

**Expected behavior**
To lock HQ

**Comment by xXJamieXx** [comment]
Fixed.
