### ISSUE TITLE
[BUG] Not able to check time or check out of jail

### ISSUE THREAD

**Issue by ItsFoux** [xXJamieXx/paradox-bugs#340]
**Your Discord Name**
Foux#1236

**Describe the bug**
Not able to check the time or check out at the phone. Not the only person having trouble with this. The two of us currently cannot leave jail even after flying out and back into the city.

**To Reproduce**
[Steps to reproduce the bug]
1. Go to jail
2. try to check time
3. jailed for life apparently 

**Expected behavior**
Get out of jail, im innocent i swear

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment]
Should be fixed next update.
