### ISSUE TITLE
[BUG] Cannot Farm 

### ISSUE THREAD

**Issue by Craficon** [xXJamieXx/paradox-bugs#341]
**Your Discord Name**
Craficon

**Describe the bug**
When trying to farm it give the prompt that the action is impossible. On the off chance that it does plant when trying to water or give nutrients it says that the action is impossible.

**To Reproduce**
[Steps to reproduce the bug]
1. Go to Field
2. Try to plant Sugar Cane
3. 

**Expected behavior**
Sugar Cane plants and I am able to water it and give it nutrients

**Screenshots**
https://medal.tv/games/gta-v/clips/fEIIn75l4sGFE/d1337uR5Jr2m?invite=cr-MSxDcDcsNTk0MDEyOTAs
https://medal.tv/games/gta-v/clips/fEQIcVMwJr7TR/d1337VyX9I90?invite=cr-MSxCUjUsNTk0MDEyOTAs

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Fixed on live.
