### ISSUE TITLE
Repair Shops

### ISSUE THREAD

**Issue by HoneySharks** [xXJamieXx/paradox-bugs#345]
HoneySharks
When we went to the repair shop I had a quarter tank of gas and then when I used my F1 to repair my vehicle it then gave me 3/4 of gas. Not sure if this is what is supposed to happen

**Comment by xXJamieXx** [comment]
Please ensure you follow the template and fill out all the necessary information. I think I know why this happens though.

**Comment by xXJamieXx** [comment]
Fixed next restart.
