### ISSUE TITLE
[BUG] No Business Paychecks

### ISSUE THREAD

**Issue by BrotherDayZ** [xXJamieXx/paradox-bugs#347]
**Your Discord Name**
BDZ#0001

**Describe the bug**
Went to go collect the paycheck after working for the VU and some employees were not getting paid. Unsure of why or how but some employees were getting paid and others were not. Did not see any prompts for receiving a paycheck, several other employees also said they did not see anything about seeing a paycheck.

**To Reproduce**
[Steps to reproduce the bug]
1. Clock in
2. Go to collect paycheck
3. Collect nothing

**Comment by xXJamieXx** [comment]
Likely related to #272
