### ISSUE TITLE
[BUG] Planting is using entirely to much water 

### ISSUE THREAD

**Issue by TeddyNM** [xXJamieXx/paradox-bugs#348]
**Your Discord Name**
[TeddyMercury#4685]

**Describe the bug**
[Watering plants while farming is using entirely to much water, I originally had 44 bottles on me with 11 in my truck. I planted 8 onion plants watering once and fertilizing once after each plant, came back around to water crops again got 4 plants in and was out of water, grabbed my 11 out of the trunk and was out after one plant. Ran to the store got 40 more bottles was out after a few plants so in total I used over 90 bottles of water and didn't even finish two rounds of watering 8 plants]

**To Reproduce**
[Steps to reproduce the bug]
1. plant onions, water, fertilize
2. water again 
3. run out of water 

**Expected behavior**
[I expected to only use 1 bottle of water per plant, per watering not 10+ ]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]
[CitizenFX_log_2022-03-28T040604.log](https://github.com/xXJamieXx/paradox-bugs/files/8359754/CitizenFX_log_2022-03-28T040604.log)

**Comment by xXJamieXx** [comment]
Followed the reproduction steps and couldn't reproduce this unfortunately. My testing worked flawlessly only taking 1 water bottle each time.

**Comment by TeddyNM** [comment]
Could it be because I was using my ped? I was on granny when this happened.

**Comment by xXJamieXx** [comment]
I wouldn't expect so, that should have no effect. Please update us if this happens again.
