### ISSUE TITLE
[ENHANCEMENT] Crop harvesting item box

### ISSUE THREAD

**Issue by xXvolcanoXx** [xXJamieXx/paradox-bugs#349]
**Your Discord Name**
volcano#3927

**Describe the bug**
when i crop plant i get 3 corns but notification says +1 corn

**To Reproduce**
[Steps to reproduce the bug]
1. crop the plants

**Expected behavior**
notifaction say +3 corns

**Screenshots**

![20220328012143_1](https://user-images.githubusercontent.com/99762701/160375539-48c9731f-d938-4360-9a39-a156b06d0190.jpg)

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Fixed next restart
