### ISSUE TITLE
[BUG] Character face set to null

### ISSUE THREAD

**Issue by 0rigamii** [xXJamieXx/paradox-bugs#35]
**Your Discord Name**
Origami#5069

**Describe the bug**
Logged in and character was changed. 

**To Reproduce**
[Steps to reproduce the bug]
1. Log in?
2. idk
3. idk

**Expected behavior**
Expected char to be as it was when I logged out earlier without any issues 

**Screenshots**![billede](https://user-images.githubusercontent.com/97002547/147892329-b041de6b-e98e-406b-bb84-e5db05e9b7df.png)
**Additional context**
[Add any other context about the problem here]

**Comment by JnKTechstuff** [comment]
I believe this was fixed however I will leave this issue open for a day or so to confirm

**Comment by JnKTechstuff** [comment]
Marking this as fixed
