### ISSUE TITLE
[BUG] The infinite Slushy

### ISSUE THREAD

**Issue by JackSlept** [xXJamieXx/paradox-bugs#350]
**popbob#1717**
[Enter your Discord name]

**A slushy gotten at the prison that never runs out and does fill up the water bar at the bottom left, rendering buying drinks useless.**
[A clear and concise description of what the bug is]

**To Reproduce**
[Steps to reproduce the bug]
1. get sent to prison and buy a slushy
2. wait for a crash or a pc crash
3. log back in, and a slight chance of being sent free, into the city while your time is being served and now you have an infinite slushy.

**Nothing. It was an accidental bug find.**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]
[CitizenFX_log_2022-03-25T230125.log](https://github.com/xXJamieXx/paradox-bugs/files/8364969/CitizenFX_log_2022-03-25T230125.log)
[CitizenFX_log_2022-03-25T230401.log](https://github.com/xXJamieXx/paradox-bugs/files/8364970/CitizenFX_log_2022-03-25T230401.log)
[CitizenFX_log_2022-03-25T230626.log](https://github.com/xXJamieXx/paradox-bugs/files/8364971/CitizenFX_log_2022-03-25T230626.log)
[CitizenFX_log_2022-03-25T230712.log](https://github.com/xXJamieXx/paradox-bugs/files/8364972/CitizenFX_log_2022-03-25T230712.log)
[CitizenFX_log_2022-03-28T011624.log](https://github.com/xXJamieXx/paradox-bugs/files/8364973/CitizenFX_log_2022-03-28T011624.log)
[CitizenFX_log_2022-03-28T012107.log](https://github.com/xXJamieXx/paradox-bugs/files/8364974/CitizenFX_log_2022-03-28T012107.log)
[CitizenFX_log_2022-03-28T013443.log](https://github.com/xXJamieXx/paradox-bugs/files/8364975/CitizenFX_log_2022-03-28T013443.log)
[CitizenFX_log_2022-03-28T022106.log](https://github.com/xXJamieXx/paradox-bugs/files/8364976/CitizenFX_log_2022-03-28T022106.log)
[CitizenFX_log_2022-03-28T025927.log](https://github.com/xXJamieXx/paradox-bugs/files/8364977/CitizenFX_log_2022-03-28T025927.log)
[CitizenFX_log_2022-03-28T043638.log](https://github.com/xXJamieXx/paradox-bugs/files/8364978/CitizenFX_log_2022-03-28T043638.log)
[CitizenFX_log_2022-03-28T045356.log](https://github.com/xXJamieXx/paradox-bugs/files/8364979/CitizenFX_log_2022-03-28T045356.log)
[CitizenFX_log_2022-03-28T050701.log](https://github.com/xXJamieXx/paradox-bugs/files/8364980/CitizenFX_log_2022-03-28T050701.log)
[CitizenFX_log_2022-03-28T163136.log](https://github.com/xXJamieXx/paradox-bugs/files/8364981/CitizenFX_log_2022-03-28T163136.log)

**Comment by Sly-Panda** [comment]
Fixed next update
