### ISSUE TITLE
Can't Create a Second Character

### ISSUE THREAD

**Issue by TheAzian47** [xXJamieXx/paradox-bugs#352]
**Your Discord Name**
TheAzian47#2758

**Describe the bug**
I can not create a second character even after filling in my second character's information 
**To Reproduce**
[Steps to reproduce the bug]
1. load into the main starting screen
2. register a new character
3. try and create a new character

**Expected behavior**
hopefully allow us to create a second or multiple characters
**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by Dez505** [comment]
You need to make sure that there are no spaces before and after your name

**Comment by TheAzian47** [comment]
yeah, I tried 6 different names and that didn't work
