### ISSUE TITLE
[BUG] Random Blueprint Spawn While Doing Inventory Fix

### ISSUE THREAD

**Issue by Nicklmfao** [xXJamieXx/paradox-bugs#355]
Discord: Nicklol#2510 / HoneySharks#2021

Description:

Katie was getting ready to go mining and was going over counts and checking her gold ore to get ready to go out and smelt it, she claims the inventory messed up when moving stuff from her stash to her pockets, she pressed tab to get out of the menu and back into it when on the  drop section located in the screen shot below it appeared for what seems to be no reason. No one else was in the area to drop the item and just seems to have appeared out of thin air. She claims as well this reminds her of when in 2.0 you would drop something in the apartment and it would appear in everyone else's apartment as well. But I'm unsure at this time if this is a issue at all in 3.0

*To Reproduce*

This is also a issue considering I attempted to get her to reproduce the bug itself and after multiple tries nothing seems to work hence in the name this feels like more of a random event then something that can be reproduced in theory by anyone.

*Expected behavior*

To not have the blueprint given to you by random chance when going out of the inventory when not even completing mining/smelting.

*Screenshots*

1. https://gyazo.com/7122ba3abf74526ca284ec5d765346e1
2. https://gyazo.com/c015ca924ecd959e18697c7e36a958ea

*Logs*

We scrolled through logs attempting to find anything that would look like it but it was generally just full of farming logs and engine health logs, nothing that I could personally see that would be helpful.

**Comment by JnKTechstuff** [comment]
Please don't make your own mind up about logs. We request them for a reason. It's impossible for someone to generate a blueprint without getting it triggered serverside which is secured. More than likely is she had the blueprint in the deep pockets and kept being jank with their inventory probably made it disappear.
