### ISSUE TITLE
[BUG] Cant pull vehicles out of tow garage

### ISSUE THREAD

**Issue by BullRiderMcGhee** [xXJamieXx/paradox-bugs#357]
**Your Discord Name**
BullRiderMcGhee#3246

**Describe the bug**
when trying to pull out your vehicle from the tow garage i can't get past the "take out vehicle" tab it just goes away. doesn't matter if I'm clocked on duty or off i deleted my cache and it still doesn't fix it. from the last time this happened i had to get a vehicle out of impound and sent it into the garage after also clearing my cache and that seemed to fix it but I'm not certain if it's a good fix or not. and I also can't test it anymore because both vehicles are stuck inside the garage. it seems to be working for others to just not me from what i know. a youtube link is there for video reference
**To Reproduce**
[Steps to reproduce the bug]
1. go to garage press f1
2. hit take out vehicle 
3. watch menu disappear

**Expected behavior**
pull my truck out of the garage

**Screenshots**
https://i.imgur.com/pajOJZW.jpeg

https://i.imgur.com/tsDhpyh.jpeg

https://youtu.be/1HCY6sCwOMo

**Logs**
[Add your FiveM logs]

**Comment by JnKTechstuff** [comment]
Step 1: relog

**Comment by JnKTechstuff** [comment]
Stop selecting "Last location" and don't logout in a garage

**Comment by BullRiderMcGhee** [comment]
That worked thank you

**Comment by BullRiderMcGhee** [comment]
i hate to be the bearer of bad news and your probably tired of dealing with this problem but it only worked that one time when i thought it was fixed. my apologies. myself and from what i know two others in tow are having this problem i just found out how to supply my logs so im gonna send them in this reply to hopefully help better than the screen shot video i took on youtube for ya. i just happened to use last location this time, but ive spawned at multiple other areas and bummed rides off people to get back to tow garage and still no luck so both the last location and logging out at garage isnt fixes either sadly.
[CitizenFX_log_2022-04-04T015015.log](https://github.com/xXJamieXx/paradox-bugs/files/8406255/CitizenFX_log_2022-04-04T015015.log)

**Comment by xXJamieXx** [comment]
This was fixed last night.
