### ISSUE TITLE
[ENHANCEMENT] unableto see the progress bar 

### ISSUE THREAD

**Issue by xXvolcanoXx** [xXJamieXx/paradox-bugs#358]
**Your Discord Name**

volcano#3927

**Describe the annoyance**

so basicly i've lowend pc with low fps so everytime i wanna use lockpicks i can't even see the progress bar so i can't press the number on time ( usually my game not lagging unless i open inventory or i use lockpick )

**To Reproduce**

1. use lockpick
2. always fail to press the number on time
3. 

**Requested behavior**
atleast be able to see the progress bar 

**Screenshots**

https://user-images.githubusercontent.com/99762701/161018702-c6f2c8e0-82af-4edc-9696-9381a5769443.mp4

**Additional context**
[Add any other context about the enhancement here]

**Comment by Sly-Panda** [comment]
FiveM > Settings > Fix UI lag at high GPU usage

**Comment by xXvolcanoXx** [comment]
that was helpfull thx
