### ISSUE TITLE
[ENHANCEMENT] Drop leg Holsters still pull weapons out of waistband

### ISSUE THREAD

**Issue by pulsevr34** [xXJamieXx/paradox-bugs#359]
**Your Discord Name**
Pulse+#5769

**Describe the annoyance**
Drop leg holsters dont work and pull weapons out of my waistband instead of the holster.

**To Reproduce**
[Steps to reproduce the annoyance]
1. Put on a Drop leg holster/Lowered Holster
2. Pull out a weapon
3. bada bing bada boom

**Requested behavior**
DRop leg/lowered Holsters should do the same animation as the regular ones, 

**Screenshots**
https://i.imgur.com/iZ387Ys.png
https://i.imgur.com/ZfA8yT9.png

**Additional context**
N/A

**Comment by Sly-Panda** [comment]
Appears to be fixed.
