### ISSUE TITLE
[BUG] weird thing at the top of my screen 

### ISSUE THREAD

**Issue by Dez505** [xXJamieXx/paradox-bugs#36]
**Your Discord Name**
[SuperD 505 #1060]

**Describe the bug**
https://i.imgur.com/Q4uIOR0.png 

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment]
@Dez505 Can be fixed with a simple relog.
