### ISSUE TITLE
[ENHANCEMENT] Stay Crouched When Crouched

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#360]
**Your Discord Name**
OwlCherry#6969

**Describe the annoyance**
when within a crouch, if you stop moving you pop back up. its expected to remain in a crouch until the crouch has been cancelled

**To Reproduce**
[Steps to reproduce the annoyance]
1.  press ctrl to sneak, and again to crouch
2.  stay crouched for 15 seconds. 
3. within 15 seconds your character will stand back up and appear normal, until moving again.

**Requested behavior**
remain into a crouch until you have exited that position

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
Fixed next restart.
