### ISSUE TITLE
[BUG] MRPD Personal Garage Not Working

### ISSUE THREAD

**Issue by Petrovic247** [xXJamieXx/paradox-bugs#361]
**Your Discord Name**
PretenderPatrol#5993

**Describe the bug**
When you use the F1 menu at the MRPD personal garage. Nothing happens. You cannot put a vehicle into the garage or take one out.

**To Reproduce**
[Steps to reproduce the bug]
1. Tried multiple days.

**Expected behavior**
Should operate like any other garage.

**Screenshots**
https://streamable.com/9v14qi

**Logs**
[CitizenFX_log_2022-04-02T060404.log](https://github.com/xXJamieXx/paradox-bugs/files/8401934/CitizenFX_log_2022-04-02T060404.log)

**Comment by xXJamieXx** [comment]
Fixed next restart.
