### ISSUE TITLE
[BUG] Enter bug title

### ISSUE THREAD

**Issue by johndoe6969007** [xXJamieXx/paradox-bugs#363]
**Your Discord Name**
[$Anonymous$#2641]

**Describe the bug**
[when you go to the gps map and you do Garbage truck and make another place to track. its getting the destination mark follow where you look on the map  ]

**To Reproduce**
[i dont know really how and why it happened but maybe i think its related to the HUD script]
1. 
2. 
3. 

**Expected behavior**
[its just annoying and little confusing]

**Screenshots**
[https://cdn.discordapp.com/attachments/907012240547389480/959904994348396635/20220402215322_1.jpg]

**Logs**
[Add your FiveM logs]

**Comment by JnKTechstuff** [comment]
Incomplete bug report
