### ISSUE TITLE
[BUG] Missing circles on flatbed

### ISSUE THREAD

**Issue by Darahz** [xXJamieXx/paradox-bugs#365]
**Your Discord Name**
Darahz#0001

**Describe the bug**
Circles to lower flatbed/load the vehicle to the flatbed is gone.

**To Reproduce**
1. Clock on as tow
2. Take out a 4 door flatbed or a normal
3.  Circles isn't there'
![image](https://user-images.githubusercontent.com/35222814/161429451-122ecb48-44c5-4ce2-bf6e-335426a9b230.png)
![image](https://user-images.githubusercontent.com/35222814/161429461-99f99cd9-7f6b-46d9-9cee-f183caae2498.png)

**Expected behavior**
To be able to load a vehicle on the back of the flatbed.

**Logs**
[CitizenFX_log_2022-04-03T125456.log](https://github.com/xXJamieXx/paradox-bugs/files/8404553/CitizenFX_log_2022-04-03T125456.log)

**Comment by Darahz** [comment]
Forgot to mention that i did the following aswell : 
- Cleared cache
- Flew out and back in
- Clocked off and on

**Comment by ithegreatgatsby** [comment]
@xXJamieXx This is an authentication issue with the script from the announcement I saw VIA TheeBu discord and the script needs to be converted to tebex which I will get ahold of Bonnar to do that and get it transferred to Jakes CFX account. YEEE fun times

**Comment by xXJamieXx** [comment]
Fixed.
