### ISSUE TITLE
[BUG] Caio Perico shots fired calls come up on MDT

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#366]
**Your Discord Name**
owlcherry#6969

**Describe the bug**
shots fired calls from ciao perrico are appearing on mdt and overloading us with calls

**To Reproduce**
1. gun fight on perico
2. we recieve calls
3. 

**Expected behavior**
from my understanding these calls should not be registering for pd calls

**Screenshots**
https://i.imgur.com/lVE0bJW.png
https://i.imgur.com/03mKibR.png
https://i.imgur.com/ep79bjx.png

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment]
This has been fixed
