### ISSUE TITLE
[BUG] Prison Infirmary

### ISSUE THREAD

**Issue by dave1880** [xXJamieXx/paradox-bugs#367]
**Your Discord Name**
dave1#1884

**Describe the bug**
The prison guards will shoot you with a carbine rifle if you brush into them and push them over causing you to bleed out and trigger the prison alarm when you respawn. There is also nowhere to check in at the infirmary desk as well.

**To Reproduce**
1. Go to the prison and brush into a guard causing them fall over/ragdoll
2. Wait for them to stand up and shoot you
3. Bleed out and respawn triggering the alarm and making you lose everything on you

**Expected behaviour**
Make it so the guards don't shoot you and to be able to check in at the infirmary desk or to get put back inside the prison when you respawn so the alarm doesn't trigger and cause you to lose everything.

**Screenshots**
N/A 

**Logs**
N/A

**Comment by Sly-Panda** [comment]
This has been fixed with the prison update.
