### ISSUE TITLE
Gas cans having infinite fuel.

### ISSUE THREAD

**Issue by richard19999** [xXJamieXx/paradox-bugs#368]
**Your Discord Name**
[Enter your Discord name]
Its_Undy
**Describe the bug**
[A clear and concise description of what the bug is]
Gas cans having infinite fuel
**To Reproduce**
[Steps to reproduce the bug]
1. Buy a gas can from a gas station
2. Use gascan to fill up car, then put it away.
3. Pull it out and gas can is still full
**Expected behavior**
[A clear and concise description of what you expected to happen]
I expect the gas can to lose a certain amount of fuel after refilling things.
**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Duplicate of #120
