### ISSUE TITLE
[BUG] After using your limiter, car will be hard limited to 100.

### ISSUE THREAD

**Issue by CorFinn** [xXJamieXx/paradox-bugs#370]
**Your Discord Name**
GrandNagus#9705
**Describe the bug**
Using your limiter and then disengaging it will put a hard limit on your speed until you refly. My vehicle, a Drift Yosemite, has a top speed of roughly 108-110, with bumps in the road sometimes giving a short boost to 115-120. After using my limiter once, and removing it, my speed can no longer go above 100 mph, even with boosts from the road terrain. It seems the game is using the Limiter behavior after it's used, rather than the base games mechanics with terrain and how it affects speed.

**To Reproduce**
[Steps to reproduce the bug]
1. Engage Limiter. For my testing, it was at 45 mph. The limiter works, and caps my speed at 45 mph, no matter the irregularities in terrain.
2. Disengage Limiter. Limiter is not turned off. Instead, the limit speed is set to something else. In the case of my Drift Yosemite, it was 100 mph.
3. Limiter was hard engaged until I reflew.

**Expected behavior**
I expect the limiter to completely disengage after toggling it off.

**Screenshots**
N/A

**Logs**
No F8 logs or Errors shown.

**Comment by xXJamieXx** [comment]
fixed next restart

**Comment by CorFinn** [comment]
Bug still exists after restart.

**Comment by xXJamieXx** [comment]
Didn't get merged apparently so it'll be in tonight.

**Comment by CorFinn** [comment]
Confirmed fixed.
