### ISSUE TITLE
[BUG] bison spinning through the air/uncontrollably fast speed pushing when totaled/glovebox partial wipe

### ISSUE THREAD

**Issue by mjb328** [xXJamieXx/paradox-bugs#371]
**Your Discord Name**
MJB328#5303

**Describe the bug**
I parked my bison on the curb next to the Marathon Ave. apartments on Prosperity Street facing southeast direction. and emptied my bison trunk and went into my apartment. when I came out to properly store my bison I was flung through the air as if I was in a tornado. Once I was close enough to the ground I jumped out but fell through the world. When my bison finally stopped spinning I tried to push it to a los customs since it was totaled but in doing so cause my character and the car to move extremely fast, occasionally fell through the world again. Would however like to note that I did store my bison at the garage across from tinsel towers prior to this while at the public forum, That combined with the city blackout caused something to glitch maybe idk.
**To Reproduce**
[Steps to reproduce the bug]
1.Park at tinsel tower garage?(but live at marathon ave)
2. blackout (maybe)
3. glitch the glovebox (maybe)

Not fly through the sky and lose my only weapons tools... I guess

**Screenshots**
I don't have screenshots but I got video I me flying around but its too big for me to upload.

**Logs**
[Add your FiveM logs]
[buglog.txt](https://github.com/xXJamieXx/paradox-bugs/files/8447881/buglog.txt)

EDIT: idk how but my gun and mag are back in my character INV. but my drill, knife, and jerry can are still gone

**Comment by JnKTechstuff** [comment]
GTA V bug with props in hand.

Unable to fix

**Comment by johndoe6969007** [comment]
maybe i have the video you were looking for?

**Comment by Sly-Panda** [comment]
> 

This is a common GTA bug, if you have a prop stuck in your hand and you go into a vehicle it will behave like that.  Not something we can fix.  If you ever have something stuck in your hand just relog to prevent this happening.

**Comment by johndoe6969007** [comment]
https://user-images.githubusercontent.com/81580991/162675862-c2d96623-3087-40b1-a77a-13879eb11ae2.mp4
