### ISSUE TITLE
[BUG] Unable to clock off as Judge job

### ISSUE THREAD

**Issue by CorFinn** [xXJamieXx/paradox-bugs#372]
**Your Discord Name**
GrandNagus#9705

**Describe the bug**
After attempting to clock out of Vanilla Unicorn, because I wasn't receiving even my $25 paycheck, I somehow was added instead to the Judge whitelist job. There's currently no way to clock off, so my crim character is a Judge on everyone's phones.

**To Reproduce**
1. Have a job other than Judge
2. Attempt to change/clock off job at Town Hall.
3. Become a Judge instead.

**Expected behavior**
There should be a way to clock off the Judge job.

**Screenshots**
N/A

**Logs**
No error logs displayed.

**Comment by JnKTechstuff** [comment]
Doing the town hall again doesnt clock you back out?

**Comment by CorFinn** [comment]
No, it just repeatedly clocks me back in. There's only two options for me. Get a new gov ID card, and Clock In.

**Comment by JnKTechstuff** [comment]
If you do the `job` command what does it show?

**Comment by CorFinn** [comment]
https://i.imgur.com/OVAfbra.png

**Comment by JnKTechstuff** [comment]
Will attempt a fix next restart. Job removed manually
