### ISSUE TITLE
[BUG] PD Outfits Mismatched 

### ISSUE THREAD

**Issue by StealthyRiot** [xXJamieXx/paradox-bugs#374]
**Your Discord Name**
Stealthy_Riot#9382

**Describe the bug**
All PD outfits numbers became outdated with latest update. Will need to send you a corrected list for the rest later. 

**To Reproduce**
[Steps to reproduce the bug]
1. Fly in and your PD outfit is outdated
2. 
3. 

**Expected behavior**
PD outfits in the locker room should be updated to latest clothing options

**Screenshots**
LSPD Updated Standard Uniform (Short Sleeve)
https://i.imgur.com/yzbs0MT.jpg
https://i.imgur.com/365ZsFz.jpg
https://i.imgur.com/9KDurWO.jpg

Will send you all the numbers when I get time to go through it. 

**Logs**
[Add your FiveM logs]

**Comment by StealthyRiot** [comment]
[JobOutfit.lua.txt](https://github.com/xXJamieXx/paradox-bugs/files/8457400/JobOutfit.lua.txt)

Attached file has the changes for LSPD Uniforms.

**Comment by Sly-Panda** [comment]
LSPD ones have been updated and should be live now. Same story for most of the others, we'll get the missing ones updated as soon as they are sent over.
