### ISSUE TITLE
[BUG] Bucket and watering can remain floating 

### ISSUE THREAD

**Issue by Vsolon** [xXJamieXx/paradox-bugs#375]
**Your Discord Name**
[Enter your Discord name]
Vsolon#1699

**Describe the bug**
The watering can and fertilizer remain after removing them and they have hitboxes... I find some of these in the parking lot and there's even some on the road. 

**To Reproduce**
[Steps to reproduce the bug]
1. Farm until you get watering can and fertilizer stuck to your hands (not entirely sure how to reproduce )
2. Fly out
3. Fly back in 

**Expected behavior**
The watering can and fertilizer bucket should be gone

**Screenshots**
[If applicable, add screenshots to help explain your problem]
![image](https://user-images.githubusercontent.com/13530791/162561648-dd4255e0-44c0-4ce6-be98-07d07c59d2da.png)

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Believe this has been fixed.
