### ISSUE TITLE
foreword winch on tow truck

### ISSUE THREAD

**Issue by BullRiderMcGhee** [xXJamieXx/paradox-bugs#376]
**Your Discord Name**
BullRiderMcGhee#3246

**Describe the bug**
when using the cable winch on a 2 door or 4 door tow truck when using the winch to load a vehicle on the rollback the winch minuscully bumps it foreword instead of rolling the vehicle foreword and onto the rollback bed. reverse works fine but on to the bed doesn't

**To Reproduce**
1. grab a 2 door or 4 door tow truck
2. park in front of vehicle 
3. winch arrow left to put on bed 

**Expected behavior**
the vehicle slowly rolls foreword onto the rollback bed

**Screenshots**
added my logs and a video to see the problem

**Logs**

[CitizenFX_log_2022-04-09T143034.log](https://github.com/xXJamieXx/paradox-bugs/files/8457158/CitizenFX_log_2022-04-09T143034.log)

https://youtu.be/DufxOgm46Pg

**Comment by xXJamieXx** [comment]
Seems to be an issue with the script itself so waiting for an update to fix.
