### ISSUE TITLE
[BUG] Tattoo limit?

### ISSUE THREAD

**Issue by WastedHearts** [xXJamieXx/paradox-bugs#378]
**Your Discord Name**
Wasted. 🖤#0420

**Describe the bug**
Tattoo bug, possibly limited?

**To Reproduce**
[Steps to reproduce the bug]
1. When tattoos first came out I bought 19 tattoos total.
2. I could preview again after removing one, but then if I purchased it I can't preview anymore.
3. If I buy one while I can't preview it, it doesn't show up at all, not even later when tattoos reappear.

**Expected behavior**
Possibly tattoos are limited now that a bunch of people have gotten them, or limited per person?

**Screenshots**
https://medal.tv/games/gta-v/clips/hbly5pE8UMuP9/d13378QPzW5O?invite=cr-MSxXMlcsMjUwNjA5NzQs

**Logs**
[Add your FiveM logs]

**Comment by WastedHearts** [comment]
I also know some people have more than 19 so idk if there is a set limit but it's acting like there is now.

**Comment by JnKTechstuff** [comment]
Where are the logs?

**Comment by WastedHearts** [comment]
Idk how to do that.

**Comment by WastedHearts** [comment]
> Where are the logs?
[CitizenFX_log_2022-04-09T152149.log](https://github.com/xXJamieXx/paradox-bugs/files/8457654/CitizenFX_log_2022-04-09T152149.log)
[CitizenFX_log_2022-04-09T171249.log](https://github.com/xXJamieXx/paradox-bugs/files/8457655/CitizenFX_log_2022-04-09T171249.log)

**Comment by JnKTechstuff** [comment]
Limitation of game
