### ISSUE TITLE
[BUG] Prison paychecks after I'm set free

### ISSUE THREAD

**Issue by SpiceF0x** [xXJamieXx/paradox-bugs#379]
**Your Discord Name**
spicedf0x#2127

**Describe the bug**
I got sent to jail because Pig forgot to put gas in the tank and Malfo and Anicino with some other guy caught me. 

My paycheck went to $30 while I was in prison, but then after release they stayed at $30 for every paycheck until I clocked onto my job.

**To Reproduce**
1. Go to jail
2. Get paid the jail amount
3. Get set free
4. Still get paid jail amount 

**Expected behavior**
Get paid $25 after I leave jail.

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment]
Is this still happening?

**Comment by SpiceF0x** [comment]
not been to jail in a bit tbh

**Comment by xXJamieXx** [comment]
Fixed next restart.
