### ISSUE TITLE
[BUG] lspd-timeclock not logging shifts

### ISSUE THREAD

**Issue by StealthyRiot** [xXJamieXx/paradox-bugs#380]
**Your Discord Name**
Stealthy_Riot#9382
Seven#3131
G-Man#0920

**Describe the bug**
All three of us were on duty from around 9pm -12am EST 4/10/2022. 
The timeclock did not show a shift for myself, S. Holloway Stealthy_Riot#9382 or Q. Gray Seven#3131
Foreman's last shift showed 13 minutes G-Man#0920, but he was one most of the night as well. 
I did use /job to check that I was duty and it all looked good in city. 
I was also experiencing a ton of "headaches" with other officers throughout the night, so I have attached my logs. Could it be related to the constant "Weapon Checks" occurring?

**To Reproduce**
[Steps to reproduce the bug]
1.  We did a long shift that carried over to the next day
2.  I logged off/on duty earlier today, and I think that's when the issues started for me
3.  Have not found a sure fire way to replicate yet

**Expected behavior**
[A clear and concise description of what you expected to happen]
Expected behavior is to log on duty for 3 hrs and have it show up in our #lspd-timeclock logs in discord

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[CitizenFX_log_2022-04-11T002445.log](https://github.com/xXJamieXx/paradox-bugs/files/8461034/CitizenFX_log_2022-04-11T002445.log)
[CitizenFX_log_2022-04-10T210107.log](https://github.com/xXJamieXx/paradox-bugs/files/8461035/CitizenFX_log_2022-04-10T210107.log)

[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Should be fixed.
