### ISSUE TITLE
[BUG] Enter bug title

### ISSUE THREAD

**Issue by Mac-ceo** [xXJamieXx/paradox-bugs#381]
**Your Discord Name**
mac_ceo

**Describe the bug**
when entering my apartment my vehicle with be impounded no matter how long i am in my apartment makeing me pay impound feeand it is adding up

**To Reproduce**
[Steps to reproduce the bug]
1. Park vehicle out side apartment
2. enter apartment
3. exit apartment and vehicle is gone

**Expected behavior**
vehicle is still ment to be there when you have left your appartment if it is a short time and not be sent to the impound 

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[fivem logs 4 11 22.txt](https://github.com/xXJamieXx/paradox-bugs/files/8463931/fivem.logs.4.11.22.txt)

**Comment by xXJamieXx** [comment]
Just how GTA & FiveM treats vehicle cleanup. Not much we can do about this unfortunately.
