### ISSUE TITLE
[ENHANCEMENT] Car sell prices

### ISSUE THREAD

**Issue by pulsevr34** [xXJamieXx/paradox-bugs#382]
**Your Discord Name**
Pulse+#5769

**Describe the annoyance**
My 40'000$ Personal police car (I was told I was okay to sell it) gave me 1000 dollars in return.
I sold my Karin Futo that cost just over 12'000$ with the mods and got about 10K back, yet my 40'000$ car only gives 1000, not sure if its intentional since it *was* a police car but very annoying that I got so little from such an expensive car

**To Reproduce**
[Steps to reproduce the annoyance]
1. Buy Personal Police car that I 100% regret buying
2. Sell it
3. Bada bing bada boom

**Requested behavior**
I should get a lot more money selling my car then 1000$ Since it's a 40'000$ car

**Screenshots**
https://i.imgur.com/mwp3bC9.png

**Additional context**
Lost a tonne of money :(

**Comment by xXJamieXx** [comment]
The bug has been fixed and the money has been refunded to your bank account.
