### ISSUE TITLE
[BUG] Crash when leaving tattoo shop

### ISSUE THREAD

**Issue by BCA-BRIGGS** [xXJamieXx/paradox-bugs#384]
**Your Discord Name**
super raccoon#0001

**Describe the bug**
entered the tattoo shop and every time the hit ESC it crashed the game
**To Reproduce**
[Steps to reproduce the bug]
1. enter tattoo shop 
2. buy a tattoo 
3. hit esc 

**Expected behavior**
the game not to crash after you buy tattoos

**Screenshots**

**Logs**

**Comment by Sly-Panda** [comment]
Unable to reproduce this, can you provide a log for when this happens so we can look into it.

**Comment by Weebait** [comment]
I've had a similar issue it can be avoided by using backspace but every once in a while if you press escape to leave the menu the game freezes on that screen and doesn't let you do anything except restart

**Comment by xXJamieXx** [comment]
Fixed by disabling escape in that menu.
