### ISSUE TITLE
[BUG] Clip through ceiling using emotes 

### ISSUE THREAD

**Issue by Vsolon** [xXJamieXx/paradox-bugs#385]
**Your Discord Name**
[Enter your Discord name]
Vsolon#1699
**Describe the bug**
[A clear and concise description of what the bug is]
So it seems if you use notepad and notepad2 plus tablet2 and then cancel them you can clip through ceilings.

Update** I've narrowed it down to just notepad2 and tablet2

**To Reproduce**
[Steps to reproduce the bug]
1. /e notepad2
2.  /e tablet2
3. /e c 
Only managed to reproduce this at legion square parking booth, but it may be possible to use this elsewhere

**Expected behavior**
[A clear and concise description of what you expected to happen]
You should just be able to exit the animation without clipping through anything 

**Screenshots**
[If applicable, add screenshots to help explain your problem]
https://www.youtube.com/watch?v=FOCuyKlCLP4&feature=youtu.be
**Logs**
[Add your FiveM logs]

**Comment by JnKTechstuff** [comment]
R* bug with GTA V unable to fix, would require a lot of stupid code and restrictive code when we will just ban people who abuse it.
