### ISSUE TITLE
[BUG] Lockpick instantly breaking

### ISSUE THREAD

**Issue by C9Roxas** [xXJamieXx/paradox-bugs#388]
**Your Discord Name**
Roxas#1111

**Describe the bug**
While attempting to lockpick a car, my lockpick broke on its last use, upon attempting it again with a new & unused lockpick, it instantly broke and vanished from my pockets at 100% durability.

**To Reproduce**
[Steps to reproduce the bug]
1. Break a lockpick on last charge
2. Attempt to lockpick again with new and unused lockpick
3. Lockpick shatters like glass never to be seen again

**Expected behavior**
Expected to get a chance to lockpick the car and lose 10% durability, not to use a thin piece of glass.

**Comment by Sly-Panda** [comment]
When this happens are the lockpicks stacked in a pile or on their own?  I can only reproduce this when there are multiple lockpicks in the slot you are using.

**Comment by C9Roxas** [comment]
Sorry, didn't see this had a comment sent to it. I was using single lockpicks. I keep them all in separate pocket slots. I believe what happened is I had one that was nearly broken, and a fresh one at the bottom of my pockets and when that pick broke, I moved the new one to the now open slot and used it, which resulted in it instantly breaking.

**Comment by Sly-Panda** [comment]
That shouldn't be able to happen anymore with a recent change, i'll go ahead and close this and if it happens again please re-open and we'll revisit it.
