### ISSUE TITLE
[BUG] PD car poofs upstairs instead of garage

### ISSUE THREAD

**Issue by PadawanPepsi** [xXJamieXx/paradox-bugs#39]
**Your Discord Name**
PadawanPepsi#6898

**Describe the bug**
When you take a Pd car out of the shared motorpool it poofs it to the main floor. 

**To Reproduce**
[Steps to reproduce the bug]
1. take a car out of the the shared motorpool at MRPD
2. 
3. 

![FiveM_b2372_GTAProcess_QxH2SxlIQL](https://user-images.githubusercontent.com/96961442/147896531-4364b317-35c1-4c79-97cd-fec49e84e7df.jpg)

**Comment by JnKTechstuff** [comment]
https://github.com/xXJamieXx/Paradox-3.0/commit/ee21305fa30270f8d604f58a96b299b9cb90c987
