### ISSUE TITLE
[BUG] Crafting tables not working

### ISSUE THREAD

**Issue by ImPaulYo** [xXJamieXx/paradox-bugs#390]
**Your Discord Name**
Carbon#7678

**Describe the bug**
Crafting tables are not working

**To Reproduce**
[Steps to reproduce the bug]
1. Go to a crafting table (any)
2.  Third eye the table (any table)
3. Notice there is not an option for crafting. Its just a common table.  A nice table. But a useless table

**Expected behavior**
Third eye the table to craft items

**Screenshots**
[[If applicable, add screenshots to help explain your problem]](https://www.youtube.com/watch?v=tjElROwuf44)
https://www.youtube.com/watch?v=tjElROwuf44

**Logs**
[Add your FiveM logs]
N/A

**Comment by SpiceF0x** [comment]
Vending machines/coffee machines and water dispensers also not third-eyeing

**Comment by xXJamieXx** [comment]
This was fixed.
