### ISSUE TITLE
[BUG] Dinghy refueling option UNavailable/crashes fivem

### ISSUE THREAD

**Issue by mjb328** [xXJamieXx/paradox-bugs#391]
**Your Discord Name**
MJB328#5303

**Describe the bug**
When i attempt to refuel my Dinghy with a jerry can for one the option isnt there anymore and 2nd after about 20-30 second of using my 3rd eye 5m crashes
**To Reproduce**
[Steps to reproduce the bug]
1. stand in dinghy
2. pull out jerry can 
3. attempt to refuel wait 20-30 sec

**Expected behavior**
Expect to be able to refuel my boat without fivem crashing
**Screenshots**
no screenshots but ive got video but i cant seem to include it

**Logs**
[dinghyrefuelbuglog.txt](https://github.com/xXJamieXx/paradox-bugs/files/8497925/dinghyrefuelbuglog.txt)

**Comment by mjb328** [comment]
I also lost my scuba gear so can yall give me another one or $300 to go buy a new set

**Comment by OwlCherry** [comment]
> I also lost my scuba gear so can yall give me another one or $300 to go buy a new set

For this you'll need to request assistance from a staff member in discord by making a ticket. this system is for bugs not refunds :)

**Comment by xXJamieXx** [comment]
Fixed next restart.
