### ISSUE TITLE
[BUG] Fuel reset when taken out of garage

### ISSUE THREAD

**Issue by Ne8u11a** [xXJamieXx/paradox-bugs#393]
**Your Discord Name**
CaptnNebula

**Describe the bug**
My vehicle gets put in the garage full of fuel and comes out empty. Multiple garage locations

**To Reproduce**
[Steps to reproduce the bug]
1. fill vehicle with fuel
2. put in garage
3. take vehicle out

**Expected behavior**
If I put my vehicle in the garage with a full tank, it should be full when I pull it back out

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment]
Going to close this out, if it's an issue with the new script just post back in it and we'll look into it again.
