### ISSUE TITLE
[BUG] Can't enter text for scenes

### ISSUE THREAD

**Issue by SpiceF0x** [xXJamieXx/paradox-bugs#394]
**Your Discord Name**
spicedf0x#2127

**Describe the bug**
Can't enter text for scenes, every other bit is available

**To Reproduce**
1. Try to create scene by pressing 'k'
2. Receive pop up without text field

**Expected behavior**
Have a text field

**Screenshots**
![20220416120540_1](https://user-images.githubusercontent.com/96963965/163672660-476e07f5-967c-4211-be60-31418fd429bd.jpg)

**Logs**
Nothing showing in F8. 
[CitizenFX_log_2022-04-16T103646.log](https://github.com/xXJamieXx/paradox-bugs/files/8499779/CitizenFX_log_2022-04-16T103646.log)

**Comment by SpiceF0x** [comment]
[CitizenFX_log_2022-04-16T164821.log](https://github.com/xXJamieXx/paradox-bugs/files/8500327/CitizenFX_log_2022-04-16T164821.log)

**Comment by xXJamieXx** [comment]
Fixed.
