### ISSUE TITLE
[BUG] Apartment moving glitch

### ISSUE THREAD

**Issue by mjb328** [xXJamieXx/paradox-bugs#395]
**Your Discord Name**
MJB328#5303

**Describe the bug**
I logged on the server 1st time after a reset, changed outfits, checked my inventory then left my apartment. When I turned around to reenter my apartment it ask to change instead of enter.

**To Reproduce**
[Steps to reproduce the bug]
1. log on for 1st time after most recent server reset
2. change outfits (maybe)
3. leave apartment
4. try to reenter apartment

**Expected behavior**
I expect to be able to reenter my apartment without being charged as if I'm moving in.

Dont have screenshots, but Sly has access to a recording of the glitch 1st hand

[If applicable, add screenshots to help explain your problem]

**Logs**
[Apartmentbuglogs.txt](https://github.com/xXJamieXx/paradox-bugs/files/8500475/Apartmentbuglogs.txt)

**Comment by I3lackwidow** [comment]
[CitizenFX_log_2022-04-17T234624.log](https://github.com/xXJamieXx/paradox-bugs/files/8502675/CitizenFX_log_2022-04-17T234624.log)

**Comment by Sly-Panda** [comment]
Can't seem to reproduce this now with the recent apartments change, is this still happening?

**Comment by mjb328** [comment]
No I dont think it has charged me since the UI change, despite that fact that still says it cost $500
