### ISSUE TITLE
[BUG] can't roll joint

### ISSUE THREAD

**Issue by xXvolcanoXx** [xXJamieXx/paradox-bugs#397]
**Your Discord Name**
volcano#3927

**Describe the bug**
can't roll joints

**To Reproduce**
[Steps to reproduce the bug]
1. try to roll a joint
2. it wont work
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by JnKTechstuff** [comment]
K
