### ISSUE TITLE
[BUG] Cars disappear when approached from the rear over 70mph

### ISSUE THREAD

**Issue by CorFinn** [xXJamieXx/paradox-bugs#399]
**Your Discord Name**
GrandNagus#9705

**Describe the bug**
All cars will disappear when approached from the rear if you're driving at 70+ mph. The video attached explains it better than I can.

**To Reproduce**
[Steps to reproduce the bug]
1. Reach 68 mph. You can bump cars from behind.
2. Reach 70 mph. Car disappears when you're near it (only from the rear), leaving a floating driver.
3. Activate Kitty Pride powers and phase through vehicles and people.

**Expected behavior**
Disappearing cars break immersion badly. I expect not to see cars poof in and out depending on how close I am.

**Screenshots**
https://youtu.be/H4VggTehAW4

**Logs**
n/a (nothing popped up in F8 logs)

**Comment by JnKTechstuff** [comment]
Try this now

**Comment by CorFinn** [comment]
Resolved.

**Comment by JnKTechstuff** [comment]
Its funny, what you saw was the anti-ghosting system actually working properly. The thing that told it key parameters however messed up. This is being marked as complete!
