### ISSUE TITLE
[BUG] Hunting Bait Cannot Stack

### ISSUE THREAD

**Issue by jibbersh** [xXJamieXx/paradox-bugs#40]
**Your Discord Name**
Jibberish#2741

**Describe the bug**
Hunting bait cannot be stacked while buying or while moving it in inventory spaces. Unsure if this is intentional or a bug.

**To Reproduce**
[Steps to reproduce the bug]
1. Buy hunting bait (can only buy quantity of one)
2. Attempt to stack hunting bait on top of other hunting bait.
3. 

**Expected behavior**
Expecting it to be able to stacked, but unclear if this is intentional now.

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by JnKTechstuff** [comment]
Hunting bait should have durability. This is fixed in: https://github.com/xXJamieXx/Paradox-3.0/commit/3d1229841905f627e009d11d161e8aa8fbbea581
