### ISSUE TITLE
[BUG] Trash Blueprint Bug

### ISSUE THREAD

**Issue by Weebait** [xXJamieXx/paradox-bugs#400]
**Your Discord Name**
Weeb#5266

**Describe the bug**
When I do the trash job and get a prompt that I found a blueprint it doesn't appear in my inventory

**To Reproduce**
[Steps to reproduce the bug]
1. Do trash collection
2. Get blueprint notification
3. Don't receive the blueprint

**Expected behavior**
When I receive the blueprint it either be possible to craft the item or give me the ability to learn to do so

**Comment by xXJamieXx** [comment]
Still awaiting logs on this...

**Comment by Frosticle1** [comment]
I just had the same issue but here are my logs
[CitizenFX_log_2022-04-22T150446.log](https://github.com/xXJamieXx/paradox-bugs/files/8544800/CitizenFX_log_2022-04-22T150446.log)

**Comment by xXJamieXx** [comment]
Just tested and works fine.
