### ISSUE TITLE
[ENHANCEMENT] Decreasing Bait Delay 

### ISSUE THREAD

**Issue by Weebait** [xXJamieXx/paradox-bugs#401]
**Your Discord Name**
Weeb#5266

**Describe the annoyance**
Delay between hunting/ price

**To Reproduce**
[Steps to reproduce the annoyance]
1. Go hunting (Drive for 10 minutes to reach a hunting spot)
2. Place bait and wait 2 minutes for something to happen 
3. Wait a further 5 minutes to place another bait

**Requested behavior**
As hunting is already far from profitable as the knife alone costs 350$ not counting the gun, bullets and bait while gaining peak of 300$ for the best possible item on the player market and 85$ to the trader it would be nicer if the frequency of the animals was increased by removing or decreasing the delay on placing a new bait

**Comment by Sly-Panda** [comment]
The wait between placing bait is nowhere near 5 minutes.

**Comment by Weebait** [comment]
It isn't that bad but it is still pretty long for what is ultimately not worthwhile in terms of money. I feel it could be better if the timer was reduced or at the very least allowed for multiple baits to be active at the same time.
