### ISSUE TITLE
[BUG] Port Authority Boats

### ISSUE THREAD

**Issue by 211Walker** [xXJamieXx/paradox-bugs#402]
**Your Discord Name**
[tonytone883

**Describe the bug**
I am unable to pull out a Port Authority boat from any the said locations after being told I could.  I have had other officers go the location 349 and they also can not see or pull any boats.

- Paleto (old)
- Boat Ramp (old)
- LS Docks (Old port authority HQ at docks)
- Fishing village on west side
- Sandy Shores boat house

**Screenshots**
![W3bxw6NMIz](https://user-images.githubusercontent.com/96933759/163888134-31d209e8-00df-4935-917f-d6e4ccf33817.jpg)
![OfsPh8fesy](https://user-images.githubusercontent.com/96933759/163888144-b666748c-c889-454b-b733-11b4cb953ee6.png)
![ziygp7QFRx](https://user-images.githubusercontent.com/96933759/163888152-806a8ee0-b97d-4f0e-a8d1-45102fd18b2e.png)

**Logs**
[Add your FiveM logs]

**Comment by JnKTechstuff** [comment]
Is it every cop job or just HC?

**Comment by 211Walker** [comment]
It’s every cop.
