### ISSUE TITLE
[BUG] Cows not dropping meat when unable to hold partial amount

### ISSUE THREAD

**Issue by oaty1** [xXJamieXx/paradox-bugs#403]
**Your Discord Name**
oaty1

**Describe the bug**
When farming, killing cows but with a full inventory will kill the cows but wont drop the meat, even if the inventory isnt full, just not enough to hold all the meat it wont give you any
**To Reproduce**
[Steps to reproduce the bug]
1. Inventory full enough not to hold all the meat
2. Sell cows to the butcher
3. 

**Expected behavior**
Maybe a prompt or butchers inventory that can store the meat for you

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment]
Excess meat will fall into a pile on the ground now if your inventory is full.
