### ISSUE TITLE
[BUG] Gold chains and Cut gem deleted when necklace craft is cancelled

### ISSUE THREAD

**Issue by mjb328** [xXJamieXx/paradox-bugs#405]
**Your Discord Name**
MJB328#5303

**Describe the bug**
While crafting a diamond and then a ruby necklace I cancelled the process and the game removed (deleted) 1x chain and 1x cut gem. At first thought it was because I missed the # prompt but after trying/testing it a 2nd time i realized it was cancelled the crafting process that deleted the chains and gems.

This happen before the change to steel drill bits/ personal mines, so I dont know is this is a bug or intentional.
**To Reproduce**
[Steps to reproduce the bug]
1. craft a necklace
2. ESC cancel while crafting
3. 1xchain and 1xgem removed from inventory, but no jeweled necklace.

**Expected behavior**
I expect the chain and gem to remain since this doesn't happen if you cancal while cutting or smelting.
**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
Didnt save the log at the time as I thought it was a new game mechanic.

**Comment by JnKTechstuff** [comment]
Thats the point so you can't endlessly try the skillcheck
