### ISSUE TITLE
Not able to emote

### ISSUE THREAD

**Issue by Flora45** [xXJamieXx/paradox-bugs#406]
**Your Discord Name**
[Flora#8531]

**Describe the bug**
[Emotes seem to be disabled for use. ]

**To Reproduce**
[Steps to reproduce the bug]
1. Type /e [any emote] 
2. 
3. 

**Expected behavior**
[Emotes should work when typing the correct emote]

**Screenshots**
[None]

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
They were fixed before you put the report in.
