### ISSUE TITLE
[BUG] Diving spots missing

### ISSUE THREAD

**Issue by TurboDummi** [xXJamieXx/paradox-bugs#407]
**Your Discord Name**
[CYBERCUCKED 2077#9166]

**Describe the bug**
[When looking at gps to go search for a diving location, I noticed there were none on the map, went to where they would be if they were marked because I assumed maybe it was reworked so that the spots are no longer visible on the map but there's nothing in where the spots once were, isn't just me who is experiencing it other people are too.]

**To Reproduce**
[Steps to reproduce the bug]
1. look at gps to search for diving location
2.  see no orange blips on gps around the ocean
3. 

**Expected behavior**
[To be able to see the marked diving locations]

**Screenshots**
[
![Screenshot (185)](https://user-images.githubusercontent.com/99993392/164110452-433987a3-4e58-4007-8724-030097147490.png)
]
![Screenshot (186)](https://user-images.githubusercontent.com/99993392/164110459-783a8592-b5b4-4a35-b169-ff6c724c57c6.png)

**Logs**
[
[CitizenFX_log_2022-04-19T213236.log](https://github.com/xXJamieXx/paradox-bugs/files/8516791/CitizenFX_log_2022-04-19T213236.log)

**Comment by xXJamieXx** [comment]
Fixed next restart.
