### ISSUE TITLE
[BUG] gun ammo disappearing

### ISSUE THREAD

**Issue by icrizpy** [xXJamieXx/paradox-bugs#408]
**Your Discord Name**
the big ape#5165

**Describe the bug**
I noticed when trying to put ammo in my gun today all the ammo disappeared. Once ammo is loaded it disappears when you put away and take the gun out again.

**To Reproduce**
[Steps to reproduce the bug]
1.  Load gun
2.  Put it away
3.  Take the gun out again

**Expected behavior**
After loading a gun, putting it away and taking it out again all the ammo will disappear

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment]
Seems to be working fine now on live.
