### ISSUE TITLE
[BUG] Hunting Knife Durability

### ISSUE THREAD

**Issue by jibbersh** [xXJamieXx/paradox-bugs#41]
**Your Discord Name**
Jibberish#2741

**Describe the annoyance**
Hunting Knife durability seems excessively low for the price and payback. You can use it 5 times, I received a highest quality($90), a second highest quality($80), and 3 medium quality carcasses($50). They sold for a total of $220. The hunting knife sells for $350. This plus paying $25 for bait, means that you're paying $475 to get max $450(assuming you get 5 highest quality carcasses). 

**To Reproduce**
[Steps to reproduce the annoyance]
1. Buy hunting knife for $350
2. Buy bait x5 for $125
3. Hunt 5 times until knife breaks
4. Sell carcasses for $450 or less

**Requested behavior**
Either the price of the knife should be lower, the durability should be higher, or the price of carcasses should be more. Hunting should be in line with trucking/garbage jobs, especially as it seems intentionally more challenging to figure out to do it.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by JnKTechstuff** [comment]
Fixed in https://github.com/xXJamieXx/Paradox-3.0/commit/3d1229841905f627e009d11d161e8aa8fbbea581
