### ISSUE TITLE
[BUG] Trucking has not been available for 2 days

### ISSUE THREAD

**Issue by TurboDummi** [xXJamieXx/paradox-bugs#412]
**Your Discord Name**
CYBERCUCKED 2077#9166

**Describe the bug**
[When going to the trucking depot, the npc to talk to for trucking is not there and nothing happens when using third eye, it has been like this for about a couple days.]

**To Reproduce**
[Steps to reproduce the bug]
1. Go to trucking
2. Notice there is no local to talk to for trucking and no third eye cues
3. 

**Expected behavior**
[For the trucking local to appear and to be able to do trucking.]

**Screenshots**
[
![Screenshot (195)](https://user-images.githubusercontent.com/99993392/164485048-d3af3fbf-599e-49f6-9119-c5f49c8b771e.png)
]

**Logs**
[CitizenFX_log_2022-04-21T134217.log](https://github.com/xXJamieXx/paradox-bugs/files/8532057/CitizenFX_log_2022-04-21T134217.log)

**Comment by Sly-Panda** [comment]
Seems to be in the right place...
