### ISSUE TITLE
[BUG] Freeze up requiring nap during trash collection job

### ISSUE THREAD

**Issue by Weebait** [xXJamieXx/paradox-bugs#413]
**Your Discord Name**
Weeb#5266

**Describe the bug**
While completing the trash collection job the character freezes in place after depositing trash being picked up or moved just causes you to fly and move in place mid air

**To Reproduce**
[Steps to reproduce the bug]
1. Collect Garbage
2. Throw Trash into truck
3. Freeze

**Expected behavior**
No freezing and need to restart when trying to finish a job

**Logs**
[   1474078] [b2545_GTAProce]             MainThrd/ GetNetworkObject: no object by ID 0
[   1475344] [b2545_GTAProce]             MainThrd/ InvokeNative: execution failed: Error executing native 0x961ac54bf0613f5d at address 0x7ff64c9e20d5.
[   1475344] [b2545_GTAProce]             MainThrd/ ^1SCRIPT ERROR: Execution of native 961ac54bf0613f5d in script host failed: Error executing native 0x961ac54bf0613f5d at address 0x7ff64c9e20d5.^7
[   1475344] [b2545_GTAProce]             MainThrd/ ^3> fn^7 (^5@qb-garbagejob/client/main.lua^7:183)

**Comment by Sly-Panda** [comment]
Should be fixed next update
