### ISSUE TITLE
MAP is still there when i am on foot

### ISSUE THREAD

**Issue by HazeLT04** [xXJamieXx/paradox-bugs#414]
**Your Discord Name**
S100#9946

**Describe the bug**
Everytime i load into the server for some reason my minimap is still there even when im on foot

**To Reproduce**
[Steps to reproduce the bug]
1. load in 
2. minimap is there
3. 

**Expected behavior**
[it would be nice if the minimap would stop showing for me because i have been banned by the anticheat today for that reason but i have been unbanned]

**Screenshots**
https://user-images.githubusercontent.com/103951489/164722107-0ab2dcdf-0401-470f-92be-ff63be333825.png

**Logs**

[Logs.txt](https://github.com/xXJamieXx/paradox-bugs/files/8541395/Logs.txt)

**Comment by Sly-Panda** [comment]
Can you give a bit more info on this one, when did it start happening / does it always happen / what are you doing when it's happening/ can you attach logs .etc

Just saying it's happening isn't really helpful in finding a solution.

**Comment by HazeLT04** [comment]
It started around a week ago i didnt notice till staff told me And yes it always happens now also i just load in and it always just pops up and the logs i have included above

**Comment by Sly-Panda** [comment]
What happens when you do the hud reset?

**Comment by HazeLT04** [comment]
When i do the hud reset it keeps the map there nothing changes

**Comment by Sly-Panda** [comment]
Can you clear your FiveM Cache and see if it clears it?  Something is keeping it up there and there aren't many things that would do that.

**Comment by HazeLT04** [comment]
Ive done that and for some reason it is still there

**Comment by Sly-Panda** [comment]
Alright so I've dug into this a lot and cannot figure out why it would only be doing this for you.  Do you have any mods on your GTA at all, visual or otherwise?

**Comment by HazeLT04** [comment]
my map just somehow started showing i have no clue i didnt change anything its just there now
