### ISSUE TITLE
[BUG] Unable to lower car-hauler back

### ISSUE THREAD

**Issue by Darahz** [xXJamieXx/paradox-bugs#415]
Darahz#0001

### Problem/issue
Car haulers back end don't go down. Missing the options in the third eye to interact with the vehicle

### Steps to reproduce the bug
1.  Take out Semi and car hauler
2.  Use third eye to bring up menu to lower back end of car hauler
3.  No menu pops up.

### Expected behavior 
To be able to lower back-end of the car hauler

###  Screenshots
![image](https://user-images.githubusercontent.com/35222814/164775143-c0e5301d-f804-4ea1-92ee-8b6cbd849a67.png)

Doesnt matter where you do it for that matter

###  Add your FiveM logs
[CitizenFX_log_2022-04-22T154807.log](https://github.com/xXJamieXx/paradox-bugs/files/8543260/CitizenFX_log_2022-04-22T154807.log)

**Comment by xXJamieXx** [comment]
Works when tested in live.
