### ISSUE TITLE
[BUG] Trash Collection Blueprint Bug

### ISSUE THREAD

**Issue by Weebait** [xXJamieXx/paradox-bugs#418]
Weeb#5266

**Describe the bug**
When I do the trash job and get a prompt that I found a blueprint it doesn't appear in my inventory

**To Reproduce**
[Steps to reproduce the bug]
1. Do trash collection
2. Get blueprint notification
3. Don't receive the blueprint

**Expected behavior**
When I receive the blueprint it either be possible to craft the item or give me the ability to learn to do so

**Screenshots**
(https://medal.tv/games/gta-v/clips/iPfyvH3eNqiL7/d1337PSPqYGw?invite=cr-MSw1c1MsNjQwMDIyMjQs)

**Logs**
![1](https://user-images.githubusercontent.com/103544801/164950975-138205d8-da70-4c58-a788-cb577a68c2c1.PNG)
[CitizenFX_log_2022-04-24T002318.log](https://github.com/xXJamieXx/paradox-bugs/files/8548835/CitizenFX_log_2022-04-24T002318.log)

**Comment by xXJamieXx** [comment]
I tested this earlier and it worked fine.

**Comment by Weebait** [comment]
What should I do then? I still need the blueprint

**Comment by xXJamieXx** [comment]
I've added extra prints next restart to hopefully narrow down the issue so i'll provide an update once I see the results of that.

**Comment by Frosticle1** [comment]
I've been grinding Garbage just for the bp and it happened 3 times now
[CitizenFX_log_2022-04-24T052431.log](https://github.com/xXJamieXx/paradox-bugs/files/8549661/CitizenFX_log_2022-04-24T052431.log)

**Comment by xXJamieXx** [comment]
Pushed a fix which may resolve this issue so feel free to test.

**Comment by Weebait** [comment]
Fixed
