### ISSUE TITLE
[BUG] Boat engine breaks for unkown reason

### ISSUE THREAD

**Issue by TurboDummi** [xXJamieXx/paradox-bugs#419]
**Your Discord Name**
[CYBERCUCKED 2077#9166]

**Describe the bug**
[When driving the dinghy the boats engine will suddenly seize up and you will be stuck moving at what is quite literally a snails pace, the amount of fuel in the boat does not seem to affect this as i tested this with both an empty fuel tank and a newly filled one and got the bug with both of them.]

**To Reproduce**
[Steps to reproduce the bug]
1. take out boat from docks or jump out of boat 
2. hop back in boat and notice that your boat move slower than your character walks
3. 

**Expected behavior**
[For my boat to be able to drive properly and not move at 2mph]

**Screenshots**
[I only have a video present, I'm not able to upload it via bug report since its over 10MB
but if staff would like me to submit the video via discord DM I would be more than happy to.]

**Logs**
[None from last night when this occurred, unfortunately soon after this happened, the wizard issue happened and I alt f4'd because I didn't want to stay in the city to hear racist words towards me and get blown up.]

**Comment by xXJamieXx** [comment]
Did you set the speed limiter or toggle the anchor by accident?

**Comment by TurboDummi** [comment]
nope, I checked incase I did and jumped in and out the boat to try and reset it, I cant show it because the video is too big for github but in the video you can see sparks coming out of the engine while its at full fuel

**Comment by xXJamieXx** [comment]
You upload the video to a website like Streamable and share the link.

**Comment by TurboDummi** [comment]
https://streamable.com/pmhgm7 here is the video i hope this helps.

**Comment by Sly-Panda** [comment]
That's how vehicles behave then they were out of fuel, might have visually been showing as having fuel and just didn't.  We've since changed the fuel script so going to close this out and if it happens again just reopen and we'll look into it again.
