### ISSUE TITLE
Garage and new cars

### ISSUE THREAD

**Issue by Deadles** [xXJamieXx/paradox-bugs#420]
**Your Discord Name**
Deadles#7777

**Describe the bug**
I bought a car from the dealership and did not store it so therefore the car should have gone to the default garage.  The car despawned so I checked my phone and did not find the car in any of the garages or on my phone.

**To Reproduce**
[Steps to reproduce the bug]
1. Buy a car from the dealership
2. Wait for car to despawn
3.

**Comment by Sly-Panda** [comment]
This should be fixed now.
