### ISSUE TITLE
[BUG] Apartment utilities aren't functional

### ISSUE THREAD

**Issue by Weebait** [xXJamieXx/paradox-bugs#421]
**Your Discord Name**
Weeb#5266

**Describe the bug**
The stash within the apartment isn't functional and neither is the wardrobe

**To Reproduce**
[Steps to reproduce the bug]
1. Access stash/ wardrobe (hear it open)
2. Nothing occurs
3. Try again

**Expected behavior**
The clothes previously saved to be in the wardrobe and the stash to contain everything I've put in it and for me to be able to interact with those items while also being able to insert new ones

**Comment by Sly-Panda** [comment]
Stash is working fine, clothing will be fixed next update.

**Comment by Weebait** [comment]
Clothing still isn't functional
