### ISSUE TITLE
[BUG] Enter bug title

### ISSUE THREAD

**Issue by Flora45** [xXJamieXx/paradox-bugs#422]
**Your Discord Name**
[Flora#8531]

**Describe the bug**
[Giving an item to a player with a full inventory duplicates the item. The item drops on the ground due to their inventory being full, while also staying in your pocket. ]

**To Reproduce**
[Steps to reproduce the bug]
1. Give a player an item while their inventory is full
2. 
3. 

**Expected behavior**
[The item should come out of your inventory when dropped on the ground]

**Screenshots**
[Can send video of occurrence if needed]

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment]
Fixed
