### ISSUE TITLE
[BUG] Taser unlimited ammo

### ISSUE THREAD

**Issue by Lucius243** [xXJamieXx/paradox-bugs#424]
**Your Discord Name**
Lucius #9921

**Describe the bug**
When sitting in the passenger seat of a car, you are able to shoot the taser with no ammo and it still works fine. 

**To Reproduce**
[Steps to reproduce the bug]
1. Sit in passenger seat of a car
2. Shoot taser that has no ammo
3. It will still fire

**Expected behavior**
If my taser has no ammo, I would expect it not to be able to fire

**Comment by xXJamieXx** [comment]
Fixed next update.
