### ISSUE TITLE
[BUG] F1 menu not displaying options within work for LEO

### ISSUE THREAD

**Issue by erniexhamer** [xXJamieXx/paradox-bugs#426]
**Your Discord Name**
Ernie Hamer#5237

**Describe the bug**
When signed in as LEO, the work menu within the F1 radial menu no longer contains any of the prior options including radio/panic etc.

**To Reproduce**
[Steps to reproduce the bug]
1. Sign in as LEO
2. Turn on Radio
3. Hit F1, then work

**Expected behavior**
I expect the options within this window including the radio channels, and panic

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by Sly-Panda** [comment]
Fixed next update

**Comment by OwlCherry** [comment]
still not working

**Comment by Sly-Panda** [comment]
Are you sure?  I just tested it on live as CID and it's working fine.

**Comment by Sly-Panda** [comment]
![image](https://user-images.githubusercontent.com/43046128/165874972-f864a349-0303-4af2-812b-3c8403b9684b.png)

**Comment by OwlCherry** [comment]
i was down and could not use the f1 as a cop for the panic button

**Comment by OwlCherry** [comment]
i had to use /panic

**Comment by Sly-Panda** [comment]
Thank you for the clarification.  The panic when down is not the same option as when you are on your feet.  I'll get that linked up.

**Comment by OwlCherry** [comment]
OOOO okay :P no problem sorry for confusion haha

**Comment by Sly-Panda** [comment]
Fix is in for the next time an update is pushed, for now just use /panic as that will work fine and the rest of the menu works good too.  (There is an empty Work tab on the radial menu that will be gone with that update as well).
