### ISSUE TITLE
[ENHANCEMENT] Male characters being able to put up their long hair.

### ISSUE THREAD

**Issue by TheGraveyardShift** [xXJamieXx/paradox-bugs#428]
**Your Discord Name**
TheGraveyardShift#6865

**Describe the annoyance**
I can't put my male characters long hairstyle up. His haircut is is style 85 and it says there is no variants for the style. I have tried all long hair styles for men and none work.

**To Reproduce**
1. Make a male character and give him long hair
2. Use F1 menu to put up hair
3. 

**Requested behavior**
Id like to see some ponytail variants added to our hairstyles. I believe its style 43 that i suits this best.

**Screenshots**
Male Haircut style 85
![Male Haircut 85](https://user-images.githubusercontent.com/104471236/165485584-d78d94f8-f6b2-43dc-8fbb-8d477305f54f.JPG)

This is the male haircut style 43 which i think would be a great variant for the long styles.
![Male Haircut 43](https://user-images.githubusercontent.com/104471236/165485694-38b89097-9914-43fd-b655-9f9cd4aa961a.JPG)

**Additional context**

https://user-images.githubusercontent.com/104471236/165485868-f039385a-d0c2-4b60-a92d-437e58b5d9a5.mov

**Comment by xXJamieXx** [comment]
Added this hairstyle to the list of toggleable options.
