### ISSUE TITLE
[BUG] Car Boosting 

### ISSUE THREAD

**Issue by dombpw** [xXJamieXx/paradox-bugs#43]
**Your Discord Name**
ruby#4567

**Describe the bug**
The individual who accepts the contract on the laptop ends up getting tracked, not the requested vehicle. I accepted the contract, went to the car and proceeded to lock pick it. At this point I have removed the laptop from my pockets and only have the gps scrambler. Once lock picked we scuffed out for a minute then the police arrived. We attempted to talk our way out but we realized it was going south so we asked for a pickup, and we ditched the requested car. After evading the police in our personal vehicles, we hid in a ditch in sandy, police randomly showed up so from there we assumed I was PERSONALLY being tracked. After then we broke eyes once again, got plenty of distance and I bailed from our personal car on foot. Climbing to the top of the crane completely unseen. After a few short minutes the officers were surrounding the base of the crane as they knew I was up there from the personal tracker. (When we first arrived to the requested car, I lock picked the vehicle and passed. It would not let me in though. So i had to re pick the lock two more times before it let ME, still would not let my passenger in.) Eventually we got two people in the car, was just a bit difficult.

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by JnKTechstuff** [comment]
Fixed: https://github.com/xXJamieXx/Paradox-3.0/commit/eaca289c9a837ad1bac3be4ea06b62fb7a2d9db4
