### ISSUE TITLE
[BUG] Gun Bench confiscating AR

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#430]
**Your Discord Name**
Owl Cherry

**Describe the bug**
Although i had not moved from the bench at all during the process, tyrone confiscated my weapon immediately without prompt to return the weapon.

**To Reproduce**
1. place ar on bench
2.  wait approx 5-10 min....
3.  was unable to get gun back. went from repairing to no weapon in your hands

**Expected behavior**
its expected to clean the weapon and then get it back when you have not moved away from the bench

**Screenshots**
https://i.imgur.com/DrGAimS.jpeg

**Logs**
[CitizenFX_log_2022-04-27T193448.log](https://github.com/xXJamieXx/paradox-bugs/files/8577679/CitizenFX_log_2022-04-27T193448.log)

**Comment by Sly-Panda** [comment]
Going to need a bit more info on this to figure out why it's happening. 

Where you on or off duty, which bench was it, does it only happen to CID or to all departments, was anyone else nearby that might have tried to use the bench, was the weapon completely broken or did it have a certain amount of durability .etc

**Comment by BigG5904** [comment]
This also happened to me while on duty. I went to the Davis PD. Placed my AR on the bench for Tyrone to clean. Never left the area. Didn’t have anything in the selected pocket. Waited for the original 15 minutes. Got the prompt my AR was finished. Went to pick it up from the bench and it was not there anymore.

**Comment by OwlCherry** [comment]
> Going to need a bit more info on this to figure out why it's happening.
> 
> Where you on or off duty, which bench was it, does it only happen to CID or to all departments, was anyone else nearby that might have tried to use the bench, was the weapon completely broken or did it have a certain amount of durability .etc

was all alone, no other person, indeed was on duty when this happened, and judging from next comment, happening to other departments as well

**Comment by BigG5904** [comment]
I was LSPD when it happened to me.

**Comment by Sly-Panda** [comment]
Should be fixed next update.
