### ISSUE TITLE
Car being messed up from Impound

### ISSUE THREAD

**Issue by itsqwertylol** [xXJamieXx/paradox-bugs#431]
Everytime I get my car out of the impound, no matter what even if I just fixed it and then my head popped so it went to the impound, all of my tires are popped and my orange check engine light thing is on. It is every single time.

**Comment by JnKTechstuff** [comment]
Please follow the giant thing you deleted because you thought it wasn't necessary. Also, did you ever put your car away? Did you consider this is where it saves that value?

Either way, invalid
