### ISSUE TITLE
[BUG] Hunting Error Notification

### ISSUE THREAD

**Issue by dingostolemename** [xXJamieXx/paradox-bugs#433]
**Your Discord Name**
dingostolemename#9763

**Describe the bug**
I sometimes be hunting and try place bait down and all of a sudden in the top right it goes ERROR. 
IDK if thats like a me thing or whatever. Quick fix is just taking a nap, but a lil later it starts happening again. Also happens when I try skin animals and stuff

**To Reproduce**
[Steps to reproduce the bug]
1. Buy Bait
2. Place Bait
3. Get ERROR code on top right

**Expected behavior**
An ERROR message will pop up on the right side of your screen

**Screenshots**
https://medal.tv/games/gta-v/clips/jdTHckLNe5Qrd/d133722Nl2tu?invite=cr-MSxIU1QsMTkwMzMzMDUs
[This was after I logged in and out]

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Do you have a log file because this should only happen when you're currently "busy". So it seems like you're spamming it too quickly or confusing it somehow whereas its not being allowed to return to the non-busy state.

**Comment by dingostolemename** [comment]
I dont think I was busy. I was waiting for an animal to come and decided to place a bait and it said that. Where can I find my log file?

**Comment by xXJamieXx** [comment]
FiveM Application Data > Logs and upload whichever one is the session in which it happened.

**Comment by dingostolemename** [comment]
[CitizenFX_log_2022-04-27T210757.log](https://github.com/xXJamieXx/paradox-bugs/files/8583018/CitizenFX_log_2022-04-27T210757.log)
[CitizenFX_log_2022-04-27T210107.log](https://github.com/xXJamieXx/paradox-bugs/files/8583019/CitizenFX_log_2022-04-27T210107.log)



Should be either one of these

**Comment by Sly-Panda** [comment]
This should be fixed now, would happen if your planting action was attempted a second time whilst planting OR if you were interrupted whilst planting.
