### ISSUE TITLE
[ENHANCEMENT] Garages at Boat docks

### ISSUE THREAD

**Issue by natashajoan** [xXJamieXx/paradox-bugs#434]
**Your Discord Name**
natasha_joan#7098

**Describe the annoyance**
I was wanting to go buy a boat and take it out at LSYMC Haven, but I realised once I arrived there was no parking for my vehicle. This means if I was to buy a boat, once I arrived back to dock my boat, I wouldn't have my vehicle due to it  de-spawning, which means I would either have to walk to impound or hope someone could pick me up. Which means I would still have to pay the new impound fees, which can be hefty. 

The only other way would be to park the vehicle at 378 parking, and walk to the LSYMC Haven.  I see this issue also being annoying for the other ports also. 

**To Reproduce**
[Steps to reproduce the annoyance]
1. Drive to LSYMC Haven (Or other boat docks) 
2. Swap to boat, leave the area, come back to no car
3. Start walking back to impound! 

**Requested behavior**
A garage be available at all the boat docks and Havens, so I don't have to worry about my vehicle on land being de-spawned.

**Comment by Sly-Panda** [comment]
Added to 4/5 of the fishing boat hiring spots (Including LSYMC).
