### ISSUE TITLE
[BUG] Race app installation not working

### ISSUE THREAD

**Issue by baxepw** [xXJamieXx/paradox-bugs#435]
**Your Discord Name**
baxe#0666

**Describe the bug**
When using the SD card to install race app on phone it does not do anything. It kicks you out of your pockets like its going to work but does not. Before just had to use the SD card and it would install on the phone you had.
**To Reproduce**
[Steps to reproduce the bug]
1. Get SD card and phone
2. Use SD card
3. Race app doesnt install

**Expected behavior**
When using the SD card the app should install as it used to.
**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[Add your FiveM logs]

**Comment by xXJamieXx** [comment]
Fixed next restart.
