### ISSUE TITLE
Impound not taking money correctly

### ISSUE THREAD

**Issue by BBstud44** [xXJamieXx/paradox-bugs#436]
BBstud27

Went to the impound to get my bike i had $350 in the bank it costs $375 to get my bike out. I went to go try to see if it would put me in debt but a message appeared saying you dont have enough money to purchase this yet it still spit me out on my bike and didnt take any money out of my account.

**To Reproduce**
1. go to impound
2. have less money than what it costs to get vehicle out of impound 
3. get car out of impound

**Expected behavior**
I expect to either go in debt after buying it or not be able get the vehicle out at all

**Comment by Sly-Panda** [comment]
Fixed next update
