### ISSUE TITLE
[BUG] Flying in bleeding out. Multiple Occurence.

### ISSUE THREAD

**Issue by tusktheshrew** [xXJamieXx/paradox-bugs#437]
**Your Discord Name**
#Shrew1219

**Describe the bug**
Flying in bleeding out from logging. Has happened multiple times, and have been found in multiple different areas. Sometimes wake up in areas I didn't even know about.

**To Reproduce**
[Steps to reproduce the bug]
1.  Log out
2.  Log In
3.  Bleeding from character selection screen.

**Expected behavior**
Being fine if not already bleeding before the log out.

**Screenshots**

**Logs**
[Add your FiveM logs]
![Log1](https://user-images.githubusercontent.com/98053772/166167621-c34837f0-35aa-4df9-973f-bfb691a8860b.PNG)
![Log2](https://user-images.githubusercontent.com/98053772/166167625-6ae7388f-8318-45f6-b25b-020470a695e6.png)

[CitizenFX_log_2022-05-02T011318.log](https://github.com/xXJamieXx/paradox-bugs/files/8600702/CitizenFX_log_2022-05-02T011318.log)

**Comment by Sly-Panda** [comment]
Can you attach your log files from the F8 Console.  The little open log button in the bottom right 
![image](https://user-images.githubusercontent.com/43046128/166181418-b2bf9f17-ffaf-4764-83cb-0367a903165a.png)

**Comment by tusktheshrew** [comment]
Added log.

**Comment by tusktheshrew** [comment]
Has happened today again, nothing running in the background. Happened after a headpop

**Comment by Sly-Panda** [comment]
There's an update pending, whenever we push it it should hopefully fix your issue.

**Comment by Sly-Panda** [comment]
Are you still experiencing this after last nights update?

**Comment by tusktheshrew** [comment]
I have not experienced the bleeding out yet after the last update so far.

**Comment by Sly-Panda** [comment]
> Ref

Sweet, I'll leave this open for a bit just in case it does happen again but hopefully we've finally squashed this one.

**Comment by tusktheshrew** [comment]
Happened Again today flying back in.

**Comment by JnKTechstuff** [comment]
Fixed: https://github.com/xXJamieXx/Paradox-3.0/commit/43f7be12d66b750804cc67c743a59aa7b53f5d11
