### ISSUE TITLE
[ENHANCEMENT] Completed Garbage Runs

### ISSUE THREAD

**Issue by BrotherDayZ** [xXJamieXx/paradox-bugs#438]
**Your Discord Name**
BDZ#0001

**Describe the annoyance**
When completing a garbage run, you get 2 options as you normally would. 1. Start a garbage run, 2. Collect Payslip. When completing a run, if you accidentally click the first option you wont get paid for the run you just completed. 
**To Reproduce**
[Steps to reproduce the annoyance]
1. Finish garbage run
2. Accidentally click start new work
3. Wont get paid for previous work

**Requested behavior**
Would be beneficial to have a prompt recognize you already have a garbage truck out if you accidentally click the first option.

**Comment by Sly-Panda** [comment]
Will be fixed in the next update to prevent you starting a new job if one is active and you have a pending payslip
