### ISSUE TITLE
[BUG] Cleaning Kit does not repair gun 

### ISSUE THREAD

**Issue by Vsolon** [xXJamieXx/paradox-bugs#439]
**Your Discord Name**
Vsolon#1699

**Describe the bug**
When I used my cleaning kit on a gun, it used up the cleaning kit and did not repair the gun itself.

**To Reproduce**
[Steps to reproduce the bug]
1.  Take out the gun
2.  Use the cleaning kit 

**Expected behavior**
[A clear and concise description of what you expected to happen]
The gun should be repaired 

**Screenshots**
[If applicable, add screenshots to help explain your problem]
https://medal.tv/games/gta-v/clips/jOBlF9qGEqJmV/LXq7yTs97Gag?invite=cr-MSx4MEgsNjQwMDU4OTks

**Logs**
[Add your FiveM logs]
[CitizenFX_log_2022-05-03T011742.log](https://github.com/xXJamieXx/paradox-bugs/files/8608467/CitizenFX_log_2022-05-03T011742.log)

**Comment by Sly-Panda** [comment]
Looking like you started the repair before the gun was fully in your hand, make sure you are giving it a second to be fully in your hands before trying to clean it.
