### ISSUE TITLE
[BUG] House robbery 

### ISSUE THREAD

**Issue by Terrylaughlin35** [xXJamieXx/paradox-bugs#44]
**Your Discord Name**
Terry Laughlin

**Describe the bug**
When you rob a house a police vest gets put on you.

**To Reproduce**
[Steps to reproduce the bug]
1. Rob house
2. 
3. 

**Expected behavior**
To not have clothes change when I enter a house

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by JnKTechstuff** [comment]
Fixed https://github.com/xXJamieXx/Paradox-3.0/commit/499f8de538ab432f63c006a450ad0d2801cc455b
