### ISSUE TITLE
Impound Issue

### ISSUE THREAD

**Issue by JeremyJohnsonn** [xXJamieXx/paradox-bugs#440]
[McFlicks#1444]

**Describe the bug**
My one of one Weazel News van was "scuff impounded" by an LEO and caused an issue for my character to not be able to use the impound. 

**To Reproduce**

1. Impound a one of one Weazel News van
2. Attempt to pull it out of impound

**Expected behavior**
I expected to be able to pull my van out of the impound. After the van was impounded I was never able to use the impound again. I currently have 2 of my main cars stuck in the impound because of this. I assume it has something to do with the one of one Weazel News van because this issue has never occurred before until the van was first impounded ever. I hope this can be resolved. Thank you.

**Screenshots**
https://user-images.githubusercontent.com/104825220/166424207-5f1009df-bc59-497a-aaae-8d3258de7d39.mp4

**Logs**
[CitizenFX_log_2022-05-02T061833 (Weazel Van issue).txt](https://github.com/xXJamieXx/paradox-bugs/files/8609241/CitizenFX_log_2022-05-02T061833.Weazel.Van.issue.txt)

**Comment by JeremyJohnsonn** [comment]
This is the van that I am referring to : 

![Weazel Van](https://user-images.githubusercontent.com/104825220/166427638-20bbc0c2-accc-4c09-95f6-c36f5649c9e1.jpg)

Thank you!

**Comment by Sly-Panda** [comment]
Fixed next update

**Comment by JeremyJohnsonn** [comment]
Thank you!!
