### ISSUE TITLE
[BUG] Motorcycle Wheels options MIA in LS Customs

### ISSUE THREAD

**Issue by drewskeattle** [xXJamieXx/paradox-bugs#442]
Your Discord Name
Drewskeattle#6011

Describe the bug
When at the Customs shop trying to buy new wheels for my motorcycle the normal front/back wheel options aren't available. It's the normal layout for regular automobiles.

To Reproduce
[Steps to reproduce the bug]
1. Enter LS Customs on Motorcycle
2. Open Customs options
3. Go to "Wheels" section
4. Notice the regular options aren't there

Expected behavior
I expect to be able to have options for the front and rear wheels of my motorcycle. Which are completely unique to the bikes, not the regular automobile variety.

Screenshots

![20220504131909_1](https://user-images.githubusercontent.com/103740998/166819553-d4c5bcdd-022d-492a-915d-fcbcde748da4.jpg)
![20220504131916_1](https://user-images.githubusercontent.com/103740998/166819560-f3d1bfe7-e8c6-42ad-86bd-7fc23b9d6812.jpg)
![20220504131857_1](https://user-images.githubusercontent.com/103740998/166819564-5594da9c-d712-429d-8ade-8bde12208687.jpg)

**Comment by Sly-Panda** [comment]
Works fine on any bikes i've tested it on, that bike might just not have wheel customization options.  Which bike was it?  
![image](https://user-images.githubusercontent.com/43046128/166851976-a6780933-b100-4c70-b181-d4f7d0037837.png)
