### ISSUE TITLE
[BUG] Unable To Store Personal CVPI In Garages

### ISSUE THREAD

**Issue by SaintSeven31** [xXJamieXx/paradox-bugs#443]
**Your Discord Name**
Seven#3131

**Describe the bug**
I have a personal LSPD CVPI and am unable to park it in the garage section of the MRPD motorpool, or any other garage for that matter.  I get a "You can't store this type of vehicle here" error message when I attempt to park it.

**To Reproduce**
[Steps to reproduce the bug]
1. Get in personally owned CVPI
2. Attempt to park in motorpool/garage
3. Sadness and an impound fee every shift

**Expected behavior**
[I expect to be able to store my personal CVPI in the motorpool or any garage]

**Screenshots**
[https://i.imgur.com/AeeJqKP.jpeg]

**Logs**
[No Logs]

**Comment by Sly-Panda** [comment]
Fixed for the next update.
