### ISSUE TITLE
[BUG] Not Earning Paycheck

### ISSUE THREAD

**Issue by tusktheshrew** [xXJamieXx/paradox-bugs#444]
**Your Discord Name**
Shrew#1219

**Describe the bug**
Paycheck is not coming onto the screen and playing for hours, received nothing for welfare.

**To Reproduce**
[Steps to reproduce the bug]
1.  Play for a long time
2.  Collect Paycheck at bank
3.  $0 collected

**Expected behavior**
Earning the normal paycheck per job.

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Logs**
[CitizenFX_log_2022-05-04T214823.log](https://github.com/xXJamieXx/paradox-bugs/files/8628458/CitizenFX_log_2022-05-04T214823.log)

**Comment by BigG5904** [comment]
PD is having the same issue. I didn't get paid for last night or the night before.

https://i.imgur.com/88L5IPV.jpeg

**Comment by Sly-Panda** [comment]
This should be fixed, is anyone still having issues with it?

**Comment by Weebait** [comment]
Fixed
