### ISSUE TITLE
[BUG] Boat Rental Spawn Location

### ISSUE THREAD

**Issue by dave1880** [xXJamieXx/paradox-bugs#445]
**Your Discord Name**
dave1#1884

**Describe the bug**
If you rent a boat at the NPC at 401 you will be spawned with the boat in the Alamo sea. 

**To Reproduce**
[Steps to reproduce the bug]
1. Go to 401 at the dam
2. rent a boat from the NPC

**Expected behaviour**
To be spawned at the Lake at 401 with the boat.

**Screenshots**
https://medal.tv/games/gta-v/clips/kbG6Vgr3A1u2K/d1337PixIzBd?invite=cr-MSxnbnEsNDc3MTczNjAs

**Logs**
N/A

**Comment by Sly-Panda** [comment]
Already fixed for the next update
