### ISSUE TITLE
[BUG] Rental boats with the same ID share trunks space

### ISSUE THREAD

**Issue by mjb328** [xXJamieXx/paradox-bugs#446]
### Your Discord Name

MJB328#5303

### A clear and concise description of what the bug is

Rental boats with the same ID have shared trunks. Rented a boat, filled with it with fish. then friend renter a boat with the same ID and was able take all my fish in my boat from his boats trunks.

### Steps to Reproduce the Bug

1.Rent 2 boats with the same ID at same time.
2.Put any item in boat As trunk. 
3.Then take them out of Boat Bs trunk
4. Look in boat As trunk again. Whatever item that was taken While boat in B's trunk should be gone from Boat As trunk.

### Expected Behavior

Don't expect rental boats to have shared trunk space allow random strangers to steal from you potentially.

### Screenshots/Videos

no screenshots or video. will add some later if possible

### Log File

No logs, forgot to save some from last night sorry. After reset today ill try and replicate it so I can get in on them.

**Comment by Sly-Panda** [comment]
Will be fixed the next time we push an update.
