### ISSUE TITLE
[BUG] Stretcher lockpick you get into the nearest car

### ISSUE THREAD

**Issue by Terrylaughlin35** [xXJamieXx/paradox-bugs#447]
### Your Discord Name

Terry Laughlin#3143

### A clear and concise description of what the bug is

I was lockpicking a stretcher just trying to see what happened and they removed it while I was lockpicking it. once I finished the lockpick onto the Stretcher. I got into the nearest car which happened to be a locked ambulance. 

### Steps to Reproduce the Bug

1. Lockpick a stretcher
2. remove stretcher while lockpicking it
3. get into nearest car after lockpick is finished

### Expected Behavior

Just for the lockpick to finish and i still stand there with nothing happening.

### Screenshots/Videos

N/A

### Log File

![image](https://user-images.githubusercontent.com/97036023/167271048-7a23eb36-0b93-417c-89fa-076c337be3eb.png)

**Comment by Sly-Panda** [comment]
That's just how lock picking works, will put you into the nearest vehicle.

Stretchers are only vehicles because they have to be, probably should not be picking/attempting to drive them.
