### ISSUE TITLE
[BUG] Logging in and starting in apt, leaving apt, cannot reenter without having to pay to move there

### ISSUE THREAD

**Issue by madsskyy** [xXJamieXx/paradox-bugs#448]
### Your Discord Name

madsskyy#2165

### A clear and concise description of what the bug is

This doesn't happen every time, but it happens a decent amount. I will fly into the city and spawn in my apartment, and when I leave the apartment, I cannot reenter without spending money to move there again. 

### Steps to Reproduce the Bug

1. Fly into city and spawn in apartment
2. Leave apartment
3. Try to reenter apartment

### Expected Behavior

It will ask you to move to apartment for $500

### Screenshots/Videos

![FiveM® by Cfx re - Paradox Gaming RP _ 3+ years _ discord gg_paradoxgaming 5_7_2022 10_49_38 PM](https://user-images.githubusercontent.com/103598492/167279619-42bf9b10-2c41-4db1-9886-c12c8df39c21.png)

### Extra Notes (Optional)

It can be solved by flying out and flying back in most of the time. 

### Log File

[CitizenFX_log_2022-05-07T230335.log](https://github.com/xXJamieXx/paradox-bugs/files/8646261/CitizenFX_log_2022-05-07T230335.log)
[CitizenFX_log_2022-05-08T021157.log](https://github.com/xXJamieXx/paradox-bugs/files/8646262/CitizenFX_log_2022-05-08T021157.log)

**Comment by Sly-Panda** [comment]
You won't actually be charged right now if you hit the Move Here option, but walking away and back usually updates it to correctly display that it is yours, so purely a visual bug.

We'll get this looked into though.

**Comment by Sly-Panda** [comment]
This should be fixed
