### ISSUE TITLE
[BUG] Fertilzers in Farming Do Not Break.

### ISSUE THREAD

**Issue by tusktheshrew** [xXJamieXx/paradox-bugs#449]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

Tested with a few farming runs, and noticed that the fertilizers tick down to the bottom for their usage. But then At their bottom they do not break and still in the inventory.

### Steps to Reproduce the Bug

1. Farming
2. Get Fertilizer to bottom of its use

### Expected Behavior

The Fertilizer breaks and leaves your inventory space.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98053772/167302089-fb42e5cb-6678-4633-9e71-ee93b3ecdd20.png)

### Log File

[FarmingFertilizerBug.txt](https://github.com/xXJamieXx/paradox-bugs/files/8647192/FarmingFertilizerBug.txt)

**Comment by TeddyNM** [comment]
Came here to post about this bug. Did 5 plantings of 9 plants each and used 1 fertilizer and it's still going strong.

**Comment by Sly-Panda** [comment]
Fixed next update
