### ISSUE TITLE
[CLICK FOR WORKAROUND] [BUG] Most ATM's do not work with NVE installed

### ISSUE THREAD

**Issue by xXJamieXx** [xXJamieXx/paradox-bugs#45]
**Your Discord Name**
xXJamie_Xx#7669

**Describe the bug**
When attempting to use the third eye with most of the ATM models while having NVE installed (specifically the `s_NVE_ATM_Animation.rpf` addon), you will be unable to access the ATM screen.

**To Reproduce**
1. Install NVE
2. Use third eye to target ATM
3. Fail to access ATM

**Expected behavior**
Should be able to access the ATM regardless.

**Comment by xXJamieXx** [comment]
As a workaround until the issue can be resolved, you should remove the following addon:
https://i.imgur.com/1IxyisH.png

Then your ATMs will work.

**Comment by JnKTechstuff** [comment]
This is getting closed as we are unable to fix and the fix is now well known
