### ISSUE TITLE
New fish icebox top row ids as belt quick slots.

### ISSUE THREAD

**Issue by mjb328** [xXJamieXx/paradox-bugs#450]
### Your Discord Name

MJB328#5303

### A clear and concise description of what the bug is

With the recent changes to fishing ice box any fish put in the top row of the ice box is recognized as an item in you quick slots and kicks you out of the icebox forcing you either leave all but one quick slot empty or not use the entire top row in the ice box.

### Steps to Reproduce the Bug

1.buy new ice box
2. fill all quick slot with items not allowed in ice box
3. try moving any fish from slot 1-5 of the top row in the ice box to any other space
4. game recognizes any fish in icebox in any of the top slot as the item on you quick belt slot and forces you out.

### Expected Behavior

to be able to organize without it repeatedly forcing you out out of it.

### Screenshots/Videos

I have video but its too big for github 

And this is all the logs show since i got on and tried moving stuff around.
![FiveM® by Cfx re - Paradox Gaming RP _ 3+ years _ discord gg_paradoxgaming 5_8_2022 10_35_03 PM](https://user-images.githubusercontent.com/103229041/167331099-c4e73a54-ff45-4c0f-bff4-6c16d3adcac0.png)

**Comment by Sly-Panda** [comment]
I'll see about a workaround to prevent it kicking you out, in the meantime I'd just organise them in your inventory as and where you can.  You can stack the regular fish in there already so the need to organize it should be minimal.

**Comment by Sly-Panda** [comment]
Fix should roll out with the next update push.

**Comment by mjb328** [comment]
Ty

**Comment by Sly-Panda** [comment]
Should be fixed now on live.
