### ISSUE TITLE
[BUG] Tackle Box Disappears When Found

### ISSUE THREAD

**Issue by Weebait** [xXJamieXx/paradox-bugs#451]
### Your Discord Name

Weeb#5266

### A clear and concise description of what the bug is

When fishing I have received the notification that I've found a tackle box twice but when I check my inventory it is nowhere to be found

### Steps to Reproduce the Bug

Fish
Receive Chest
Open Chest
See that you received tackle box but don't acquire it

### Expected Behavior

To receive the item when I acquire it

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/ksoryonqQx4yU/d1337XdB86Rd?invite=cr-MSwzbm0sNjQwMDIyMjQs

### Log File

[CitizenFX_log_2022-05-09T041439.log](https://github.com/xXJamieXx/paradox-bugs/files/8649768/CitizenFX_log_2022-05-09T041439.log)

**Comment by Sly-Panda** [comment]
From your video you are overwriting the tackle box with plastic as it goes into your first available slot (which you overwrite when you right click the plastic). 

Will be fixed next time an update rolls out.
