### ISSUE TITLE
[BUG] Face Losing Alterations On Load In Or Outfit Change

### ISSUE THREAD

**Issue by jibbersh** [xXJamieXx/paradox-bugs#452]
### Your Discord Name

Jibberish#2741

### A clear and concise description of what the bug is

There is a random chance that when you load in your character that you've loaded in will retain the face shape, but lose any customizations effectively making it a danny-esque face. This can also happen when changing outfits. Hair, Face One, Face Two, skin mix, and face mix all stay the same - but makeup, eyebrows, and all other sliders are reset. 

After the character has lost customization, I have not been able to find a way to restore it without having to readjust all the sliders manually.

### Steps to Reproduce the Bug

1. Load into the server
2. Character has lost customization

or

1. Load into the server
2. Character is untouched
3. Change outfits
4. Character loses customization

### Expected Behavior

Character to not lose their appearance or customization.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/96938099/167392394-6eb289fd-1156-47a4-bbd0-63ff40d46488.png)

### Extra Notes (Optional)

Screenshot is of the character after being reset, will attempt to get a video of it happening.

### Log File

[CitizenFX_log_2022-05-09T100648.log](https://github.com/xXJamieXx/paradox-bugs/files/8650871/CitizenFX_log_2022-05-09T100648.log)

**Comment by Sly-Panda** [comment]
Is anyone still experiencing this?
