### ISSUE TITLE
[BUG] Unable to park by Bikini Tow HQ

### ISSUE THREAD

**Issue by curtdavies621** [xXJamieXx/paradox-bugs#453]
### Your Discord Name

MK Wraith#4267

### A clear and concise description of what the bug is

When I go to park outside of Bikini Tow, the "Park" button will not pop up in my F1 menu.

### Steps to Reproduce the Bug

1. Check in for Bikini Tow (become empolyed).
2. Try and park your personal vehicle in the car park.

### Expected Behavior

For some people such as myself, the "park" option won't appear.

### Screenshots/Videos

![unknown](https://user-images.githubusercontent.com/105245187/167492080-d4e8f642-e369-4bf3-abcc-60237e08c596.png)

### Log File

I don't have a logs folder in that location sorry. Or anywhere else for that matter.

**Comment by Sly-Panda** [comment]
Tested and it's working fine on live as long as you are clocked on as tow.  To get logs press F8 after trying to park, click Open Logs and then save the text document and drag it in here.

**Comment by curtdavies621** [comment]
[CitizenFX_log_2022-05-11T210124.log](https://github.com/xXJamieXx/paradox-bugs/files/8673469/CitizenFX_log_2022-05-11T210124.log)

Thanks for the info, here's the log. Still not working for me...

**Comment by Sly-Panda** [comment]
Can you post a video of what you are doing?

**Comment by Darahz** [comment]
https://user-images.githubusercontent.com/35222814/168486592-b316bcd1-4054-496c-aaf7-75a374a0a52b.mp4

Here is a video showing off the bug.

**Comment by Sly-Panda** [comment]
Ah, your car is just too low down, i'll lower the collider for that sorta car.

**Comment by Sly-Panda** [comment]
Fixed next update.

**Comment by Darahz** [comment]
> 

Thank you so much!
