### ISSUE TITLE
[BUG] Telescope Unusable 

### ISSUE THREAD

**Issue by tusktheshrew** [xXJamieXx/paradox-bugs#455]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

Use of the telescopes on the piers is unusable. You may third eye the telescope but nothing happens.

### Steps to Reproduce the Bug

1. Go to telescope
2. Use third eye interaction on telescope
3. Wait for work [never happens]

### Expected Behavior

To be able to peer through telescope in a better vision out in the looking space.

### Screenshots/Videos

N/A currently

**Comment by xXJamieXx** [comment]
This was fixed
