### ISSUE TITLE
[BUG] shots fired are not registering at all for dispatch

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#456]
### Your Discord Name

OwlCherry#6969

### A clear and concise description of what the bug is

since the update, officers haven't been getting notified of 10-13's anywhere in the city. 

### Steps to Reproduce the Bug

1. shoot a weapon 
2. do not recieve a shots fired call

### Expected Behavior

you should recieve the shots fired call for the first shot and on some shots after depending on timing

### Screenshots/Videos

have no screenshots for this.

### Log File

[CitizenFX_log_2022-05-11T050758.log](https://github.com/xXJamieXx/paradox-bugs/files/8671605/CitizenFX_log_2022-05-11T050758.log)
[CitizenFX_log_2022-05-11T053144.log](https://github.com/xXJamieXx/paradox-bugs/files/8671606/CitizenFX_log_2022-05-11T053144.log)
[CitizenFX_log_2022-05-11T152241.log](https://github.com/xXJamieXx/paradox-bugs/files/8671607/CitizenFX_log_2022-05-11T152241.log)
[CitizenFX_log_2022-05-11T040350.log](https://github.com/xXJamieXx/paradox-bugs/files/8671608/CitizenFX_log_2022-05-11T040350.log)
[CitizenFX_log_2022-05-11T043421.log](https://github.com/xXJamieXx/paradox-bugs/files/8671609/CitizenFX_log_2022-05-11T043421.log)

**Comment by Sly-Panda** [comment]
This has been fixed.
