### ISSUE TITLE
[BUG] <Music playing by tunnel, between lumberyard and and chiliad mountain>

### ISSUE THREAD

**Issue by ItzBlackStar** [xXJamieXx/paradox-bugs#457]
### Your Discord Name

Sadistic Dane#1413

### A clear and concise description of what the bug is

I can only assume its requested music being played in a remote location by a drain.
better if you look at the pictures I attach. basicly while next to the drain/tunnel, im hearing music. specifically doja cat xD

### Steps to Reproduce the Bug

1. go to the spot
2. (I assume request music)
3. listen to the music

### Expected Behavior

just not to be able to listen to the music.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/18250904/167967243-008b8352-4ac1-45aa-ac7b-2fed9b4c6998.png)
![image](https://user-images.githubusercontent.com/18250904/167967355-b5944ab4-13c1-44c4-a205-0277a580eb75.png)
![image](https://user-images.githubusercontent.com/18250904/167967382-0c918a0d-255e-424a-bccb-f7654fdcb067.png)

### Extra Notes (Optional)

its nice to listen to music here... just not suppose to be here.

### Log File

[CitizenFX_log_2022-05-11T215726.log](https://github.com/xXJamieXx/paradox-bugs/files/8674087/CitizenFX_log_2022-05-11T215726.log)

**Comment by Sly-Panda** [comment]
Have gone to the spot and not been able to hear anything from it/reproduce this issue.  Are you sure the music was coming from FiveM?

**Comment by ItzBlackStar** [comment]
100% it was coming from FiveM, I checked my sounds and everything. I havnt been able to reproduce it either, but im also new to paradox. I thought it was a requested song somehow, I just remember it being 2 doja cat songs, and it would play when only in that spot. 
If I hear a song there again ill record it and post a link.

**Comment by Sly-Panda** [comment]
> 100% it was coming from FiveM, I checked my sounds and everything. I havnt been able to reproduce it either, but im also new to paradox. I thought it was a requested song somehow, I just remember it being 2 doja cat songs, and it would play when only in that spot. If I hear a song there again ill record it and post a link.

Sounds good, i'll go ahead and close this, should it happen again feel free to open up a new report.
