### ISSUE TITLE
Multicharacter incompatible on ultra wide screen

### ISSUE THREAD

**Issue by Adrianmcmastergaming** [xXJamieXx/paradox-bugs#458]
### Your Discord Name

Adrianmcmastergaming#2554

### A clear and concise description of what the bug is

I have a ultra wide monitor and the enter button is missing so had to set my graphics to 1920x1080 to be able to see it. A support person help me but had a ultra wide monitor also. The coding needs changing so folks with a ultra wide monitor can see. ultra-wide

### Steps to Reproduce the Bug

The coding needs changing so folks with a ultra wide monitor can see. 
had to set my graphics to 1920x1080 

### Expected Behavior

s

### Screenshots/Videos

![Untitled](https://user-images.githubusercontent.com/76175523/167970349-ce29e2f9-df14-49c0-8529-f9d1f7bf8019.png)

### Extra Notes (Optional)

s

### Log File

[CitizenFX_log_2022-05-12T001105.log](https://github.com/xXJamieXx/paradox-bugs/files/8674231/CitizenFX_log_2022-05-12T001105.log)

**Comment by Sly-Panda** [comment]
It's very unlikely we're going to change things for crazy wide-screen resolutions.  Works fine on most resolutions up to 4k.  Anything beyond that is niche.
