### ISSUE TITLE
[BUG] outfits saved to the last thing i was in

### ISSUE THREAD

**Issue by Dez505** [xXJamieXx/paradox-bugs#46]
**Your Discord Name**
[SuperD 505#1060]

**Describe the bug**
[outfits saved to the last thing i was in
https://medal.tv/games/gta-v/clips/6NVB0tmq3EDxU/d1337Cw06qia?invite=cr-MSxPTUIsMzQ3OTM3MTAs]

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by JnKTechstuff** [comment]
No replication steps and unable to replicate
