### ISSUE TITLE
[BUG] E muscle doesn't work loading in the Apartment

### ISSUE THREAD

**Issue by tusktheshrew** [xXJamieXx/paradox-bugs#461]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

When flying in, can not use  the trunk, leave the apartment, or wardrobe, or log out into the character selection

### Steps to Reproduce the Bug

1. Fly into apartment
2. Try to leave
3. try to open stash
4. try to open wardrobe
5. try to logout through the apartment

### Expected Behavior

Be able to use the E muscle for apartment.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98053772/168329550-0cb5936b-00ba-48a7-a58a-584a32844d20.png)
![image](https://user-images.githubusercontent.com/98053772/168329703-4bb859e5-d9bc-419d-b5ed-673430488b47.png)
![image](https://user-images.githubusercontent.com/98053772/168329769-84d687ae-3f5b-414c-8d87-fae6f7336730.png)
![image](https://user-images.githubusercontent.com/98053772/168329814-4959e1d7-6d31-4a59-893e-97610211c47a.png)

### Log File

[ApartmentTest.txt](https://github.com/xXJamieXx/paradox-bugs/files/8689508/ApartmentTest.txt)

**Comment by JnKTechstuff** [comment]
Fixed: https://github.com/xXJamieXx/Paradox-3.0/commit/0ee38c9327b675a5fda1be40a60c17ab65827103
