### ISSUE TITLE
[BUG] Cars getting damaged when pulling them from the garage

### ISSUE THREAD

**Issue by BBstud44** [xXJamieXx/paradox-bugs#462]
### Your Discord Name

BBstud27#5956

### A clear and concise description of what the bug is

when i go to any garage and pull put a car/truck/motorcycle they will sometimes lose objects on them (hood, tires, windows, doors). this doesnt happen every single time but it happens more often than it should.

### Steps to Reproduce the Bug

Put car in garage 
Take car out 
windows shatter, door falls, off tires will pop. 

### Expected Behavior

I expect my car to come out of the garage the way i put it into the garage

### Screenshots/Videos

NA

### Extra Notes (Optional)

Everything that happens doesnt always happen sometimes only one thing will happen sometimes all of it will happen its very random.

**Comment by GFaustini** [comment]
That also happens with me sometimes

**Comment by AkaBlackX** [comment]
same here, pretty annoying to have to keep repairing my car over and over.

**Comment by Sly-Panda** [comment]
This happens if the car has damage beyond a certain amount when you store it.  The status damage amounts should display on the menu when you go to pull out the car.

Are there any instances of it saying the car is not damaged and still pulling it out with damage?
