### ISSUE TITLE
[BUG] Police Battering ram doesnt work

### ISSUE THREAD

**Issue by pulsevr34** [xXJamieXx/paradox-bugs#465]
### Your Discord Name

Pulse+#5769

### A clear and concise description of what the bug is

When arriving on a house robbery, when we try to use the police enforcer/battering ram it doesnt work. By doesnt work I mean when we use it it says "Used" in our Hotbar thing, and nothing happens.

### Steps to Reproduce the Bug

1. Obtain Enforcer
2. Arrive on house robbery call
3. Use enforcer on door of hosue
4. Bada bing bada boom

### Expected Behavior

Be able to use the battering ram to enter robbed houses

### Screenshots/Videos

N/A

### Log File

Haven't encountered a robbery yet, this will be updated when I do.

**Comment by pulsevr34** [comment]
[CitizenFX_log_2022-05-15T200255.log](https://github.com/xXJamieXx/paradox-bugs/files/8695947/CitizenFX_log_2022-05-15T200255.log)
heres the logs

**Comment by xXJamieXx** [comment]
Fixed next restart.
