### ISSUE TITLE
[ENHANCEMENT] Adding a Prison Stash

### ISSUE THREAD

**Issue by Weebait** [xXJamieXx/paradox-bugs#467]
**Your Discord Name**
Weeb#5266

**Describe the annoyance**
As of right now there's no way to carry over progress within prison especially since you need to do multiple jobs for most things while some of the items are very rare and require you to work the same job many times

**Requested behavior**
As planned add some form of stash that can be kept between going to and leaving prison

**Comment by xXJamieXx** [comment]
Added next restart.
