### ISSUE TITLE
[BUG] Stuck In Lock Picking Animation 

### ISSUE THREAD

**Issue by Vsolon** [xXJamieXx/paradox-bugs#468]
### Your Discord Name

Vsolon#1699

### A clear and concise description of what the bug is

After locking picking a car and succeeding, lock picking does not stop. I will get in the car and still be lock picking, I'll drive the car and still be lock picking, I'll have left the car and still be lock picking.  I used an Advanced Lockpick when it happened to me 

### Steps to Reproduce the Bug

1. Lock Pick a car 

### Expected Behavior

Car is unlocked upon succeeding, animations and sounds stop playing 

### Screenshots/Videos

https://www.youtube.com/watch?v=FGKfWvO6NYQ

**Comment by xXJamieXx** [comment]
Fixed next restart.
