### ISSUE TITLE
[ENHANCEMENT] Sandy PD garage unlocking/locking garage doors

### ISSUE THREAD

**Issue by andythewookie** [xXJamieXx/paradox-bugs#47]
**Your Discord Name**
[andythewooke#0798]

**Describe the annoyance**
[Using garage door locks, forces you into the repair station, this was experienced on garage door closest to repair point and became a hinderance to trying to leave the garage]

**To Reproduce**
[Steps to reproduce the annoyance]
1. sit in vehicles
2. attempt to use "E" to function locking and unlocking
3. 

**Requested behavior**
[Smalled register area for the repair function inside on Sandy PD garages]

**Screenshots**
https://i.imgur.com/vKlPKbp.jpeg    /     https://i.imgur.com/ywF29oz.jpeg

**Additional context**
[Add any other context about the enhancement here]

**Comment by JnKTechstuff** [comment]
Fixed: https://github.com/xXJamieXx/Paradox-3.0/commit/1f3fdb6dbd7e7d0d3b4d5493ae793ac7eac4f4d8
