### ISSUE TITLE
[BUG] glovebox broke in my car and lost my gun

### ISSUE THREAD

**Issue by JarneEveraerts** [xXJamieXx/paradox-bugs#470]
### Your Discord Name

Den Dikken#1114

### A clear and concise description of what the bug is

i tried to take my gun out of my glovebox while driving on the interstate alone
but when i tried to use the gun after it wasnt in my front pockets i checked my glovebox again just to see a empty glovebox with no storage spots visible

### Steps to Reproduce the Bug

get in car
dubble pres tab
move item
esc

### Expected Behavior

to get my gun out of the glovebox

### Screenshots/Videos

i dont have any clips but the car is still broken
[
![image](https://user-images.githubusercontent.com/91672463/169385941-43844a68-708b-4fe1-aa38-e5dfbb9201d6.png)
](url)

### Extra Notes (Optional)

if screenshot doesnt work give me a pm

### Log File

[CitizenFX_log_2022-05-19T184328.log](https://github.com/xXJamieXx/paradox-bugs/files/8733670/CitizenFX_log_2022-05-19T184328.log)

**Comment by Sly-Panda** [comment]
This happens if you try and open the Glove Box (or any inventory) twice in quick succession.  A relog/restart should make the glove box accessible again.
