### ISSUE TITLE
[BUG] Storage Deletion Issue

### ISSUE THREAD

**Issue by Nicklmfao** [xXJamieXx/paradox-bugs#471]
### Your Discord Name

Nicklol#2510

### A clear and concise description of what the bug is

But basically, I was clearing my register tills before I opened up the 10-42. I didn't know the receipts could not stack at the time. I went into my storage, having one receipt in my pockets and one receipt in my business storage behind the bar. When I went to move the receipt into the storage on top of it, I got two error messages, and then went to move it to the bottom which it allowed. I double checked my pockets to make sure it went through and then when I checked my business storage it deleted the item that was in my slot for my inventory but not deleting either receipt. 

I was able to replicate it back to back with one losing 17x Waterhose the first time and 1x Butter the second time, when I was just testing if I could replicate it to see if it was something on my end or not. 

### Steps to Reproduce the Bug

1. Open any storage, in my case it was my business storage behind the bar.
2. Attempt to stack what I presume is a unstack-able item, I didn't know this at the time that the receipts were not stackable.
3. Once you do the second step, the spot where the item was in YOUR inventory will replace the exact slot in the storage you are attempting to put it in. The item it replaces will poof, deleting it essentially. 

### Expected Behavior

When moving items that item to not be deleted and just moved to another spot that is free.

### Screenshots/Videos

https://medal.tv/games/requested/clips/lBNzBE8Thdm_w/d1337xSOurmM?invite=cr-MSxSZkcsNjE0ODk2NDks

### Log File

[F8 Log.txt](https://github.com/xXJamieXx/paradox-bugs/files/8744668/F8.Log.txt)

**Comment by xXJamieXx** [comment]
Fixed next restart.
