### ISSUE TITLE
[BUG] Unable to craft jewelry

### ISSUE THREAD

**Issue by Kromlec** [xXJamieXx/paradox-bugs#472]
### Your Discord Name

Kromelc#3389

### A clear and concise description of what the bug is

When attempting to craft jewelry at the anvil it just tells you that you don't have the correct tools, Talked with Sly and he says this is a bug and even with the new update it is not working as it is supposed to be.

### Steps to Reproduce the Bug

1. Attempt to use anvil and craft any jewelry.

### Expected Behavior

Craft said jewelry.

### Screenshots/Videos

https://i.imgur.com/MiibBEL.png

### Log File

[CitizenFX_log_2022-05-20T205919.log](https://github.com/xXJamieXx/paradox-bugs/files/8744701/CitizenFX_log_2022-05-20T205919.log)

**Comment by Sly-Panda** [comment]
Should be fixed next update.
