### ISSUE TITLE
[ENHANCEMENT] Imorgan Fix

### ISSUE THREAD

**Issue by Weebait** [xXJamieXx/paradox-bugs#473]
**Your Discord Name**
Weeb#5266

**Describe the annoyance**
Imorgan along with the chameleon, the neon, and the raiden is an electric car and one of the features that comes with electric cars is being able to drive backwards at the same speed as forwards though Imorgan is unique in the fact that it can't achieve that and locks up at 40 just like every non electric car.

**Requested behavior**
The Imorgon to act like every other electric and back up at the same speed as it can go forward

**Comment by Sly-Panda** [comment]
Imorgon is a hybrid (You can tell when it gets up to higher speeds and the ICE (Internal combustion engine) kicks in, as such it's max reverse speed is dictated by that ICE.
