### ISSUE TITLE
[BUG] ONE PUNCH ENGINE LIGHT

### ISSUE THREAD

**Issue by Mac-ceo** [xXJamieXx/paradox-bugs#474]
### Your Discord Name

mac_ceo#7021

### A clear and concise description of what the bug is

Punching your car any where will give your car a red or orange engine light making it brake

### Steps to Reproduce the Bug

1. punch your car
2. get in
3. see engine light
4. gwt a repair

### Expected Behavior

Punch your can and be some minor body damage unless done several times over 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/lHih64Yyn1A6g/d1337zFgjIvM?invite=cr-MSxhcTksNjIwNTkzNzQs

### Log File

[CitizenFX_log_2022-05-21T152356.log](https://github.com/xXJamieXx/paradox-bugs/files/8747882/CitizenFX_log_2022-05-21T152356.log)

**Comment by Sly-Panda** [comment]
This has been fixed
