### ISSUE TITLE
Car upgrades going stock

### ISSUE THREAD

**Issue by DreadLaux** [xXJamieXx/paradox-bugs#475]
### Your Discord Name

Dreadlaux#7075

### A clear and concise description of what the bug is

My Bravado Banshee has always had problems with all my upgrades resetting to stock. This happens randomly and with no cause. I will wake up in city and take my car out of the garage and it will be stock. But also sometimes it will stay for awhile but then reset. 

### Steps to Reproduce the Bug

1. Upgrade your Bravado Banshee 
2. Give it a few days 
3. The upgrades will reset 

### Expected Behavior

To upgrade my car and it stays like that forever. 

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/99301833/169717372-b98052f1-809e-40ab-ae44-671f4559948b.png)
![image](https://user-images.githubusercontent.com/99301833/169717377-39a72f95-8014-4be7-84f1-25d6668c8e63.png)
![image](https://user-images.githubusercontent.com/99301833/169717381-21dacd24-24a5-4716-9dc2-af429cab6e0f.png)

### Extra Notes (Optional)
Latest logs

[CitizenFX_log_2022-05-22T210340.log](https://github.com/xXJamieXx/paradox-bugs/files/8750370/CitizenFX_log_2022-05-22T210340.log)

Logs after I reupgraded and parked car

[CitizenFX_log_2022-05-22T210340.log](https://github.com/xXJamieXx/paradox-bugs/files/8750379/CitizenFX_log_2022-05-22T210340.log)

_No response_

**Comment by JnKTechstuff** [comment]
Duplicate
