### ISSUE TITLE
[BUG] <REPLACE ME WITH YOUR BUG TITLE>

### ISSUE THREAD

**Issue by lPrestonl** [xXJamieXx/paradox-bugs#478]
### Your Discord Name

Preston#1337

### A clear and concise description of what the bug is

Renting a dingy and returning it from the Fishing dock in Postal 401, When you return it, it takes the boat and spawns you all the way up in Postal 2008.

### Steps to Reproduce the Bug

1. Rent a boat from Fisher Man in Postal 401
2. Drive the boat around and have fun
3. Go to Return the boat (I wasn't in the boat at the time, but it was right next to me)
4. Screen Goes black and you wake up in 2008 on the dock

### Expected Behavior

When you return the boat, you are expected to respawn on the same dock in Postal 401

### Screenshots/Videos

https://clips.twitch.tv/MotionlessTriangularClipsdadSmoocherZ-7wJhi9It-s4nc-Wg

**Comment by Sly-Panda** [comment]
Fixed next update
