### ISSUE TITLE
[BUG] House Robbery Head Pops

### ISSUE THREAD

**Issue by Petrovic247** [xXJamieXx/paradox-bugs#479]
### Your Discord Name

PretenderPatrol#5993

### A clear and concise description of what the bug is

Every time there is a house alarm in the hills, multiple Officers will head pop and not be able to fly back into their last location. I" have only heard of it happening in the hills. 

### Steps to Reproduce the Bug

1. Has happened multiple times over the past few weeks. 

### Expected Behavior

Be able to respond to house robbery calls.

### Screenshots/Videos

https://i.imgur.com/oBmDkiP.jpeg

### Log File

[CitizenFX_log_2022-05-22T062320.log](https://github.com/xXJamieXx/paradox-bugs/files/8792757/CitizenFX_log_2022-05-22T062320.log)

**Comment by Sly-Panda** [comment]
[CitizenFX_log_2022-05-31T201622.log](https://github.com/xXJamieXx/paradox-bugs/files/8809508/CitizenFX_log_2022-05-31T201622.log)
[CitizenFX_log_2022-05-31T201006.log](https://github.com/xXJamieXx/paradox-bugs/files/8809509/CitizenFX_log_2022-05-31T201006.log)

Logs from a duplicate report.

**Comment by kordoso** [comment]
[CitizenFX_log_2022-06-11T063615.log](https://github.com/xXJamieXx/paradox-bugs/files/8883395/CitizenFX_log_2022-06-11T063615.log)

**Comment by OwlCherry** [comment]
[CfxCrashDump_2022_07_07_02_08_59.zip](https://github.com/xXJamieXx/paradox-bugs/files/9059893/CfxCrashDump_2022_07_07_02_08_59.zip)

The rollback today seems to have caused the issues to get worse
