### ISSUE TITLE
[ENHANCEMENT] Walk style Not saving after doing a certain action or flying out

### ISSUE THREAD

**Issue by pulsevr34** [xXJamieXx/paradox-bugs#48]
**Your Discord Name**
Pulse+#5769

**Describe the annoyance**
When you do /walk shady (for example) it won't save the Walk animation after you do another action like crouch or sit in a chair etc.  My walk style is a big part of my character and its really annoying that it doesn't save after I do something else

**To Reproduce**
[Steps to reproduce the annoyance]
1. Enter the command /walk [insert walk here] or set your walk style by doing /emotemenu

**Requested behavior**
I want my walk to save after I fly out or do an action.

**Screenshots**
https://user-images.githubusercontent.com/97071437/147997548-6181e61f-6345-4d09-9664-0ca9a1cde9c7.mp4 Here is a video of the issue instead of a screenshot

**Additional context**
N/A

**Comment by JnKTechstuff** [comment]
Fixed https://github.com/xXJamieXx/Paradox-3.0/commit/8c64c136720d649ec14431fc6a4cb0ac28653325
