### ISSUE TITLE
[BUG] Rebreather causes tornado

### ISSUE THREAD

**Issue by EmmettIsTRASH** [xXJamieXx/paradox-bugs#480]
### Your Discord Name

EmmettIsTRASH#3911

### A clear and concise description of what the bug is

Once you enter your apartment with a rebreather on, exit the apartment and jump into your car, you obtain the glitch where your vehicle starts flying through the air spinning uncontrollably. This glitch has happened to me twice recently.

### Steps to Reproduce the Bug

My Exact Steps Following the Bug:
1. Use a rebreather.
2. Collect Coral
3. Enter Car and Drive to Apartment
4. Enter Apartment
5. Access Storage
6. Leave Apartment
7. Enter Vehicle, Glitch Occurs

### Expected Behavior

I would expect to be able to enter and exit the apartment without having the glitch occur. I should be able to drive away right after exiting the apartment.

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/mE8JKWWTBi-qZ/d13378x8WnUf?invite=cr-MSwza3MsMzU5OTYxNyw

### Log File

[CitizenFX_log_2022-05-23T030511.log](https://github.com/xXJamieXx/paradox-bugs/files/8794361/CitizenFX_log_2022-05-23T030511.log)

**Comment by Sly-Panda** [comment]
I'd just take the diving suit off before going into your apartment.  Entering/Leaving the apartment instance seems to desync the diving suit causing the prop vs tornado car issue.

**Comment by EmmettIsTRASH** [comment]
> I'd just take the diving suit off before going into your apartment. Entering/Leaving the apartment instance seems to desync the diving suit causing the prop vs tornado car issue.

Thats what I currently am doing, though if possible having something that says I need to take the rebreather off first before entering the apartment or something that auto takes it off, just so if myself or other people forget we don't have to deal with this issue.

**Comment by EmmettIsTRASH** [comment]
I just got the same exact issue, but this time I believe my radio bugged out. The radio was stuck in my hands and when entering my car, I got the tornado glitch.

**Comment by Sly-Panda** [comment]
This is a common GTA issue where if a prop is stuck in your hand it will cause any vehicle to tornado and it is not something we can fix.

We have tried to mitigate it by adding the command /clearprops but if that doesn't work and you have a prop stuck on you then a relog is pretty much what you need to do.
