### ISSUE TITLE
[BUG] Ice chest storage breaks

### ISSUE THREAD

**Issue by Kromlec** [xXJamieXx/paradox-bugs#481]
### Your Discord Name

Kromlec#3389

### A clear and concise description of what the bug is

When putting ice chest from trunk of vehicle into the hand slot it deletes the contents of the chest and makes it non usable.

### Steps to Reproduce the Bug

1. Put chest full of stuff in trunk.
2. Move item from trunk to the hand icon
3. Move chest from trunk to pockets
4. Open chest from pockets and POOF nothing in it and it's broken and can't be used.

### Expected Behavior

chest should not be breaking and contents should not be lost.

### Screenshots/Videos

None

### Log File

[CitizenFX_log_2022-05-30T023225fish.log](https://github.com/xXJamieXx/paradox-bugs/files/8795680/CitizenFX_log_2022-05-30T023225fish.log)

**Comment by BCA-BRIGGS** [comment]
[CitizenFX_log_2022-06-09T025428.log](https://github.com/xXJamieXx/paradox-bugs/files/8869475/CitizenFX_log_2022-06-09T025428.log)

**Comment by JnKTechstuff** [comment]
The only way I was ever able to reproduce it was by spamming the trunk key and the ice chest at the same time which makes me believe people are doing jank and experiencing jank then go "why is there jank". I digress, I put an anti-jank fix on it so you guys stop scuffing these,,.
