### ISSUE TITLE
[BUG] Grocery Guy Doesn't React

### ISSUE THREAD

**Issue by Weebait** [xXJamieXx/paradox-bugs#484]
### Your Discord Name

Weeb#5266

### A clear and concise description of what the bug is

Whenever you speak to him and you're not able to do the job or missing something he responds saying "I've got nothing for you" and yet currently he doesn't give any response when interacted with

### Steps to Reproduce the Bug

fly in
interact with item in pocket
Nothing occurs

### Expected Behavior

If I have the item he tells me to wait for the email

### Screenshots/Videos

N/A

**Comment by Sly-Panda** [comment]
This has been fixed.
