### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ImPaulYo** [xXJamieXx/paradox-bugs#485]
### Your Discord Name

Carbon#7678

### A clear and concise description of what the bug is

New Sandy Recycle is actually a boat rental. After talking to him he pulled a gun and disappeared

### Steps to Reproduce the Bug

Go to 954 and talk to the dude

### Expected Behavior

recycle shit? 

### Screenshots/Videos

the guy disappeared, was not recording sorry

**Comment by xXJamieXx** [comment]
Should be fixed.
