### ISSUE TITLE
[BUG] New City Council Member Are Paid Incorrectly

### ISSUE THREAD

**Issue by tusktheshrew** [xXJamieXx/paradox-bugs#486]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

New City Council when they get their roles are only getting paid per paycheck $150. Their role is supposed to give $250 per paycheck.

### Steps to Reproduce the Bug

1. Be a city council member
2. Clock in as a city council member
3. Wait till the next paycheck
4. Receive paycheck

### Expected Behavior

Paid $250 instead of $150.

### Screenshots/Videos

![Screenshot_2022-06-02_190543](https://user-images.githubusercontent.com/98053772/171769162-e0aa0089-1032-48b4-a10c-c0b878fda69d.png)

**Comment by Sly-Panda** [comment]
This is not a bug, their rank is set to Clerk and not City Council. 

The boss menu is where you change peoples ranks.
