### ISSUE TITLE
[BUG] <REPLACE ME WITH YOUR BUG TITLE>

### ISSUE THREAD

**Issue by DomBrown1** [xXJamieXx/paradox-bugs#487]
### Your Discord Name

ConnorB123 4227

### A clear and concise description of what the bug is

Everytime i do the garbage job i only get 1 drop then i have to return to the depot so i make no money.

### Steps to Reproduce the Bug

im not sure

### Expected Behavior

i was expecting to get more than 1 run to make money.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/106838300/171935190-58ea7a19-d070-407e-a8c0-1301402a5992.png)

**Comment by Sly-Panda** [comment]
Not quite sure what the report is here.
