### ISSUE TITLE
[BUG] Trunk shows full when trying to swap out items and the items vanish

### ISSUE THREAD

**Issue by DNAMcKnight** [xXJamieXx/paradox-bugs#488]
### Your Discord Name

DNAMcKnight#4318

### A clear and concise description of what the bug is

icebox in my glovebox glitched and I see an empty spot with the storage being full.

### Steps to Reproduce the Bug

1. Get on the moped and open the inventory.
2. Move the icebox in your inventory over the one in your glovebox. this should just swap them out.
3. The one in the glovebox glitched and now it shows it's full but there's no item in there.

### Expected Behavior

The icebox that I swapped should've still been in my glovebox. I should still be able to access my glovebox items.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/31538687/171941391-cececa57-2341-43d1-944d-0b9be651b78a.png)

### Extra Notes (Optional)

This is my first bug report if I didn't do it right I apologize. 

### Log File

[CitizenFX_log_2022-06-03T180054.log](https://github.com/xXJamieXx/paradox-bugs/files/8835454/CitizenFX_log_2022-06-03T180054.log)
[CitizenFX_log_2022-06-03T192432.log](https://github.com/xXJamieXx/paradox-bugs/files/8835477/CitizenFX_log_2022-06-03T192432.log)

**Comment by xXJamieXx** [comment]
I have removed the bugged items in your glovebox. If you're still running into issues with this please open a Paradox Mail ticket.
