### ISSUE TITLE
[BUG] cant stop escorting

### ISSUE THREAD

**Issue by Dez505** [xXJamieXx/paradox-bugs#49]
**Your Discord Name**
[SuperD 505#1060]

**Describe the bug**
[when i escort people on EMS or LEO i can't let go of them ]

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by JnKTechstuff** [comment]
When you press your 3rd eye it automatically drops them
