### ISSUE TITLE
[BUG] Interior Design Hates Me

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#490]
### Your Discord Name

OwlCherry#6969

### A clear and concise description of what the bug is

so any time i use the interior design, it bugs me out. each time is different. Here is todays issue.

I was looking at the furniture owned. i pressed f5 as directed to turn on/off mouse controls so i can move around the house. when i located the item, it froze, would not allow me to do anything, then i used logout for a 1/2 nap and that did not work either causing the image below.

### Steps to Reproduce the Bug

1. enter into decorating
2. look at owned furniture
3. press f5 to deactivate the mouse so i can move
4. was able to move
5. press f5 to return to the menu selection
6. bug out
7. /logout
8. bug on fly in screen
9. hard nap

### Expected Behavior

it should be seemless to move and return to the menu using appropriate commands

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/97353529/172030624-66bab882-799e-49e4-9f0f-0b2aaeec42f0.png)

### Log File

[CitizenFX_log_2022-06-05T001217.log](https://github.com/xXJamieXx/paradox-bugs/files/8839154/CitizenFX_log_2022-06-05T001217.log)

**Comment by Sly-Panda** [comment]
That feature is not on the live server at this time and as such is still in development.

**Comment by OwlCherry** [comment]
Actually it is in live hense the bug report. The interior designers are working on staging houses. I'll talk to spice. Thank you.

**Comment by Sly-Panda** [comment]
What I meant is this feature hasn't been released yet so it's still in development.  I'll reopen the bug report for someone to take care of at the earliest convenience.

**Comment by JnKTechstuff** [comment]
"I did jank shit and I wondered why it broke"

Yes logging out whilst in any NUI menu (MDT or anything) will cause issues.

**Comment by OwlCherry** [comment]
> "I did jank shit and I wondered why it broke"
> 
> Yes logging out whilst in any NUI menu (MDT or anything) will cause issues.

I logged out because it was frozen and I could not exit the menu

**Comment by Sly-Panda** [comment]
using /logout won't usually fix it if UI bugs out.  You'll need to hard relog anytime that happens with F8 quit.

**Comment by OwlCherry** [comment]
> using /logout won't usually fix it if UI bugs out. You'll need to hard relog anytime that happens with F8 quit.

And I'll do that from now on but how am I able to decorate if anytime I do anything it freezes... doesn't solve the issue
