### ISSUE TITLE
Flashing Lights within Catalogs/Dealerships [BUG] 

### ISSUE THREAD

**Issue by BreColorful** [xXJamieXx/paradox-bugs#491]
### Your Discord Name

Bre#5286

### A clear and concise description of what the bug is

It's been a pretty consistent thing that when you enter the dealerships/catalog that the lights in the background will flash over and over again. It doesn't appear that anything within the settings fixes it either. 

### Steps to Reproduce the Bug

Enter a catalog for a dealership. Seems to be an issue with all of them. 

### Expected Behavior

No strobe lights whenever I'm trying to buy a badass car. </3 

### Screenshots/Videos

I unfortunately don't have any screenshots or videos of this at the moment. 

### Extra Notes (Optional)

Thank you for your time. ♥

**Comment by JnKTechstuff** [comment]
They are slated to be replaced
