### ISSUE TITLE
[Enhancement] Trashcans/bins

### ISSUE THREAD

**Issue by Darahz** [xXJamieXx/paradox-bugs#492]
### Your Discord Name

Darahz#0001

### A clear and concise description of what the bug is

So i think i used the wrong template for this. But anyhow.
I would love to have the option to dump stuff that you don't need into bins around city,
instead of dumping all of the stuff you dont need on the ground it would be amazing if you could stick it in a bin and have it decay over time? maybe using the gun degrade thing?
That way some people can also get stuff out of it if its something they need.

### Steps to Reproduce the Bug

1. Have tons of waterbottles or some other stuff
2. dump it on the ground
3. nothing

### Expected Behavior

More recycling!

### Screenshots/Videos

none

**Comment by xXJamieXx** [comment]
Recycling is now a thing and so we will stick with that as an alternative to your suggestion. Thanks for submitting this though.
