### ISSUE TITLE
[BUG] Journey's no longer having trunks

### ISSUE THREAD

**Issue by kingtortle** [xXJamieXx/paradox-bugs#493]
### Your Discord Name

Tortle#0499

### A clear and concise description of what the bug is

I pulled my Journey(Little meth RV) out of the garage today and no matter where I stood around it there was no trunk. It is not just with mine others are having the same issue. This is a major problem because people store a lot of their items in them!

### Steps to Reproduce the Bug

1. Take Journey out of Garage
2. Try to access trunk
3. There will be no trunk no matter where you stand.

### Expected Behavior

To be able to access the trunk

### Screenshots/Videos

None

**Comment by Sly-Panda** [comment]
Just tested and it is still there and working, just in a very specific spot.

**Comment by JnKTechstuff** [comment]
> Just tested and it is still there and working, just in a very specific spot.

Yeah I added the more accurate trunk finder. I think they are trying to get them at the old place and not being careful
