### ISSUE TITLE
[BUG] <REPLACE ME WITH YOUR BUG TITLE>

### ISSUE THREAD

**Issue by LtNathan235** [xXJamieXx/paradox-bugs#494]
### Your Discord Name

Lnathan#2764

### A clear and concise description of what the bug is

The money wash does not work, when pressing [G] to wash money nothing happens, have tested with few other people and it has not worked for them either. 

### Steps to Reproduce the Bug

Get inked money bags
Go to location
Attempt to wash

### Expected Behavior

When I press [G] it would take my inked bags and reward me the desired amount of money in cash.

### Screenshots/Videos

none

### Extra Notes (Optional)

none

**Comment by Sly-Panda** [comment]
Fixed next update.  Try include the title in future bug reports tho plz :)
