### ISSUE TITLE
[BUG] Emergency button is also an ejecto seato cuz

### ISSUE THREAD

**Issue by PadawanPepsi** [xXJamieXx/paradox-bugs#495]
### Your Discord Name

PadawanPepsi#6898

### A clear and concise description of what the bug is

If you are sitting in your car and you are down as a LEO. When you hit your panic you get shot out of the car. This happened to me when I was driving not sure if its the same when passenger i was driving a CID CVPI 

### Steps to Reproduce the Bug

drive a car
get downed
hit your emergency button

### Expected Behavior

i would imagine you would stay in the car when u hit your button

### Screenshots/Videos

https://user-images.githubusercontent.com/96961442/173168108-64f40fb1-5092-488b-8277-03c89140c738.mp4

### Log File

[CitizenFX_log_2022-06-11T011413.log](https://github.com/xXJamieXx/paradox-bugs/files/8882930/CitizenFX_log_2022-06-11T011413.log)

**Comment by JnKTechstuff** [comment]
If it happens again please open another bug report but this is unable to be reproduced and may be caused by other factors
