### ISSUE TITLE
[BUG] <Head pop at new tow Hq>

### ISSUE THREAD

**Issue by BullRiderMcGhee** [xXJamieXx/paradox-bugs#496]
### Your Discord Name

BullRiderMcGhee#3246

### A clear and concise description of what the bug is

i was at new bikini hq with alot of ops on duty went to put a truck away when my head popped idk what specifically caused it its happened twice around here before though

### Steps to Reproduce the Bug

1. goto HQ 
2. i put the 2 door flatbed truck away idk if that caused it alot of people were around tho
3. head pop

### Expected Behavior

no head pop

### Screenshots/Videos

n/a

### Extra Notes (Optional)

n/a

### Log File

[CitizenFX_log_2022-06-12T172846.log](https://github.com/xXJamieXx/paradox-bugs/files/8886516/CitizenFX_log_2022-06-12T172846.log)

**Comment by Sly-Panda** [comment]
One off issue
