### ISSUE TITLE
[BUG] <Thermite Not Working On Trucks>

### ISSUE THREAD

**Issue by kingtortle** [xXJamieXx/paradox-bugs#497]
### Your Discord Name

Tortle#0499

### A clear and concise description of what the bug is

When you kill the guards to the trucks there is a good chance that you will not be able to blow the doors. It has happened 4 times where when you go to third eye the doors you don't get the option to thermite them.

### Steps to Reproduce the Bug

1.Stop truck
2. Kill guards
3. Attempt to thermite doors
4. The option will not be there on your third eye
5. Police wont show up and you will overhear traffic of a previous robbery 

### Expected Behavior

To be able to blow the doors when you third eye

### Screenshots/Videos

None but it should be simple enough to reproduce if you try a few of them based on the amount of times it has happened to us

**Comment by xXJamieXx** [comment]
@kingtortle Is this still a problem since the third-eye update? Tested it on a few trucks and always had the option as long as I ha the correct requirements.

**Comment by kingtortle** [comment]
Didnt see the response on this. It is still happening it just seems to be more rare now and usually there are other weird things happening too. One instance there was an empty truck sitting there and the radio spawned another one I guess because I showed up and let us kill the guards but wouldn't let us thermite.
It seems to still be an issue but less common.
