### ISSUE TITLE
[BUG] Third Eye Not working for public safety stuff

### ISSUE THREAD

**Issue by drugfree420** [xXJamieXx/paradox-bugs#499]
### Your Discord Name

drug_free#4200

### A clear and concise description of what the bug is

When you go into the EMS locker room to change clothes you are unable to. You get the purple eye but do not get the menu when right clicking

### Steps to Reproduce the Bug

1 Clock on as EMS
2 Go to third eye the locker to change closed
3 Purple eye comes up but you dont get the options

### Expected Behavior

Be able to get the option after third eying and be able to change clothes.

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/ouM8bsoCobWV7/d1337eGVaXVr?invite=cr-MSxkTW0sMjM3OTE0MjMs

### Log File

[CitizenFX_log_2022-06-14T210909.log](https://github.com/xXJamieXx/paradox-bugs/files/8904030/CitizenFX_log_2022-06-14T210909.log)

**Comment by pulsevr34** [comment]
Same with chairs in pillbox, PD Locker, PD mechanic etc.
