### ISSUE TITLE
[ENHANCEMENT] Add other hospitals

### ISSUE THREAD

**Issue by JnKTechstuff** [xXJamieXx/paradox-bugs#5]
**Describe the bug**
- Add other hospital job locations
- Add other hospital check-in locations

**Additional context**
From to-do list

**Comment by xXJamieXx** [comment]
Resolved here: https://github.com/xXJamieXx/Paradox-3.0/commit/29eaae1fd6f02f5714758f611d5b32eb945f6bf8
