### ISSUE TITLE
[BUG] Judges cannot Clock Out or access MDT

### ISSUE THREAD

**Issue by CorFinn** [xXJamieXx/paradox-bugs#504]
### Your Discord Name

GrandNagus#9705

### A clear and concise description of what the bug is

Pretty self-explanatory. Judges cannot clock off their job. Also, the Judge job does not have MDT access, and since we can't clock off, we can't access the Public Records, therefore effectively locking us out of the MDT for any cases. 

### Steps to Reproduce the Bug

1. Refer to description

### Expected Behavior

The ability to clock-in/clock-out, and the ability to see cases and their evidence is important in a trial.

### Screenshots/Videos

https://i.imgur.com/t8JLTmI.png

**Comment by xXJamieXx** [comment]
Just pushed an update to allow any non-public safety job to access public records
