### ISSUE TITLE
[BUG] MDT doesnt clear Warrants

### ISSUE THREAD

**Issue by M1ngh** [xXJamieXx/paradox-bugs#505]
### Your Discord Name

Minghee#0876

### A clear and concise description of what the bug is

When we serve a warrant and we got to the report were the warrant is written and we clear it there and save it its doenst do anything and the person still have the warrant on his profille.
plus charges on warrant report each time u try to remove it and save it it duplicate the charges
bellow i will drop a video about the situation

### Steps to Reproduce the Bug

1. go on warrant report and remove the warrant mark
2. save and its supose to be clear
3. the warrnat mark still green wanted still appear on suspect profile and the charges on the warrant get duplicated

### Expected Behavior

1. go on warrant report and remove the warrant mark
2. save and its supose to be clear

### Screenshots/Videos

https://medal.tv/clips/oJSToHgoGSQPV/vpFjEFLCj?invite=cr-MSxYaWwsMzgwMzUxODEs

**Comment by xXJamieXx** [comment]
Weird issue. I cleaned up that persons profile and couldn't get it to happen again, something weird happened there.

**Comment by M1ngh** [comment]
Hello im writting here cause the warrant clear is not wroking atleast on Dakota Andre Profile and when i try to remove it it crashes my MDT to the point i have to quit and come back in.
And do not clear the warrant.

Theres a video
https://medal.tv/games/imported-clips/clips/sEDSYE1krnuR6/d13375Pj4RwF?invite=cr-MSxiQlAsMzgwMzUxODEs
