### ISSUE TITLE
[BUG] Car selling issue

### ISSUE THREAD

**Issue by AyraSensei** [xXJamieXx/paradox-bugs#507]
### Your Discord Name

AyraSensei#8914

### A clear and concise description of what the bug is

The option to sell a car is not appearing through the F1 menu at the vehicle buyer.
Attempted multiple areas inside the shop, with 2 different cars (mine, Brioso and Elegy)
Another player also tried and said it wasn't working prior to server restart.
Tried after server restart, still not working.
Reported through Discord support ticket, been advised that the option seems turned off and is an issue.

### Steps to Reproduce the Bug

Attempt to sell a vehicle.

### Expected Behavior

The option will not appear as it used to.

### Screenshots/Videos

N/A

**Comment by Sly-Panda** [comment]
Fixed next update.
