### ISSUE TITLE
[BUG] HI JAMIE. Terry needed a personal MDT bug report

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#508]
### Your Discord Name

OwlCherry#6969

### A clear and concise description of what the bug is

the MDT will not open his profile (Terry Laughlin) Have not been able duplicate this with any other civilian MDT as of yet. this is a wise spread issue for all officers.

### Steps to Reproduce the Bug

1. Search Terry Laughlin
2. Click Profile
3. Never Opens

### Expected Behavior

Should open when you click his profile as everyone else does

### Screenshots/Videos

https://user-images.githubusercontent.com/97353529/174504355-0a51948d-e97a-4638-a0c1-b376ed4627cf.mp4

### Log File

[CitizenFX_log_2022-06-19T224610.log](https://github.com/xXJamieXx/paradox-bugs/files/8936600/CitizenFX_log_2022-06-19T224610.log)

**Comment by xXJamieXx** [comment]
Fixed
