### ISSUE TITLE
[ENHANCEMENT] Requesting an ATM at PDM

### ISSUE THREAD

**Issue by Malfoo** [xXJamieXx/paradox-bugs#509]
**Your Discord Name**
Malfo#2515

**Describe the annoyance**
Selling vehicles gives you a ton of cash, a ATM inside PDM would be lovely

**To Reproduce**
[Steps to reproduce the annoyance]
1. Sell car get lots of money
2. Have to run to bank cause you have no car
3. Have lots of cash on you if you get robbed you are SOL

**Requested behavior**
Put a ATM inside PDM :)

**Comment by xXJamieXx** [comment]
Changed script to add money to bank instead of cash as an alternative.
