### ISSUE TITLE
[BUG] Cant push panic button when down in vehicle

### ISSUE THREAD

**Issue by monk3ythund3r** [xXJamieXx/paradox-bugs#51]
**Your Discord Name**
Monk3yThund3r#5594

**Describe the bug**
When you go down in your vehicle you are unable to push your panic button

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
(https://i.imgur.com/L7QLsWX.jpeg)

**Additional context**
[Add any other context about the problem here]

**Comment by JnKTechstuff** [comment]
https://i.imgur.com/w8ALjy8.jpeg
