### ISSUE TITLE
[BUG] Back doors at Tow being weird

### ISSUE THREAD

**Issue by Darahz** [xXJamieXx/paradox-bugs#510]
### Your Discord Name

Darahz#0001

### A clear and concise description of what the bug is

When you try to unlock the doors into the vehicle bays to tow the backdoor gets unlocked.

### Steps to Reproduce the Bug

1. Unlock door
2. Other door gets unlocked

### Expected Behavior

The right door to unlock

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/pc8CGhDgJepv1/d133766kpsiS?invite=cr-MSxveFUsNjkxMTgzMTcs

### Log File

[CitizenFX_log_2022-06-20T154051.log](https://github.com/xXJamieXx/paradox-bugs/files/8942317/CitizenFX_log_2022-06-20T154051.log)

**Comment by Sly-Panda** [comment]
This is caused by the doors being too close to one another and their orientation.  I've tried to tweak it to where you can unlock both reliably and it's not worked so i've gone ahead and removed the lock from the internal door.  Will be live next time we push an update.
