### ISSUE TITLE
[BUG] MRPD Captain's Office Chair doesn't work.

### ISSUE THREAD

**Issue by Petrovic247** [xXJamieXx/paradox-bugs#511]
### Your Discord Name

PretenderPatrol#5993

### A clear and concise description of what the bug is

You can look at, but are unable to sit in the chair in the MRPD Captains office.

### Steps to Reproduce the Bug

Look at it with third eye
Press sit 
Nothing happens.

### Expected Behavior

When you press sit, it sits. 

### Screenshots/Videos

N/a

### Log File

[CitizenFX_log_2022-06-21T001742.log](https://github.com/xXJamieXx/paradox-bugs/files/8945304/CitizenFX_log_2022-06-21T001742.log)

**Comment by Sly-Panda** [comment]
Will be fixed next update
