### ISSUE TITLE
[BUG] Falling through world at high speed

### ISSUE THREAD

**Issue by Dez505** [xXJamieXx/paradox-bugs#512]
### Your Discord Name

SuperD 505#1060

### A clear and concise description of what the bug is

when ever driving code 3 you will fall into the void for no reason 

### Steps to Reproduce the Bug

drive code 3 down LS free way 

at a random time fall into the void

### Expected Behavior

fall into the void

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/pliN8zPUkJ_OM/d1337ZDg3Qz0?invite=cr-MSx4UkcsMzQ3OTM3MTAs

### Log File

[CitizenFX_log_2022-06-21T200919.log](https://github.com/xXJamieXx/paradox-bugs/files/8953541/CitizenFX_log_2022-06-21T200919.log)

**Comment by Sly-Panda** [comment]
Is this still happening or was it just that one night?  I saw it happen to someone else the night this was posted and never seen it since.

**Comment by Dez505** [comment]
fixed by clearing cache and deleting the snail. may have been on my side but I heard other people having this problem

**Comment by xXJamieXx** [comment]
Could be multiple things:
- You need to up your extended texture budget
- You ran out of disk space on the drive FiveM is installed
- Your cache was corrupted or something similar which caused that section of the map to fail to load
