### ISSUE TITLE
[BUG] <Tattoo shop exit>

### ISSUE THREAD

**Issue by A1busDumbledore** [xXJamieXx/paradox-bugs#513]
### Your Discord Name

Minty#5681

### A clear and concise description of what the bug is

Entered the Tattoo shop in sandy went to exit and was left on the map screen of the building wasn't able to do anything, tried it twice and the same thing happened.

![image](https://user-images.githubusercontent.com/107995596/175007671-70542eb3-0457-4dea-aa04-77f3a84b3138.png)

### Steps to Reproduce the Bug

sorry mate i dont understand this question

### Expected Behavior

I expected to be able to exit the shop menu and move out of the shop

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/107995596/175008126-fecbd2d6-0834-44c0-b1d2-724628a090b0.png)

### Log File

[CitizenFX_log_2022-06-22T101611.log](https://github.com/xXJamieXx/paradox-bugs/files/8956797/CitizenFX_log_2022-06-22T101611.log)

**Comment by xXJamieXx** [comment]
Disabled pressing escape to close the menu to avoid issues like this. Use backspace instead.
