### ISSUE TITLE
[Jerry Can] <Cant fill the jerrycan with gas>

### ISSUE THREAD

**Issue by Tokentys** [xXJamieXx/paradox-bugs#517]
### Your Discord Name

TokenTys#7692

### A clear and concise description of what the bug is

When attempting to third eye and refill and empty jerry can nothing happens, this in turns doesnt let you fill your car with gas even normally from a pump as it will tell you that the jerry can is empty. This happens even if you put the jerry can away.

### Steps to Reproduce the Bug

1. Use a empty jerry can and use try to refill it at any pump.
2. Attempt to refill a vehicle using the gas station pumps 

### Expected Behavior

Nothing will happen and you will recive a message that you cant fill up using a empty jerry can

### Screenshots/Videos

![delete](https://user-images.githubusercontent.com/105580368/175788585-7401e984-8d11-42d6-af92-27f2e7aa7bc4.jpg)

**Comment by Sly-Panda** [comment]
Should be fixed next update
