### ISSUE TITLE
[BUG] CID Camera Unavailable

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#518]
### Your Discord Name

OwlCherry#6969

### A clear and concise description of what the bug is

Use of store cameras is no longer available stating camera does not exist

### Steps to Reproduce the Bug

1. determine location
2. use command to access camera
3. recieve error camera doesnt exist

### Expected Behavior

its expected that depending on what camera you access you see inside the store

### Screenshots/Videos

https://i.imgur.com/YrszWFU.png

### Log File

[CitizenFX_log_2022-06-26T211752.log](https://github.com/xXJamieXx/paradox-bugs/files/8987591/CitizenFX_log_2022-06-26T211752.log)

**Comment by Sly-Panda** [comment]
Which cameras don't work?  Al the enabled ones seem to be working as normal.

**Comment by OwlCherry** [comment]
havent had further issues since

**Comment by Sly-Panda** [comment]
Awesome i'll go ahead and close this then, if it crops back up just reopen it :)
