### ISSUE TITLE
[ENHANCEMENT] Notepads

### ISSUE THREAD

**Issue by BullRiderMcGhee** [xXJamieXx/paradox-bugs#519]
**Your Discord Name**
[BullRiderMcGhee#3246]

**Describe the annoyance**
Be able to use the notepads to transfer notes to someone else after you write on it so I can give a note to someone to give to someone else if that makes sense

**To Reproduce**
[Steps to reproduce the annoyance]
1. Buy notepad
2. Write in it
3. Give to someone else
4. They be able to read it
**Requested behavior**
Write a note on notepad and give it to someone to read I think would be cool for rp maybe a note given to someone as a threat or what not

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
[Add any other context about the enhancement here]

**Comment by xXJamieXx** [comment]
Added next restart.
