### ISSUE TITLE
[BUG] Switching Characters get "Instanced"

### ISSUE THREAD

**Issue by BrotherDayZ** [xXJamieXx/paradox-bugs#52]
**Your Discord Name**
BDZ#0001

**Describe the bug**
Whenever you go to your apartment to switch characters, the character you select will be in the "multiverse" and you wont be able to see or interact with anyone.

**To Reproduce**
[Steps to reproduce the bug]
1. Go into apartment 
2. switch characters
3. get multiversed

**Expected behavior**
n/a

**Screenshots**
n/a

**Additional context**
n/a

**Comment by JnKTechstuff** [comment]
Fixed on https://github.com/xXJamieXx/Paradox-3.0/commit/5152275b31050008ea395be765d7f400b5315c27
