### ISSUE TITLE
I cannot take my vehicules out of the impound[BUG] 

### ISSUE THREAD

**Issue by DracoWZ** [xXJamieXx/paradox-bugs#520]
### Your Discord Name

Draco#8314

### A clear and concise description of what the bug is

I cannot take out any vehicles from the impound.
I had my vehicle outside of the tattoo shop and when I left I can't find it and at the impound I can't take it.

### Steps to Reproduce the Bug

IDK to be honest

### Expected Behavior

I expect to be able to take my vehicle out of the impound.

### Screenshots/Videos

https://cdn.discordapp.com/attachments/991003354727579768/991003512861229076/unknown.png

**Comment by Nicklmfao** [comment]
https://medal.tv/games/gta-v/clips/qqyJetVWjik5j/d1337XTVllqZ?invite=cr-MSx1U3QsMjM4MzMzNzYs 

Had the same issue from a report that came in earlier, here's a video if it helps at all.

**Comment by Sly-Panda** [comment]
> https://medal.tv/games/gta-v/clips/qqyJetVWjik5j/d1337XTVllqZ?invite=cr-MSx1U3QsMjM4MzMzNzYs
> 
> Had the same issue from a report that came in earlier, here's a video if it helps at all.

Is it possible their car was still somewhere on the server?  This error should ONLY appear if the car still exists somewhere.

**Comment by Nicklmfao** [comment]
> > https://medal.tv/games/gta-v/clips/qqyJetVWjik5j/d1337XTVllqZ?invite=cr-MSx1U3QsMjM4MzMzNzYs
> > Had the same issue from a report that came in earlier, here's a video if it helps at all.
> 
> Is it possible their car was still somewhere on the server? This error should ONLY appear if the car still exists somewhere.

Not sure, I attempted to get him to check the last garage but he got nothing and couldn't track it. So I genuinely don't know.

**Comment by xXJamieXx** [comment]
Added a check to see if the car exists in the world before showing it in the impound menu so if this issue still occurs then there's some other fundamental issue with the impound system. For now I'll close this as it is likely user error.
