### ISSUE TITLE
[BUG] can't buy items from imports

### ISSUE THREAD

**Issue by madsskyy** [xXJamieXx/paradox-bugs#522]
### Your Discord Name

madsskyy #2165

### A clear and concise description of what the bug is

When you go down to the dock to the general imports, you cant buy anything from the vendor ped. This shop has items like fabric and tobacco and spices and fruit that you can't get anywhere else in the city that the businesses use to make items. 

### Steps to Reproduce the Bug

1. go to the general imports
2. third eye the ped
3. click the prompt

### Expected Behavior

it should open a store and i should be able to buy items

### Screenshots/Videos

[Uploading 2022-06-29 03-25-47.zip…]()

### Extra Notes (Optional)

nothing shows up in the f8 menu either

**Comment by madsskyy** [comment]
additional note: the meat place and crops places are fine

**Comment by Sly-Panda** [comment]
Will be fixed next update

**Comment by Sly-Panda** [comment]
Fixed
