### ISSUE TITLE
[BUG] Custom plates don't give you your car keys correctly

### ISSUE THREAD

**Issue by SpiceF0x** [xXJamieXx/paradox-bugs#523]
### Your Discord Name

spicedf0x#2127

### A clear and concise description of what the bug is

When pulling your car out of your garage, you receive the prompt that you've received the keys, but as soon as you get in the car the engine shuts down and the car is disabled.

This happens with only cars where plates have been customised.

### Steps to Reproduce the Bug

1. Pull out car with custom plate
2. Get in
3. Car disables
4. Unable to turn engine on
5. Park car
6. Pull out car with no custom plate
7. No problems

### Expected Behavior

Have keys to any cars I own, I paid money for that plate, homie

### Screenshots/Videos

https://streamable.com/0a7bcs

**Comment by xXJamieXx** [comment]
Believe this is fixed next restart.
