### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by D4rkStr1der** [xXJamieXx/paradox-bugs#525]
### Your Discord Name

FuriousStrider#3393

### A clear and concise description of what the bug is

When going to refill jerry can at gas station it take money but doesnt refill.

### Steps to Reproduce the Bug

1. have empty jerry can.
2. try and refill jerry can.

### Expected Behavior

I expected it to refill my jerry can.

### Screenshots/Videos

*

### Extra Notes (Optional)

*

### Log File

*

**Comment by xXJamieXx** [comment]
Fixed next restart.
