### ISSUE TITLE
[BUG] BOLO Plate Bug

### ISSUE THREAD

**Issue by Malfoo** [xXJamieXx/paradox-bugs#526]
### Your Discord Name

Malfo#2515

### A clear and concise description of what the bug is

Getting an alert for a BOLO plate on a cop car

### Steps to Reproduce the Bug

1. Cop car drove by
2. Got a ding on my radar saying bolo plate

### Expected Behavior

Hopefully no radar pings for cop cars marking them as BOLO

### Screenshots/Videos

https://i.imgur.com/AjhtdaK.jpeg
https://i.imgur.com/DNfud2F.jpeg

**Comment by Malfoo** [comment]
Apparently this is also effecting Bikini Tow trucks as well

**Comment by xXJamieXx** [comment]
Should be fixed next restart if not already.
