### ISSUE TITLE
[BUG] Gas pumps explode when trash cans are pushed into them

### ISSUE THREAD

**Issue by daemon3698** [xXJamieXx/paradox-bugs#528]
### Your Discord Name

maddog3698#3698

### A clear and concise description of what the bug is

o I went to the gas station in paleto at postal 3016 I was walking around while my friend was pumping gas and I accidently brushed the trashcan. When I did the yellow bin touched the pump and exploded

### Steps to Reproduce the Bug

1. Push the trash bin at gas station at postal 3016 into the left pump (One closes to the mechanic garage) and when it touches the gas pump it explodes

### Expected Behavior

For it not to explode

### Screenshots/Videos

N/A

**Comment by daemon3698** [comment]
Does it to both tanks

**Comment by Sly-Panda** [comment]
Pushing a heavy metal object into the gas pumps causes them to explode?
