### ISSUE TITLE
[BUG] Can't test drive cars

### ISSUE THREAD

**Issue by DraconicRebel** [xXJamieXx/paradox-bugs#529]
### Your Discord Name

DraconicRebel#5942

### A clear and concise description of what the bug is

As the title says you can't test drive cars thanks to the keys.

### Steps to Reproduce the Bug

N/A

### Expected Behavior

Once you hit test drive car, you should be able to give it a test run on it, regardless of keys.

### Screenshots/Videos

https://user-images.githubusercontent.com/100647205/176651881-0e70450f-9d82-42c2-a9e8-b1a313180cf6.mp4

**Comment by Sly-Panda** [comment]
Should be fixed next update

**Comment by Sly-Panda** [comment]
Fixed
