### ISSUE TITLE
Off-Road and Truck Dealership seller is missing

### ISSUE THREAD

**Issue by Afgoozilla** [xXJamieXx/paradox-bugs#53]
**Your Discord Name**
Afgoozilla#0180

**Describe the bug**
The Off-Road and Truck Dealership seller has been missing for a few days, been trying to buy the Bison and he is no where to be found.

**To Reproduce**
[Steps to reproduce bug]
1. Go to the Off-Road and Truck Dealership
2. 
3. 

**Expected behavior**
For the seller to be there to purchase certain vehicles only sold there.

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by JnKTechstuff** [comment]
Fixed https://github.com/xXJamieXx/Paradox-3.0/commit/279921b76019b8cde24e73708b90f55d0ef08e7a
