### ISSUE TITLE
[BUG] /givekeys does not work, thoroughly tested - borks car locks so heavily annoying lmao

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#531]
### Your Discord Name

OwlCherry#6969

### A clear and concise description of what the bug is

The commands do not work, logged server responses as well. this also causes allowing someone to drive your car to be unable to and causes heavy issues with car locks and being unable to get inside a vehicle

/givekeys - Results Are | you do not have keys to vehicle
/givekeys - Results Are | There is nobody nearby to hand keys to

out of car
/givekeys - Results Are | No response logged by server/ ineffective
/givekeys - Results Are | No response logged by server/ ineffective

### Steps to Reproduce the Bug

Use command /givekeys within car with someone

ABOVE RESULTS

### Expected Behavior

should hand keys over easy

### Screenshots/Videos

https://i.imgur.com/y0Bh9sh.png

https://i.imgur.com/XUOUIxv.png

### Log File

[CitizenFX_log_2022-06-30T173110.log](https://github.com/xXJamieXx/paradox-bugs/files/9022162/CitizenFX_log_2022-06-30T173110.log)

**Comment by xXJamieXx** [comment]
Fixed next restart.
