### ISSUE TITLE
[ENHANCEMENT] Car menu when out of vehicle

### ISSUE THREAD

**Issue by pulsevr34** [xXJamieXx/paradox-bugs#532]
**Your Discord Name**
Pulse+#5769

**Describe the annoyance**
Not 100% needed but I would like to see if its possible to be able to open car doors when outside of a car like we could back in 2.0. As a cop if we want to RP opening doors to let a suspect in/out of our vehicle we'd have to go into the driver seat to open our vehicle doors, and suspects just run. I was thinking it could be something like the ambulances had a while ago where we could third eye the vehicle and press "open ambulance doors" or something along the lines of that. Also people keep RP checking me when I put them in my car and thats annoying "HoWd YoU PuT Me ThRoUGh ThE DoOr??!?!?!?!?"

**To Reproduce**
[Steps to reproduce the annoyance]
1. Go into car to open door menu
2. open door to let police suspect in
3. suspect run
4. sad :(

**Requested behavior**
A third eye or menu to let us open vehicle doors while outside of the vehicle.

**Screenshots**
N/A, just a third eye option added to our cars to open our doors.

**Additional context**
N/A

**Comment by xXJamieXx** [comment]
Next restart adds door options in the F1 menu when looking at vehicle.
