### ISSUE TITLE
[BUG] Vehicle keys again

### ISSUE THREAD

**Issue by pulsevr34** [xXJamieXx/paradox-bugs#533]
### Your Discord Name

Pulse+#5769

### A clear and concise description of what the bug is

every car keeps shutting off saying "you do not have the keys", loosk to be only public safety vehicles and stolen local cars. I cannot come on duty because when I get a car from the police ped, the car says "you do not have the keys to this vehicle", and I cant use the provided car. Needs to be fixed ASAP

### Steps to Reproduce the Bug

Get publics safety car from ped
No keys]
Cant drive

Steal car or be in department provided car
car shuts off with "You do not have the keys to this vehicle" 
cant drive and have to continuously turn on car

### Expected Behavior

be able to drive stolen cars or public safety cars without losing the keys, and be able to get a public safety car from police ped.

### Screenshots/Videos

https://streamable.com/izeg96 The video doesnt show the error message for the keys in this one, but i cant lock or unlock it either

### Log File

Cant fly out atm, will provide in a few minutes if still needed

**Comment by pulsevr34** [comment]
[CitizenFX_log_2022-07-01T011200.log](https://github.com/xXJamieXx/paradox-bugs/files/9024621/CitizenFX_log_2022-07-01T011200.log)
Heres my logs file

**Comment by xXJamieXx** [comment]
Should be fixed next restart.
