### ISSUE TITLE
[BUG] Tow Cars are completely borked. Instanced immediately upon spawn

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#534]
### Your Discord Name

OwlCherry#6969

### A clear and concise description of what the bug is

suddenly with all the key issues all tow trucks are now instanced or "stuck" and will not move. tow functions are broken too

### Steps to Reproduce the Bug

1. talk to ped to pull out tow cars
2. try to drive
3. Will not move, cant gain keys, will not turn on or run. broken

### Expected Behavior

should spawn in the truck and you can drive

### Screenshots/Videos

https://i.imgur.com/cmCVzS6.jpeg

### Log File

[CitizenFX_log_2022-07-01T021847.log](https://github.com/xXJamieXx/paradox-bugs/files/9024610/CitizenFX_log_2022-07-01T021847.log)

**Comment by Bojackjackson** [comment]
[CitizenFX_log_2022-07-01T022041.log](https://github.com/xXJamieXx/paradox-bugs/files/9024636/CitizenFX_log_2022-07-01T022041.log)

**Comment by xXJamieXx** [comment]
Should be fixed next restart.
