### ISSUE TITLE
[BUG] Bank Visual Bug

### ISSUE THREAD

**Issue by tusktheshrew** [xXJamieXx/paradox-bugs#535]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

I logged out of Gigi through the apartment logout, and switched over to Finn. I needed to transfer money I paid out of my personal wallet from the business account as Finni's Taxis helped sponsor the event. When I switched the money, the money still went into the right account, but on the picture given it says Gigi did the transaction.

### Steps to Reproduce the Bug

1. Logout of an alternate character through the apartment logout
2. Log onto Main.
3.  Withdraw from 2nd account into personal account
4. Deposit from 2nd account into personal account.

### Expected Behavior

The right person making the transaction is the name marked.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98053772/176964159-5e5eef00-d121-4dc3-988b-1c5f6d1d2abd.png)

### Log File

[BankTransfer.txt](https://github.com/xXJamieXx/paradox-bugs/files/9031429/BankTransfer.txt)

**Comment by xXJamieXx** [comment]
Believe this is fixed next restart.
