### ISSUE TITLE
[BUG] Emotemenu crash

### ISSUE THREAD

**Issue by KayNelson7** [xXJamieXx/paradox-bugs#536]
### Your Discord Name

QueenKayy#5499

### A clear and concise description of what the bug is

Emotemenu will not pop up anymore after using the heart hands emote.

### Steps to Reproduce the Bug

dont use the emote itself

### Expected Behavior

emotemenu wont pop up afterword's

### Screenshots/Videos

N/A

### Extra Notes (Optional)

N/A

**Comment by xXJamieXx** [comment]
Should be fixed.
