### ISSUE TITLE
[BUG] Locks Not Locking on Cars

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#537]
### Your Discord Name

OwlCherry#6969

### A clear and concise description of what the bug is

hi. Me Again. New issue is locks aren't actually working rn. 

### Steps to Reproduce the Bug

1. attempt to lock the car from inside or outside car.
2. get confirmation car is locked
3. attempt to lock check
4. get in car as if unlocked

### Expected Behavior

lock should cause door to be not openable by pulling door handle

### Screenshots/Videos

https://streamable.com/qtf4e6

### Log File

[CitizenFX_log_2022-07-01T230852.log](https://github.com/xXJamieXx/paradox-bugs/files/9032031/CitizenFX_log_2022-07-01T230852.log)

**Comment by xXJamieXx** [comment]
Fixed.
