### ISSUE TITLE
[BUG] <Scenes don't show if close to a building with interior>

### ISSUE THREAD

**Issue by TheGraveyardShift** [xXJamieXx/paradox-bugs#538]
### Your Discord Name

TheGraveyardShift#6865

### A clear and concise description of what the bug is

I am trying to place scenes on the outside of a building I call my house and they only appear when I go inside. Scenes DO work outside they just have to be far enough away from a building with an interior. If its too close they will just appear invisible. 

### Steps to Reproduce the Bug

1. Go near any building that has an interior. 
2. Create a scene and place it on the building or near it
3.

### Expected Behavior

I expected scenes that are placed outside only be seen outside and scenes placed inside only be seen inside.

### Screenshots/Videos

 Heres a video of me trying to place scenes near my characters house.

https://user-images.githubusercontent.com/104471236/176982474-84d92d67-85e0-44e1-8a6f-bfce9d1eccff.mp4

**Comment by xXJamieXx** [comment]
Fixed next restart.
