### ISSUE TITLE
[BUG] Trucking quest not restarting properly

### ISSUE THREAD

**Issue by hitmefast** [xXJamieXx/paradox-bugs#54]
**Your Discord Name**
hitmefast#4443

**Describe the bug**
In trucking job, if you release the trailer with the quest and then grab another head truck and attatch it backto the trailer, and then cancel the trucking. The quest will stay with the old trailer and therefore the icons and the avaliability to finish the quest are bugged

**To Reproduce**
1. Initiate quest of trucking (any), hop in the truck, get the trailer
2. Change the head of the truck and pick another one and connect it to the first trailer
3. Cancel the truck quest
4. Next truck quest will not show the trailer 'area'

**Expected behavior**
Reset every time trucking is initiated, either way the old truck and trailer should disapear

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by JnKTechstuff** [comment]
We need a video because your description is not coming across
