### ISSUE TITLE
[BUG] Yard job unable to be performed

### ISSUE THREAD

**Issue by Terrylaughlin35** [xXJamieXx/paradox-bugs#540]
### Your Discord Name

Terry Laughlin#3143

### A clear and concise description of what the bug is

Yard job in prison is unable to be done next to the cells. third eye becomes Purple but unable to choose any options.

### Steps to Reproduce the Bug

1. Get the yard job
2. once it comes to the location pictured you will be unable to perform the job.

### Expected Behavior

work the job and cut time off.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/97036023/176986401-dcc554c6-eb60-4021-b3ef-534ef47bed58.png)

### Log File

[CitizenFX_log_2022-07-02T032018 7.1.txt](https://github.com/xXJamieXx/paradox-bugs/files/9032425/CitizenFX_log_2022-07-02T032018.7.1.txt)

**Comment by Sly-Panda** [comment]
Will be fixed next update, until then if you encounter the task try going into first person.  There is something invisible blocking the third eye event in third person at those particular tasks but going first person should make it workable.
