### ISSUE TITLE
[BUG] Diving Symbols go away so cant pick up

### ISSUE THREAD

**Issue by Mac-ceo** [xXJamieXx/paradox-bugs#541]
### Your Discord Name

mac_ceo#7021

### A clear and concise description of what the bug is

When getting close to diving ? it will disappear it onnly happens sometimes
 

### Steps to Reproduce the Bug

1. go to last diving spot
2. try to collect 
3. get close 
4. boom gone

### Expected Behavior

to get close and it be able to get collected 

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/qKn224m1unVWi/d1337Z2NBZOe?invite=cr-MSw0TjcsNjIwNTkzNzQs

### Log File

[CitizenFX_log_2022-07-02T155742.log](https://github.com/xXJamieXx/paradox-bugs/files/9033304/CitizenFX_log_2022-07-02T155742.log)

**Comment by Sly-Panda** [comment]
Should hopefully be sorted next update
