### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by EmmettIsTRASH** [xXJamieXx/paradox-bugs#544]
### Your Discord Name

EmmettIsTRASH#3911

### A clear and concise description of what the bug is

Basically, within the High Command Boss menu I appear to them as Commissioner. Due to that, they are not able to set me into the Sheriff position. I still appear as an Undersheriff in my MDT though.

### Steps to Reproduce the Bug

1. Open MDT to see Undersheriff status.
2. Have HC attempt to promote you, but instead appear as Commissioner.

### Expected Behavior

Be shown to HC as Undersheriff, and allow HC to promote me to Sheriff in the MDT.

### Screenshots/Videos

https://cdn.discordapp.com/attachments/528317609159032832/993604250728931458/unknown.png

I'll upload a picture of what HC sees whenever I get a chance.

### Log File

[CitizenFX_log_2022-07-04T183546.log](https://github.com/xXJamieXx/paradox-bugs/files/9041746/CitizenFX_log_2022-07-04T183546.log)

**Comment by xXJamieXx** [comment]
Should be fixed.
