### ISSUE TITLE
[BUG] Boss Menu

### ISSUE THREAD

**Issue by 211Walker** [xXJamieXx/paradox-bugs#545]
### Your Discord Name

tonytone883#4146

### A clear and concise description of what the bug is

Boss menu is not working properly. It is not allowing me to change to proper job title within the departments and  it also gives the officer a high command title.

### Steps to Reproduce the Bug

Open Boss Menu
Select BCSO
Select manage under Emmett brown
Change job title to sheriff
Job title does not change but gives and a Commissioner's title under HC 

### Expected Behavior

Open Boss Menu
Select BCSO
Select manage under Emmett Browne
Change job title to Sheriff
Job title should change to Sheriff 

### Screenshots/Videos

https://user-images.githubusercontent.com/96933759/177457605-cc92ac06-4323-42f0-811d-be4110a41591.mp4

**Comment by xXJamieXx** [comment]
@211Walker Pushed a fix if you could test it when you get a chance :)
