### ISSUE TITLE
[BUG] <RACING TABLETS INTERFACE>

### ISSUE THREAD

**Issue by Tokentys** [xXJamieXx/paradox-bugs#546]
### Your Discord Name

TokenTys#7692

### A clear and concise description of what the bug is

Upon using the "Racing Tablet" you can not start a race nor can you exit the tablet, you are forced to restart to get out of the interface.

### Steps to Reproduce the Bug

1. Use a racing Tablet
2. Try to exit the tablet/start a race/ preview course
3. No action should work

### Expected Behavior

Once using the tablet you are then stuck in the interface and arent able to ext nor start any of the races.

### Screenshots/Videos

n/a

**Comment by baxepw** [comment]
Today you cannot open the tablet at all. When used nothing happens.

**Comment by xXJamieXx** [comment]
Fixed next restart.
