### ISSUE TITLE
[BUG] Customs and Upgrades currently unavailable.

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#547]
### Your Discord Name

OwlCherry#6969

### A clear and concise description of what the bug is

All Benny's and Bikini Tow HQ no longer have the customization features.

### Steps to Reproduce the Bug

1. Enter a bikini tow or benny's,
2. Attempt to enter menu
3. No menu option is given

### Expected Behavior

you should be given access to the menu to customize the vehicle

### Screenshots/Videos

no screenshots/video just nothing opens

### Log File

[CitizenFX_log_2022-07-07T002709.log](https://github.com/xXJamieXx/paradox-bugs/files/9059880/CitizenFX_log_2022-07-07T002709.log)
[CitizenFX_log_2022-07-07T013429.log](https://github.com/xXJamieXx/paradox-bugs/files/9059884/CitizenFX_log_2022-07-07T013429.log)

**Comment by OwlCherry** [comment]
Was working immediately after the 5pm Est restart, however seems to have stopped working again

**Comment by Sly-Panda** [comment]
Anyone else experiencing this issue just spam E the first time you go in there and it will eventually open/work going forward.  Fix will be rolled out.

**Comment by xXJamieXx** [comment]
Seems to be fixed.
