### ISSUE TITLE
[BUG] Boss actions not working

### ISSUE THREAD

**Issue by baxepw** [xXJamieXx/paradox-bugs#548]
### Your Discord Name

baxe#0666

### A clear and concise description of what the bug is

Past couple days been trying to use the boss menu inside of Nismos interior. When trying to open the menu when you third eye you can see it but when clicked on nothing happens.

### Steps to Reproduce the Bug

1. Go in Nismos interior to the laptop that has the Boss actions
2. Third eye to open
3. Menu does not open 

### Expected Behavior

1. Go in Nismos interior to the laptop that has the Boss actions
2. Third eye to open
3. Menu opens and can fire/ change roles

### Screenshots/Videos

https://streamable.com/pbt7sy

### Log File

[CitizenFX_log_2022-07-08T005322.log](https://github.com/xXJamieXx/paradox-bugs/files/9068421/CitizenFX_log_2022-07-08T005322.log)

**Comment by Sly-Panda** [comment]
The menu works as intended, you need to be set to the correct rank by the registered "owner" to be able to access it.
