### ISSUE TITLE
[BUG] not able to finish trash route

### ISSUE THREAD

**Issue by madsskyy** [xXJamieXx/paradox-bugs#549]
### Your Discord Name

madsskyy#2165

### A clear and concise description of what the bug is

When on the trash route, when you get to skull island, there are no trash bins and you cant get the trash anymore from the area it was in with the new third eye system. 

### Steps to Reproduce the Bug

1. do trash run
2. get skull island stop
3. try to get trash

### Expected Behavior

Either there's a working trash bin or just remove the location so i can finish my trash route

### Screenshots/Videos

![FiveM® by Cfx re -  Original  Paradox Gaming RP _ 3+ years _ discord gg_paradoxgaming 7_8_2022 1_45_10 AM](https://user-images.githubusercontent.com/103598492/177926837-d0881f4d-9240-49a8-9fdb-512a54f84aab.png)
![FiveM® by Cfx re -  Original  Paradox Gaming RP _ 3+ years _ discord gg_paradoxgaming 7_8_2022 1_46_36 AM](https://user-images.githubusercontent.com/103598492/177926844-2eb0145d-c6e7-410c-aa0c-547f7f62bfb8.png)
![FiveM® by Cfx re -  Original  Paradox Gaming RP _ 3+ years _ discord gg_paradoxgaming 7_8_2022 1_45_17 AM](https://user-images.githubusercontent.com/103598492/177926846-e843cb1a-8255-4545-91e7-c0ad5852931d.png)

**Comment by xXJamieXx** [comment]
Fixed next restart.
