### ISSUE TITLE
[BUG] Jerry Can Refill Too Expensive

### ISSUE THREAD

**Issue by tusktheshrew** [xXJamieXx/paradox-bugs#551]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

Trying to refill Gas in Jerry Can, and it reports that I have to pay 10,000 for it.

### Steps to Reproduce the Bug

1. Try to Refuel Jerry can from Gas Pump

### Expected Behavior

Not have 10,000 charge for Gas

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98053772/178091943-d82a5839-1245-4a20-9491-cd193f5ba05a.png)

### Log File

[JerryCanTooHigh.txt](https://github.com/xXJamieXx/paradox-bugs/files/9075882/JerryCanTooHigh.txt)

**Comment by xXJamieXx** [comment]
Fixed next restart.
