### ISSUE TITLE
[BUG] 'locked' doors arent locked

### ISSUE THREAD

**Issue by Mac-ceo** [xXJamieXx/paradox-bugs#552]
### Your Discord Name

mac_ceo#7021 RILLLEY

### A clear and concise description of what the bug is

when i go to lock the door to ward a in pillbox it says its locked but its not

### Steps to Reproduce the Bug

1. unlock door
2. Go through
3. lock the door
4. find that the doors not locked

### Expected Behavior

To lock it and it stays shut

### Screenshots/Videos

https://medal.tv/games/gta-v/clips/rBNkvG5esGp2x/d1337XZqDlxc?invite=cr-MSxDMUcsNjIwNTkzNzQs

### Log File

[CitizenFX_log_2022-07-09T055756.log](https://github.com/xXJamieXx/paradox-bugs/files/9075975/CitizenFX_log_2022-07-09T055756.log)

**Comment by xXJamieXx** [comment]
Can't reproduce this issue.
