### ISSUE TITLE
[BUG] Police Impound not working again

### ISSUE THREAD

**Issue by JaxCreed** [xXJamieXx/paradox-bugs#553]
### Your Discord Name

Spicy#5426

### A clear and concise description of what the bug is

The police impound (When a vehicle gets more then 3 strikes) does not work. it was fixed at one point now people with 3 strikes can get their car out of normal impound instead of having to reach out to PD to be fined and receive their vehicle

### Steps to Reproduce the Bug

Call for police impound on the car itself or park the car in the red arrow at impound both they both do not end up inside the police impound itself. this was working at the start of 3.0 and then stopped working at an unknown time.

### Expected Behavior

1 Call for police seizure or physically park the car at impount to be seized
2 Car goes into police impound
3 Civ reaches out to PD to get their car out
4 We fine and retreive their vehicle for them
5 Criminal has their car back

### Screenshots/Videos

https://i.imgur.com/BPPuQtq.png https://i.imgur.com/iqQZYqn.png https://i.imgur.com/RX9ijlr.png

### Extra Notes (Optional)

i can get logs if needed just will need to put a car in the impound first

**Comment by xXJamieXx** [comment]
Fixed next restart.
