### ISSUE TITLE
[BUG] Postal 225 f1 repair menu

### ISSUE THREAD

**Issue by erniexhamer** [xXJamieXx/paradox-bugs#555]
### Your Discord Name

Ernie Hamer#5237

### A clear and concise description of what the bug is

The Los Santos Customs at Postal 225 does not allow use of F1 menu to repair vehicle

### Steps to Reproduce the Bug

1. Go inside Los Santos Customs location at postal 225
2. attempt to repair vehicle using F1 menu

### Expected Behavior

I believe this location should also have repair as an option in F1

### Screenshots/Videos

https://i.imgur.com/UfsFOQO.jpeg

**Comment by xXJamieXx** [comment]
Added next restart.
