### ISSUE TITLE
[BUG] Mine Bauxite Rocks Can't Mine Ore

### ISSUE THREAD

**Issue by tusktheshrew** [xXJamieXx/paradox-bugs#558]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

Trying to mine the Bauxite ore veins, but no third eye menu comes up to start mining.

### Steps to Reproduce the Bug

Step up to a bauxite ore vein
Left Alt[Third Eye]
No Menu shows up.

### Expected Behavior

3rd eye menu shows up, and mine option comes up.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98053772/178602644-83e8ac73-c8fc-4062-9e10-f35ed0830526.png)
![image](https://user-images.githubusercontent.com/98053772/178602731-0602c8af-54c0-4b54-b28f-d3d57ff84243.png)
![image](https://user-images.githubusercontent.com/98053772/178602803-35fe6593-92b0-45c9-854b-e45e13ca238b.png)

### Extra Notes (Optional)

Diamond Veins may be broken as well in the mines.
![image](https://user-images.githubusercontent.com/98053772/178603116-4bf5c2fa-02ca-4e38-9bfc-ee1e34ec39ea.png)

### Log File

[BauxiteMineRocks.txt](https://github.com/xXJamieXx/paradox-bugs/files/9097133/BauxiteMineRocks.txt)

**Comment by xXJamieXx** [comment]
Should be fixed.
