### ISSUE TITLE
[BUG] Hunting Can't Sell Carcasses

### ISSUE THREAD

**Issue by tusktheshrew** [xXJamieXx/paradox-bugs#560]
### Your Discord Name

Shrew#1219

### A clear and concise description of what the bug is

Trying to sell carcasses in the deposit box, try ton confirm sale, but it doesn't sell the carcasses.

### Steps to Reproduce the Bug

1. Hunt
2. Bring carcasses to Carcass buyer
3. put meat in sell box
4. try to sell.

### Expected Behavior

Money given for each carcass corresponding with Quality.

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/98053772/178781704-1faf30b7-5271-4451-ae25-4739a47046ca.png)
![image](https://user-images.githubusercontent.com/98053772/178781951-50a46b1f-b2fd-4e6c-82f9-ed76257c8f1d.png)

### Extra Notes (Optional)

Civilians have a hard time with earning money by itself with hunting.

### Log File

[HuntingCarcasses.txt](https://github.com/xXJamieXx/paradox-bugs/files/9104107/HuntingCarcasses.txt)

**Comment by xXJamieXx** [comment]
Fixed next restart.
