### ISSUE TITLE
[BUG] Interior Door Locks

### ISSUE THREAD

**Issue by Sly-Panda** [xXJamieXx/paradox-bugs#58]
**Your Discord Name**
SlyPanda#8576

**Describe the bug**
If you load in inside an interior (almost always happens) or enter an interior just after loading in (Less frequently) you will not be able to interact with the first lockable door you go to.  To fix it you have to go to any other door and come back to it.

**To Reproduce**
1.  Log out inside an interior behind a locked door
2.  Log back in
3.  Try unlock the first lockable door you see
4.  You should not be able to interact with the locks and it will either let you walk through like it's locked or won't let you through
5.  Go to any other lockable door and interact with it
6.  Doors will then work as normal

**Expected behavior**
Door lock status to sync each time.

**Additional context**
Happens both when employed as EMS or LEO both on and off duty, not sure if it happens with non-ps whitelisted people but folk often are roaming behind locked doors so may be more widespread.

Couple of clips of the weird behaviour from this morning
https://streamable.com/ai2sew
https://streamable.com/tyfso2

**Comment by JnKTechstuff** [comment]
Fixed: https://github.com/xXJamieXx/Paradox-3.0/commit/bd5dffaad685ad79250dff450c5aaba98cb8e980
