### ISSUE TITLE
[BUG] Respawns as a different skin

### ISSUE THREAD

**Issue by ChocoDiosa** [xXJamieXx/paradox-bugs#60]
**Your Discord Name**
𝐵𝑖𝑡𝑐𝘩-𝑠𝑒𝑛𝑠𝑒𝑖™#9234

**Describe the bug**
Can’t seem to get back into my own ped but instead I respawn as Danny with my character’s outfit but with a different skin color and hair color. I tried changing it at the barber shop but it won’t let me choose any other color than green. I’ll put the picture below. I also added an original picture of my character. 

Hopefully you guys are able to fix it. 
![D6A83060-10FF-44A9-AFF5-0F335681928C](https://user-images.githubusercontent.com/97263693/148493320-2df37f61-3557-4ddd-a133-456c6c3a9be3.png)
![B9AEB74C-12DB-46F9-9050-A876D9DB9F5E](https://user-images.githubusercontent.com/97263693/148493386-14553a1d-2894-4aff-aa37-7ebb70bc3d87.jpeg)

**Comment by xXJamieXx** [comment]
@ChocoDiosa We need screenshots of your F8 and/or the log from the instance where this occurs. Otherwise we cannot do anything.

**Comment by ChocoDiosa** [comment]
Oh jeez, I was told to check f8 for any but there was none. Didn’t think I needed to screenshot. If it happens again I’ll take a screenshot of it.

**Comment by ChocoDiosa** [comment]
![Uploading F98ACA03-AFA4-4CB6-AF51-30C74046E3E9.png…]()

**Comment by ChocoDiosa** [comment]
It happened again. 
![Uploading 82BA63E3-2BFC-4350-9DC7-E116509E26F5.png…]()

**Comment by ChocoDiosa** [comment]
Another bug 
![Uploading AED574ED-537E-429B-BA9A-87CE14E3F28D.png…]()

**Comment by xXJamieXx** [comment]
Closing this but keeping #69 open to continue investigating this issue.
