### ISSUE TITLE
lockpicks with house robberies 

### ISSUE THREAD

**Issue by ithegreatgatsby** [xXJamieXx/paradox-bugs#61]
*Chris**
Chris]

**Describe the bug**
[A clear and concise description of what the bug is]
Lockpicks cost $250 now due to the durability change. When robbing a house it uses the whole lockpick which cuts into profits a lot when they cost so much as well as takes away the risk since they never have a lockpick on them if they get caught by the cops
**To Reproduce**
[Steps to reproduce the bug]
1. Rob a house
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]
need a diff kind of lockpick or make the lockpicks lose durability with each house you rob
**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by SterlingMoss** [comment]
this^
