### ISSUE TITLE
Tow liverys

### ISSUE THREAD

**Issue by ithegreatgatsby** [xXJamieXx/paradox-bugs#62]
**Your Discord Name**
[Enter your Discord name]
Chris
**Describe the bug**
[A clear and concise description of what the bug is]
Tow liverys got reverted somehow you can find them again in developer chat.
**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment]
Resolved after restart.
