### ISSUE TITLE
[ENHANCEMENT] Owned vehicles disappear immediately if your head pops

### ISSUE THREAD

**Issue by SterlingMoss** [xXJamieXx/paradox-bugs#66]
SterlingMoss#1596

If your head pops or if you need to take a nap for any reason, your vehicle will be gone when you come back, leaving you stranded wherever you happened to be. This makes things difficult and puts you in sketchy situations (i.e. You have to steal a car and risk getting the cops called on you)

**Requested behavior**
I would request that your car stays around for 15 minutes or so after you fly out/your head pops so you don't have to stop everything you're doing to retrieve your car from the impound.

**Comment by xXJamieXx** [comment]
Deferred for if/when we go back to server-side spawning

**Comment by JnKTechstuff** [comment]
Possibly fixed: https://github.com/xXJamieXx/Paradox-3.0/commit/2c0071188fcabe2e73af1424b3790fd1483608d8
