### ISSUE TITLE
[BUG] Clothes changing hair colors 

### ISSUE THREAD

**Issue by Timmy636** [xXJamieXx/paradox-bugs#68]
**Your Discord Name**
Timmy#8418

**Describe the bug**
So this has been happening for a while now, Whenever I go to change my clothes it will work but like the 2nd-3rd time it completely changes my hair and face I am not sure if it happens to other people or just me but with that being said I went to the clothes shop and hair salon to changer it back to normal I saved the outfits again and it gave me the same problem  

**To Reproduce**
[Steps to reproduce the bug]
1. Go to apartments 
2. Change into clothes about 6 times or so 
3. Observe how the individual switches 

**Expected behavior**
Changing clothes without any change of character 
**Screenshots**
https://medal.tv/games/gta-v/clips/77dhNnmlJOmDt/d1337rHnebmL?invite=cr-MSxid3QsMzY5ODkzNDgs

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment]
Resolved with https://github.com/xXJamieXx/Paradox-3.0/pull/69/commits/6585d52faddc1aa7288fdaa73a8c2f0e7732a402
