### ISSUE TITLE
[BUG] Faces type reverts back to normal.

### ISSUE THREAD

**Issue by natashajoan** [xXJamieXx/paradox-bugs#69]
natasha_joan#7098

**Describe the bug**
Before flying out, your characters face will be normal, but once you fly back in, you have the default face, but all the customisation like the nose height etc are all the same that you had before you flew out, it's just the type of face selection that's changed, hair and everything else is fine.

**To Reproduce**

1. Fly out
2. Fly back in (Sometimes you can tell on the character selection screen that your characters face has messed up, even before you fly in)
3. 

**Expected behaviour**
The faces shouldn't have to be changed on every fly in, I expect that the way I fly out, should be what I look like when I fly back in, whether that's in minutes, hours or days. 

**Screenshots**
https://youtu.be/OAkCVuyTf0A
https://youtu.be/dG_HPqtZyf0

**Additional context**
Steps tried to fix this include: Changing the face, saving, then changing the outfit and saving as new, then deleting the old outfit. Neither of these steps have fixed the issue.

**Comment by doppelshire** [comment]
Doesn't properly save inside barber shop/salon either.

If you select a face, and confirm/save changes, your character will have the face you chose.  However, when you open the barbershop menu again, it will show your face is set to option 0.

I did not experience the default face issue until I attempted to edit my character further in the barbershop menu.

**Comment by doppelshire** [comment]
https://streamable.com/2j674r

Video shows the number selection resetting to zero after purchasing selection 45

**Comment by natashajoan** [comment]
The above also happens when you go to the clothing store and don't save there and just exit, it reverts you back to the default face.

**Comment by OwlCherry** [comment]
i encountered same issue, error code i recieved when i flew in a danny again was this
https://i.imgur.com/bUY9eLi.png

**Comment by xXJamieXx** [comment]
Resolved with https://github.com/xXJamieXx/Paradox-3.0/pull/69/commits/6585d52faddc1aa7288fdaa73a8c2f0e7732a402
