### ISSUE TITLE
Bennys not allowing color changing

### ISSUE THREAD

**Issue by monk3ythund3r** [xXJamieXx/paradox-bugs#71]
**Your Discord Name**
Monk3yThund3r5594

**Describe the bug**
bennys is not allowing color changes

**To Reproduce**
[Steps to reproduce the bug]
1. go to bennys
2. try to change color
3. 

**Expected behavior**
Being able to change colors of vehicles
**Screenshots**
https://i.imgur.com/DpFAzAF.jpeg

**Additional context**
[Add any other context about the problem here]

**Comment by ithegreatgatsby** [comment]
new car? Put it in the garage at lease once and take it back out and then the color should be able to be changed

**Comment by xXJamieXx** [comment]
Deferred until new mod shop

**Comment by JnKTechstuff** [comment]
Fixed: https://github.com/xXJamieXx/Paradox-3.0/commit/1f3fdb6dbd7e7d0d3b4d5493ae793ac7eac4f4d8
