### ISSUE TITLE
[BUG] Almost impossible to get into PD car with suspect in the back

### ISSUE THREAD

**Issue by JaxCreed** [xXJamieXx/paradox-bugs#73]
**Your Discord Name**
[Spicy#5426]

**Describe the bug**
[After putting suspect in the back of the cruiser and trying to get in the vehicle will say unlocked 50 times and still will not be able to get in. Have tried running away multiple times still with not being able to get in. Only way we got it working was having another officer put the suspect in the vehicle after the driver has already gotten into the vehicle ]

**To Reproduce**
[Steps to reproduce the bug]
1. Put suspect into car 
2. Try to get into vehicle
3. Wont work

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment]
@JaxCreed Cannot reproduce this issue myself, could you attach a video of the bug so we can see it happening. Please also open your F8 during the video after reproducing the bug.

**Comment by JnKTechstuff** [comment]
Closed due to no response
