### ISSUE TITLE
[BUG] Can't panic when down but on as LEO

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#74]
**Your Discord Name**
OwlCherry#6969

**Describe the bug**
I noticed when I went down I am unable to panic via F1 causing me to have to put in a /911 which isn't as effective.
Both within and out of vehicle

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment]
@OwlCherry Cannot reproduce this, a video may help discover why.

**Comment by OwlCherry** [comment]
https://streamable.com/27pwn2

**Comment by OwlCherry** [comment]
That is a video showing nothing on the wheel to allow me to panic

**Comment by xXJamieXx** [comment]
Thanks for that, the issue is now resolved next restart.

**Comment by OwlCherry** [comment]
Thank you Jamie
