### ISSUE TITLE
[BUG] Stash not being accessible

### ISSUE THREAD

**Issue by s0ur3n** [xXJamieXx/paradox-bugs#76]
souren #4664

Stash not being accessible in Alta Apartments sometimes, hard nap should solve the issue.
Has happened multiple times to me, might have to do with pressing e to open stash multiple times when approaching stash
No error shown in F8

1. Enter apartment 
2. Walk toward stash
3. Press e multiple times while approaching stash

Expected stash to open showing items stored and player pockets

![Stash none](https://user-images.githubusercontent.com/96967755/148656798-d1c1de26-32c9-478f-9419-905a3744d90d.PNG)

**Comment by JnKTechstuff** [comment]
Unable to replicate
