### ISSUE TITLE
[ENHANCEMENT] Proper Emotes/props for different items.

### ISSUE THREAD

**Issue by OmegaGrape** [xXJamieXx/paradox-bugs#78]
**Your Discord Name**
OMEGA#0821

**Describe the annoyance**
When you drink stuff like coke and coffee it gives you the animation/prop of drinking water. I'm not sure how many items use the same props/animations I know the food items all use the Sandwich prop too

**To Reproduce**
[Steps to reproduce the annoyance]
1. Buy coffee/coke 
2. Drink

**Requested behaviour**
Have a Coke can for Coke and a Coffee cup for coffee. Just the proper props for the item you use if possible.

**Screenshots**
[If applicable, add screenshots to help explain your enhancement]

**Additional context**
I know this is very insignificant just thought I would suggest it.

**Comment by xXJamieXx** [comment]
Done.
