### ISSUE TITLE
[ENHANCEMENT] Add a place/option to Sell a vehicle that has been purchased

### ISSUE THREAD

**Issue by JnKTechstuff** [xXJamieXx/paradox-bugs#8]
**Describe the annoyance**
- Can't sell a car once bought 

**Requested behavior**
- Add a place/option to Sell a vehicle that has been purchased

**Additional context**
From to-do list

**Comment by johndoe6969007** [comment]
yeah that would be really great if you could sel your car

**Comment by pulsevr34** [comment]
I second this

**Comment by JnKTechstuff** [comment]
Posting useless "I second this" when I'm the ones who made it contributes nothing but to see yourself show in server-commits
