### ISSUE TITLE
[BUG] New EUP Clips With Hair Suddenly

### ISSUE THREAD

**Issue by AstroKing98** [xXJamieXx/paradox-bugs#80]
**Your Discord Name**
Astro#4786

**Describe the bug**
Hair is completely clipped through most baseball caps (especially new police hat EUP)

**To Reproduce**
[Steps to reproduce the bug]
1. Wear any of the hats in the clothing store from new EUP

**Expected behavior**
Hair will go through hat, some of hat won't show.

**Screenshots**
https://imgur.com/a/8D61jov
https://imgur.com/KY5BqEL

**Comment by JnKTechstuff** [comment]
Was no longer an issue
