### ISSUE TITLE
[BUG] Boss menu withdraw funds

### ISSUE THREAD

**Issue by LittletonSniper** [xXJamieXx/paradox-bugs#81]
LittletonSniper

Not being able to withdrawal money from department funds

When going into your Boss Menu as a Captain/Sheriff and going into department funds, you are not able to withdrawal money. It tells you, "you do not have enough money" although I most definitely do have enough. No errors in F8
**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
When withdrawing money from the department that you have, it to actually give it to you and not say you don't have enough

**Screenshots**
https://user-images.githubusercontent.com/79656405/148722767-9f455860-4e62-49ca-8808-3b669efa8f89.png (copy link and paste it)

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment]
Unable to reproduce this issue. The exact steps you take which produces the issue may be more helpful, including amounts etc.
