### ISSUE TITLE
[BUG] Danny Issue 

### ISSUE THREAD

**Issue by Hembry** [xXJamieXx/paradox-bugs#82]
**Your Discord Name**
_Hembry_#9901

**Describe the bug**
Flew in with green hair and danny face (never happened to me before) so went to the hair shop like Jake said and attempted to fix my char. Reset all the parameters so had to go back and redo all of it. Only issue is I cannot change facial hair color. Stuck on green

**To Reproduce**
1. Fly in broken
2. Go to hair shop
3. Try on facial hair

**Expected behavior**
Able to change my facial hair color

**Screenshots**
(https://prnt.sc/26c2oza)

**Comment by Hembry** [comment]
Saving the char appearance then relogging allowed me to change color of facial hair

**Comment by JnKTechstuff** [comment]
Remake your character or change your hair
