### ISSUE TITLE
[BUG] Putting Glasses Back on

### ISSUE THREAD

**Issue by BrotherDayZ** [xXJamieXx/paradox-bugs#83]
**Your Discord Name**
Bay Harbour Butcher#6820

**Describe the bug**
After getting punched, you are unable to put glasses back on. You have to go the locker room or the clothing store to put them back on

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xXJamieXx** [comment]
This was fixed.
