### ISSUE TITLE
Can't make Advanced lockpicks

### ISSUE THREAD

**Issue by MacFion** [xXJamieXx/paradox-bugs#84]
When trying to combine the toolkit with lockpick the combine button appears, but that's it, it's not functional. It won't combine, and even after relogging it doesn't work.  
![image](https://user-images.githubusercontent.com/67557594/148824917-b591df62-a52a-4e8a-a02f-7190d1145043.png)

**Comment by xXJamieXx** [comment]
Cannot reproduce. Seems to work fine for me.
