### ISSUE TITLE
Not combining to make advance lock picks

### ISSUE THREAD

**Issue by MacFion** [xXJamieXx/paradox-bugs#85]
When trying to combine the toolkit with lockpick the combine button appears, but that's it, it's not functional. It won't combine, and even after relogging it doesn't work.  It's also giving a weird message and wing dings thing across the top of my screen.
![image](https://user-images.githubusercontent.com/67557594/148824917-b591df62-a52a-4e8a-a02f-7190d1145043.png)
![weird cache message](https://user-images.githubusercontent.com/67557594/148827783-8d2427f3-efcd-4054-8056-c6b1af9728a3.png)

**Comment by xXJamieXx** [comment]
Duplicate of #84
