### ISSUE TITLE
[BUG] Items disappearing from PD glovebox

### ISSUE THREAD

**Issue by PadawanPepsi** [xXJamieXx/paradox-bugs#86]
**Your Discord Name**
PadawanPepsi#6898

**Describe the bug**
I placed items into the glovebox of my vehicle. After being away from the vehicle for a period of time when i returned to the vehicle the glovebox was empty. The vehicle was in a place where no one would have been able to get to it and the vehicle was locked. 

**To Reproduce**
[Steps to reproduce the bug]
1. Unkown
2. 
3. 

**Additional context**
The car was parked in between the two gates at Bolingbrook penitentiary. I walked to the center of the prison yard and in the infirmany. I was away from the car for maybe 30 mins.

**Comment by PadawanPepsi** [comment]
UPDATE i went to the orange trash can at MRPD and my evidence was there. I was not able to pull it out at all but another cop was. So somehow it poofed there

**Comment by PadawanPepsi** [comment]
MAJOR UPDATE PROBLEM FOUND 

All Pd Gloveboxes are connected so what happened was i put it in my glove box and shortly after another officer in another car saw it in their LSPD glove box and put it in the trash!

**Comment by JnKTechstuff** [comment]
Fixed: https://github.com/xXJamieXx/Paradox-3.0/pull/72
