### ISSUE TITLE
[BUG] Gas is burnign way to fast 

### ISSUE THREAD

**Issue by PadawanPepsi** [xXJamieXx/paradox-bugs#87]
**Your Discord Name**
PadawanPepsi#6898

**Describe the bug**
If you drive about 2 miles you go through a quater of a tank

**To Reproduce**
[Steps to reproduce the bug]
1.  fill car
2. drive
3. gas go bye bye lol

**Additional context**
Started after the fuel target update

**Comment by BrotherDayZ** [comment]
Gas also costs a lot!

**Comment by xXJamieXx** [comment]
Fixed https://github.com/xXJamieXx/Paradox-3.0/commit/33a57e379e56e42de7b6829bad8c3d8f97adb174
