### ISSUE TITLE
[BUG] Mors Mutual

### ISSUE THREAD

**Issue by BrotherDayZ** [xXJamieXx/paradox-bugs#88]
**Your Discord Name**
BDZ#0001

**Describe the bug**
The Mors Mutual app on the phone no longer tracks your vehicle.

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment]
Probably due to client side spawning changes. Deferred until we potentially return to server side spawning.

**Comment by JnKTechstuff** [comment]
Fixed: https://github.com/xXJamieXx/Paradox-3.0/commit/63926b5796cb3ba227d3e447888956c0748ada67
