### ISSUE TITLE
[BUG] Fingerprint scanning not working

### ISSUE THREAD

**Issue by BrotherDayZ** [xXJamieXx/paradox-bugs#89]
**Your Discord Name**
BDZ#0001
**Describe the bug**
Fingerprint scanner is not working, unable to acquire the fingerprint from any suspect.

**To Reproduce**

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by JnKTechstuff** [comment]
Being rewritten anyway

**Comment by JnKTechstuff** [comment]
This has worked
