### ISSUE TITLE
[ENHANCEMENT] Move/redo garage locations

### ISSUE THREAD

**Issue by JnKTechstuff** [xXJamieXx/paradox-bugs#9]
**Describe the annoyance**
- Garage locations suck

**Requested behavior**
- Place them at the apartments and some better spots

**Additional context**
From to-do list

**Comment by xXJamieXx** [comment]
Done in this commit: https://github.com/xXJamieXx/Paradox-3.0/commit/589f78077080e84a47f06a9679f2e055b1fd9d16#diff-1d4c54ab5a4d4563d3a808ebd20d92a8665c4a92b7d11e49e36eea5325ccc255
