### ISSUE TITLE
[BUG]  busy in MDT not saving

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#90]
**Your Discord Name**
OwlCherry#6969

**Describe the bug**
When officers mark themselves as busy, this does not save and automatically toggles off once MDT is closed

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by xXJamieXx** [comment]
Fixed.
