### ISSUE TITLE
[BUG] Gas station fuel issues

### ISSUE THREAD

**Issue by OwlCherry** [xXJamieXx/paradox-bugs#92]
**Your Discord Name**
OwlCherry#6969

**Describe the bug**
After a mod mail regarding refueling issues, i noticed gen chat blow up regarding it. i went in city to test and was not giving refueling option via third eye.

photo in comments as well as additional info i gathered from others.

**To Reproduce**
[Steps to reproduce the bug]
1. 
2. 
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
[Add any other context about the problem here]

**Comment by OwlCherry** [comment]
https://i.imgur.com/pm54PXN.png

**Comment by OwlCherry** [comment]
https://cdn.discordapp.com/attachments/930454870681583696/930454985240637470/IMG_6597.mov

**Comment by xXJamieXx** [comment]
Not able to reproduce. Works fine.
