### ISSUE TITLE
[BUG] Repairing bricks your vehicle in Benny's

### ISSUE THREAD

**Issue by CorFinn** [xXJamieXx/paradox-bugs#93]
**Your Discord Name**
GrandNagus#9705

**Describe the bug**
Repairing in PC 101 Benny's bricks the car. Drivable by others. Not by owner.

**To Reproduce**
[Steps to reproduce the bug]
1. Damage car.
2. Take it to Benny's
3.  Repair it.

**Expected behavior**
Car should be drivable after repair. Instead, it bricks the car for the driver, but others can get in the driver's seat and drive it.

**Screenshots**
[If applicable, add screenshots to help explain your problem]

**Additional context**
As I was writing this, another person came in to repair a different vehicle, a dune buggy. He experienced the exact same issue. He repaired, then couldn't drive his own vehicle. I was able to drive it. Running to the impound, and pulling out the car fixed the issue temporarily, until he repaired again to see if he could repeat the issue.

[EDIT] Removed Car Make/Model, as it happened with multiple vehicles.

**Comment by xXJamieXx** [comment]
Unable to reproduce.
