### ISSUE TITLE
Electrician Job in Jail

### ISSUE THREAD

**Issue by prdxFairBZ** [xXJamieXx/paradox-bugs#95]
**Your Discord Name**
Bru

**Describe the bug**
When attempting to do the electrician job, there is a location behind a fence

**To Reproduce**
N/A

**Expected behavior**
Being able to get to the marker

**Screenshots**
vector4(1625.02, 2575.46, 45.32, 338.95)
![image](https://user-images.githubusercontent.com/96957728/148999436-07b09904-c12f-4986-a95b-8f71ccf8d44f.png)

vector4(1622.62, 2508.27, 45.32, 104.95)
![image](https://user-images.githubusercontent.com/96957728/148999694-72d22575-2e97-4ae8-9ae5-d3e0d3f8b1ee.png)

**Comment by xXJamieXx** [comment]
Fixed.
